### ISSUE TITLE
Support for Xiaomi Mi 9T

### ISSUE THREAD

**Issue by reyis4402** [Divested-Mobile/DivestOS-Build#10]
Xiaomi Mi 9T has official Lineage support. Can DivestOS developers provide support for Mi 9T?

**Comment by SkewedZeppelin** [comment]
I seem to have missed this.
I will add davinci after the security update batch.

**Comment by reyis4402** [comment]
This is very good news. I'm excited to try

**Comment by reyis4444** [comment]
Hello, I have uploaded the zip file for Mi 9T via twrp. However, the system did not boot.

**Comment by reyis4444** [comment]
Screen stays on boot

**Comment by reyis4444** [comment]
Twrp app = OrangeFox

**Comment by SkewedZeppelin** [comment]
Does it show the DivestOS logo or just the Xiaomi one?

Can you try flashing via the DivestOS recovery?

**Comment by reyis4444** [comment]
Only Xiaomi logo nothing else

**Comment by reyis4402** [comment]
Can I use Divest with Orangefox recovery? I don't want to lose my root access.

**Comment by SkewedZeppelin** [comment]
Use the volume keys to reboot to fastboot
Run `fastboot flash recovery divested-17.1-20211003-dos-davinci-recovery.img`
Then use the volume keys to reboot to recovery
Then initiate update via sideload
then run `adb sideload divested-17.1-20211003-dos-davinci.zip`

**Comment by reyis4402** [comment]
is it possible for me to install orangefox twrp again after the process is finished? And make an update via Orangefox?

**Comment by SkewedZeppelin** [comment]
Yes, it should work for testing purposes.

**Comment by SkewedZeppelin** [comment]
Davinci appears to be booting according to the update check counter on the downloads page.
Give it a try if you are adventurous.
Be sure to backup fully first.

**Comment by reyis4402** [comment]
hello, sorry for the late reply


![Screenshot_20211130-084303_Ayarlar](https://user-images.githubusercontent.com/60405617/144139113-3d28ce2b-1639-4e8c-986a-eea8c5e4e010.png)
![Screenshot_20211130-084420_F-Droid](https://user-images.githubusercontent.com/60405617/144139117-d3c89f1d-cf6e-47f9-b6e5-bde7cbad6b20.png)

**Comment by reyis4402** [comment]
Mull browser is updated via both f-droid and divest store. Isn't that a risk for fake signature package?

**Comment by SkewedZeppelin** [comment]
> Isn't that a risk for fake signature package?

No.
Once you install an app from one source you cannot get it from another until you
uninstall.

Mull having two independently built versions is a *good* thing.

And DivestOS is pinned to only support Mull from the DivestOS repo.

**Comment by reyis4402** [comment]
I have a problem that I can't solve. If I install the latest Firmware, no ROMs boot. Only Android 10 Firmware is running.

**Comment by reyis4402** [comment]
I am using DivestOS but do I need to install the Hypatia app?

**Comment by SkewedZeppelin** [comment]
Nope.

Hypatia is just an extra if you want it.

I personally don't even use it myself.

**Comment by reyis4402** [comment]
![Screenshot_20220106-130159_Mulch](https://user-images.githubusercontent.com/60405617/148365617-99781f03-17ae-4b23-9aab-847801b76ec0.png)
![Screenshot_20220106-130139_Mull](https://user-images.githubusercontent.com/60405617/148365624-85857792-5493-4438-a1e9-d653a7431cf3.png)

**Comment by reyis4402** [comment]
Mulch& Mull

**Comment by reyis4402** [comment]
![Screenshot_20220106-130344_Ayarlar_1](https://user-images.githubusercontent.com/60405617/148365758-1320e2e9-6707-4fd3-9d66-44b1fc072738.png)

**Comment by SkewedZeppelin** [comment]
Was in the ad block list.
I've removed it.
It will be fixed in next update.

**Comment by SkewedZeppelin** [comment]
Please open a new issue for any issues you have.
