### ISSUE TITLE
Sim card software switch

### ISSUE THREAD

**Issue by elimin-8** [Divested-Mobile/DivestOS-Build#100]
Hello,
I'd like to preface this issue by first thanking the development team for this operating system they have spent time developing, I've been using it on my personal device and its been brilliant, it's nice to see a ROM with an emphasis on FOSS software :)

Now, I have an idea which I believe could significantly improve the privacy of phones running this ROM and it relates to sim cards.
Modern mobile sim cards connect to cell towers operated by major carriers in their country. Because major carriers have many towers, this allows them to perform triangulation on the signals emitted by the phone and determine the location of the user's phone and thus by proxy, the user. There are already fine grained controls for GPS functionality for this ROM, so I figured that it would also make sense to have the ability to disable sim cards within devices as and when required by the user. This could be within the settings, but I also believe there should be a tile for the drop down menu at the top of the screen to quickly allow activating and deactivating certain sim card slots, thus deactivating the cards themselves (like the disable sensors option). This also has other uses besides the privacy aspect, such as disabling your main sim card when abroad, although technically I believe this can be done by disabling roaming, but this would still allow calls and texts to come through to my knowledge.
This brings me to the disadvantage of this feature for end users, which is that whilst their sim card is disabled calls, texts and mobile data will be unavailable of course. Therefore it would be a good ideas for users to turn on their phone's sim card at regular intervals to check for messages and when they otherwise need mobile data.

Why do I think this should be integrated into DivestOS?
Well, in order to control the power state of the sim card slots, the program in question would require the android.permission.MODIFY_PHONE_STATE permission, which is only available to system apps. And since root is not provided and explicitly discouraged within the [FAQ](https://divestos.org/index.php?page=faq) (and rightly so I believe), this leaves me with no other option but to integrate this functionality directly into the ROM.

I would be very happy to create a pull request once I've managed to successfully implement this functionality myself.
Please let me know what you think :)

**Comment by SkewedZeppelin** [comment]
This is out of scope, but I'll accept patches for it given they are clean.

Regarding location: DivestOS already has numerous changes in place to reduce the
ways your carrier can acquire your location.
Like not sending IMSI to SUPL, disabling A-GPS MSA, removing OMA-DM, removing
other carrier blobs, etc.

**Comment by elimin-8** [comment]
Understood, I'll create a fork of the project and begin work on a patch.
Thank you for listing these other features of the ROM, I was not aware of these.

**Comment by elimin-8** [comment]
I unfortunately do not currently have the time to work on this. Perhaps I'll come back to it later. Consider this issue closed for now.
