### ISSUE TITLE
F-Droid still prompts for manual installation despite being installed as a system app. Plus some feedback.

### ISSUE THREAD

**Issue by ThoriumTextile** [Divested-Mobile/DivestOS-Build#101]
Hello.
I decided to revisit DivestOS, and there are still quite a few issues that prevent me from daily driving it.
First and foremost, this isn't an F-Droid issue because Lineage for MicroG doesn't have it.
Second, Divest doesn't ship with [the f-droid privapp extension](https://f-droid.org/en/packages/org.fdroid.fdroid.privileged/), which IMO is kind of like putting a V8 engine on a Fiat Seicento, and then crippling it with the transmission of a lawnmower.
So i decided to go the ol' fashioned DIY method and [found this thread](https://forum.f-droid.org/t/privileged-extension-ota-workaround-for-los-17-1/11058) and i couldn't even begin because i found out that rooted adb is disabled.
Now, i understand not being a fan of rooting, i'm one myself. Both for practical and security reasons. But this seems a bit too excessive...
Finally, i couldn't install Divest by simply running `adb update divestos.zip`. Most likely it's a fault on my end because i wiped completely my phone, and with the update command it expects an already existing OS, but i haven't tested it to be sure. Just a heads-up.
On the other hand, the website greatly improved, there is way more documentation and info.
I think that if you were to include [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore), this could be seriously up in the ranks with GrapheneOS.
(I donated 5$ btw!)

**Comment by SkewedZeppelin** [comment]
The PrivExt was removed due to security concerns and straight-up incompatibility with newly added permissions (NETWORK & SENSORS): https://github.com/Divested-Mobile/DivestOS-Build/commit/96e3fc507c10d7b9b65ef9a6dcf733d7b9039dba

Reasons against root here: https://divestos.org/index.php?page=faq#rootSupport

Please see the installation steps here: https://divestos.org/index.php?page=bootloader#fastboot

Aurora Store will never ever be default included, this project has a focus on FOSS first and foremost, users can install it if they want.

Thank you for the donation!

**Comment by ThoriumTextile** [comment]
> The PrivExt was removed due to security concerns and straight-up incompatibility with newly added permissions (NETWORK & SENSORS): [96e3fc5](https://github.com/Divested-Mobile/DivestOS-Build/commit/96e3fc507c10d7b9b65ef9a6dcf733d7b9039dba)
> 
> Reasons against root here: https://divestos.org/index.php?page=faq#rootSupport
> 
> Please see the installation steps here: https://divestos.org/index.php?page=bootloader#fastboot
> 
> Aurora Store will never ever be default included, this project has a focus on FOSS first and foremost, users can install it if they want.
> 
> Thank you for the donation!

I get the scope of the project, but i think you should give users the choice to allow some QoL customizations like unattended installs for F-Droid. Many users like myself cannot install (or simply prefer LineageOS as a base.) ROMs like Graphene and Calyx. Your ROM is a great alternative.

**Comment by SkewedZeppelin** [comment]
OK, but DivestOS *had* the PrivExt for 5 years, it was broken a few weeks back
when I added the sensors permission, I cannot just put it back.
Even if you root and put it back it still won't work, you'll hit the same issue.
