### ISSUE TITLE
FP3: vendor image outdated

### ISSUE THREAD

**Issue by EmanuelLoos** [Divested-Mobile/DivestOS-Build#102]
The vendor image included in the 18.1 build for the FP4 is outdated according to LineageOS Trust and the build number. [Here](https://support.fairphone.com/hc/en-us/articles/360048050332-FP3-Install-Fairphone-OS-offline) is the current version. However, DivestOS won't boot when flashing the vendor image from there.

**Comment by SkewedZeppelin** [comment]
You can't replace the vendor image as DivestOS includes a built one and would
also trip verified boot.


The current version of DivestOS for FP3 already has the latest 4.A.0011 blobs
blobs, but the patch level wasn't bumped.

**Comment by SkewedZeppelin** [comment]
See also the website: https://divestos.org/index.php?page=patch_levels


Using a vendor image not provided by DivestOS means you lose all deblobber
benefits.


Also of note FP3 should see 19.1 builds soon.

**Comment by SkewedZeppelin** [comment]
See also the website: https://divestos.org/index.php?page=patch_levels

Also of note FP3 should see 19.1 builds soon.
