### ISSUE TITLE
phone services use location and green notification/dot is shown

### ISSUE THREAD

**Issue by scrdcow** [Divested-Mobile/DivestOS-Build#104]
Hi! Just trying out DivestOS 19.1 on enchilada. I noticed that Phone Services is using Location and it shows by the small green notification when I turn on the lock screen for ex. I now understand that it needs to use location, but can the notification be turned off? According to a friendly fellow on matrix CalyxOS has turned that off and that could be used as help. Thanks :-)

**Comment by SkewedZeppelin** [comment]
https://github.com/Divested-Mobile/DivestOS-Build/commit/7a168302cfb14a516ec744daff31cfa11bc1d50f
https://divestos.org/index.php?page=news-future
