### ISSUE TITLE
Toast pops up when deleting photos in gallery (Enchilada - DOS19.1)

### ISSUE THREAD

**Issue by mikitakahazekura** [Divested-Mobile/DivestOS-Build#105]
![photo_2022-05-17_19-51-25](https://user-images.githubusercontent.com/24222032/168878261-c2f4149b-6157-421b-950f-a2488d27e4d5.jpg)
Steps to reproduce:

    Open Gallery
    Delete photo saved with Telegram (folder Pictures/Telegram)
    Toast Popsup and galley crashes

Device: OnePlus 6
OS: DivestOS 19.1
Build Number: SP2A.220505.002
Kernel: 4.9.227-dos.p302-g8bce3f4b0603-dirty
#1 Tue May 10 22:26:07 EDT 2022
Logcat:
[logcat2.txt](https://github.com/Divested-Mobile/DivestOS-Build/files/8710510/logcat2.txt)

**Comment by SkewedZeppelin** [comment]
This is an upstream issue.
Maybe already fixed in recent releases:
https://github.com/SimpleMobileTools/Simple-Gallery/releases

It is because it doesn't have access to manage that folder.

**Comment by mikitakahazekura** [comment]
Thanks Tad, didn't know about that. I'll close.

**Comment by SkewedZeppelin** [comment]
Actually maybe not fixed, and maybe not the apps issue?
See https://github.com/SimpleMobileTools/Simple-Gallery/issues/2344
