### ISSUE TITLE
OnePlus 7 Pro - Copy Paritions - FAILS

### ISSUE THREAD

**Issue by ToddCrimson** [Divested-Mobile/DivestOS-Build#113]
Installing DIVEST OS on OnePlus 7 Pro (guacamole)
Downloading your file ==> https://divestos.org/builds/LineageOS/guacamole/copy-partitions-guacamole.zip

When using the command ==> adb sideload copy-partitions-guacamole.zip
Getting the following error:

E: failed to verify whole-file signature
Update package verification took 0.1 s (result 1).
E:Signature verification failed
error: 21

Therefore it is not copying partitions. If I set active partition b, I can see the other Recovery image there. 

Please help provide an updated copy partition, which will work with your fastboot recovery image.

**Comment by SkewedZeppelin** [comment]
Give me a few minutes.

**Comment by SkewedZeppelin** [comment]
I've regenerated this for all devices, should work now.

**Comment by ToddCrimson** [comment]
Ok, checking now

**Comment by ToddCrimson** [comment]
yep confirming that copy partitions worked, and I finished installing DivestOS.
