### ISSUE TITLE
Network Connectivity Check - Setting Missing

### ISSUE THREAD

**Issue by ToddCrimson** [Divested-Mobile/DivestOS-Build#115]
Just installed new version of DivestOS

The URL ==> https://divestos.org/index.php?page=network_connections, states that the network connectivity check can be disabled under settings. I tried doing search for it, looked everywhere, including the Developer options, couldn't find it anywhere. 

Has that functionality been removed? If so, can I set it via ADB?

**Comment by SkewedZeppelin** [comment]
Please read the website

https://divestos.org/index.php?page=news-future#twelve

The toggle hasn't been ported yet to 19.1

You can disable it via adb via the command on
https://divestos.org/index.php?page=privacy_policy

**Comment by ToddCrimson** [comment]
Ahh, thank you... I should have read that part. 
Perfect, that helps.

**Comment by SkewedZeppelin** [comment]
I've just made it so future news is always shown on the news page, to minimize
it being overlooked.

**Comment by SkewedZeppelin** [comment]
Please read the website

https://divestos.org/index.php?page=news-future#twelve

The toggle hasn't been ported yet to 19.1

You can disable it via adb via the command on
https://divestos.org/index.php?page=privacy_policy
