### ISSUE TITLE
Minor Bug - Updater - showing current version again

### ISSUE THREAD

**Issue by ToddCrimson** [Divested-Mobile/DivestOS-Build#116]
Under Setting / Systems / Updater.
I'm on May 11th version already.
But it is still showing in list May 11, and wants to download and update. 
Just for testing, I did download from there, and applied the update.
It still shows in the list, even after deleting it. 

I'm assuming under normal working conditions, it should not show the same version to update to, which I already have installed.

**Comment by SkewedZeppelin** [comment]
That is expected.

**Comment by ToddCrimson** [comment]
Thank you

**Comment by tcrxt** [comment]
I have a follow-up question about this issue: on the page [reboot the bootlocker](https://divestos.org/pages/bootloader#fastbootLocking), it reads:

> After install of a properly signed system you must verify boot, verify functionality, verify update support, and verify the ability to factory reset.

To "verify update support", do I need to wait until an update is actually released, and then try it, or does "re-installing the current version" through the uploader is a safe guarantee that updates are supported?

**Comment by SkewedZeppelin** [comment]
@tcrxt

installing the current update is reasonably sufficient to verify updates work

please do not repeat questions on multiple platforms :slightly_smiling_face:
