### ISSUE TITLE
OnePlus 9 Pro - Starting with a Fresh, Stock, Fully updated ROM to 12 - Getting Qualcomm Crash Dump screen

### ISSUE THREAD

**Issue by ToddCrimson** [Divested-Mobile/DivestOS-Build#125]
So I've tried this a few times now.
Just bought a brand new One Plus 9 Pro yesterday (New, unlocked, directly from OnePlus - upgrading from my trusty OnePlus 7 Pro)

1. Updated the OOS to latest over the air. Nothing extra installed.
2. Running OOS at Android 12 confirmed.
3. Unlocked Bootloader, go through all your steps. Reboot.
4. Phone puts me at Qualcomm Crash Dump Screen (Research, found MSM tool to unbrick)

Started again (First unbrick with MSM)

1. Updated all OTA to 12
2. This time, did your steps on both partitions, just to be sure.
4. Again, at the end phone puts me in Crash Dump Screen

Started again (Second unbrick with MSM)

1. This time didn't do any Android 12 updates, kept it at latest Android 11
2. Again, phone puts me at Qualcomm Crash Dump Screen

Something doesn't want to work :(

As a CHECKPONT ==> I unbricked, updated, and installed LineageOS using their steps, and it works.
I don't want to keep running LineageOS, as it is userdebug and non-lockable bootloader creates a huge security GAP.

So Right now
1. I've used MSM tool to go back to Factory Default of Android 11
2. Updated to the latest OOS 12 OTA updates.

**Please help with getting this install working :)** 
I can keep you posted on updates.

**Comment by ToddCrimson** [comment]
Here is a little more detail of the sideloading process and what I see everytime.

So, after I upload the fastboot zip and finish copy partitions:
This is what I get when I sideload the DOS package 

   _Supported API: 3
   Finding update package...
   Verifying update package...
   Update package verification took 114.1 s (result 0).
   Installing update...
   Step 1/2
   Step 2/2

   Install completed with status 0._

So the above steps work beautifully

When I do the Factory reset, I get:

   _-- Wiping data...
   **E: Cannot log to file /dev/fascklogs/log**

   **E: open failed: /metadata/ota: No such file or directory**
   Formatting /data...
   Formatting /metadata...
   Data wipe complete._

Could those two errors be an issue?

**Comment by SkewedZeppelin** [comment]
You shouldn't need to use EDL to unbrick, just use volume up + power to exit
crashdump and reboot to fastboot.
Then fastboot flash whatever recovery and reboot to recovery and adb sideload
Lineage or whatever.

**Comment by ToddCrimson** [comment]
Thanks and yes I tried that too.
I was just trying few ways to eliminate any possibilities of non-success.

So what would be the next step to get Divest 19.1 rolling on OP9 PRO?

Happy to be your guinea pig - and test things out.

**Comment by SkewedZeppelin** [comment]
I have no idea.

Pixel 3, 3a, and 4a, lmi, and now OP9 are all not booting.
I suspect there is more than one issue at play.
I do not have any of these devices to test/debug with.

**Comment by ToddCrimson** [comment]
Hmm...

Well, I'm a good solid power user and experience with testing etc.
If you think of some way to test out OP9PRO or even OP7PRO.

Happy and available. 
Thanks again

**Comment by xcfmc** [comment]
I'm very eager to use this on my oneplus 9 pro as well. Mine is from T-mobile, but its unlocked and I'm running lineage on it currently. How can I help to get this running?

**Comment by SkewedZeppelin** [comment]
New OP9 builds are up, lemonade has been reported working by another user.

Give it a spin!

**Comment by SkewedZeppelin** [comment]
I have no idea.

Pixel 3, 3a, and 4a, lmi, and now OP9 are all not booting.
I suspect there is more than one issue at play.
I do not have any of these devices to test/debug with.
