### ISSUE TITLE
DivestOS recovery doesn't flash on Oneplus 5

### ISSUE THREAD

**Issue by helpthemfix** [Divested-Mobile/DivestOS-Build#129]
Hey  [SkewedZeppelin](https://github.com/SkewedZeppelin) I hope you're having a wonderful day 😃 

I downloaded the Cheeseburger recovery 19.1 and tried to flash it using the fastboot command `Fastboot flash recovery recovery.img`
Then it shows that it's done so successfully. However when I `Fastboot reboot recovery` nothing happens and it takes me back to the Bootloader.

So I had to flash TWRP the same way then flashed DivestOS 19.1 from there. I read a comment of yours about how bad TWRP is. so, is it ok if I flash the OS this way then when the OS updates the recovery updates with it? or does it have to be clean from he beginning without the use of TWRP? becuase I tried many times and the DivestOS recovery just doesn't boot. I was using Linux so I'm sure my phone was connected correctly.

**Comment by SkewedZeppelin** [comment]
I have two OnePlus 5's and both are working just fine with the recovery.
You may need to update your firmware first perhaps?

https://sourceforge.net/projects/lineageos-cheeseburger/files/firmware/cheeseburger/firmware_10.0.1_cheeseburger.zip/download

**Comment by helpthemfix** [comment]
> I have two OnePlus 5's and both are working just fine with the recovery. You may need to update your firmware first perhaps? https://sourceforge.net/projects/lineageos-cheeseburger/files/firmware/cheeseburger/firmware_10.0.1_cheeseburger.zip/download

Thanks for the swift reply! Do you by any chance have a guide for updating Firmware? As I've never done that before.

**Comment by SkewedZeppelin** [comment]
You can flash that zip through any (working) recovery, be it TWRP or Lineage
recovery.

DivestOS recovery will reject it due to signature mismatch.
