### ISSUE TITLE
OnePlus2: Signature spoofing?

### ISSUE THREAD

**Issue by Kreyren** [Divested-Mobile/DivestOS-Build#13]
Is there a way to set a signature spoofing support from the live system without the need to rebuild with `DOS_MICROG_INCLUDED` as defined in following?

https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Scripts/init.sh#L60

I wasnt able to do that using adb.

CC @SkewedZeppelin

**Comment by SkewedZeppelin** [comment]
Late response:
Signature spoofing can only be properly added at compile time.
