### ISSUE TITLE
How to help in order to stabilize alioth DivestOS 19.1?

### ISSUE THREAD

**Issue by AkechiShiro** [Divested-Mobile/DivestOS-Build#130]
Hi,

I have got an alioth Poco F3, and woild like to help stabilize the DivestOS 19.1 that is available on the official website, how can I help ? Should I try to help upstream LOS 19.1 ?

I'm a bit new to Android custom ROMs dev but I'm familiar with LOS wikipedia pages, how to and so on

**Comment by SkewedZeppelin** [comment]
Upstream builds work fine from what I know, so there is no issue upstream to fix.

The boot animation shows, but it will never boot. It could be the kernel, it could be deblobber related, it could also be related to the bionic hardening.

A user in the chat already tested using the boot.img from a LineageOS build, so that likely rules out kernel changes.

The second half of bionic hardening patches are actually disabled in previous branches, because of known boot issues on some devices however most of them were legacy not new like alioth is.

**Comment by AkechiShiro** [comment]
So what's left to rule out is either the deblobber or bionic hardening that could be a culprit preventing the boot process from finishing, what kind of tools can be used to investigate when booting an Android device that is bugging like this ? Only trial and error like disabling patches or removing parts of the deblobber and trying many times ?

**Comment by SkewedZeppelin** [comment]
You can make an engineering build which has insecure adb, but it may not help to debug if it is the bionic patches.

Easiest is to just disable the changes/patches and enable until it breaks.

**Comment by AkechiShiro** [comment]
Couldn't someone just disable them all and reactivate them one by one then flag the one that are causing the problem, but I guess this takes a lot of time.

I would do that but I only have one Alioth device and it's my daily driver I can't afford to break it on purpose at the moment.

**Comment by AkechiShiro** [comment]
Hey @SkewedZeppelin, I've seen that the status of Alioth has changed to `very likely working` does that means it works ? Or there still need some tests to be made ? 

I'm not too sure what that status means right now, but I'll close my issue, I think it is no longer relevant.

**Comment by SkewedZeppelin** [comment]
@AkechiShiro 
There have been multiple updater checks from alioth running 12, so I marked it so.

No one has yet to report it working so it doesn't have the `Reported Working` status just yet.

**Comment by AkechiShiro** [comment]
Updater checks you mean from users running DivestOS under Android 11 and that could have upgraded to Android 12 (DivestOS 19.1??)

**Comment by AkechiShiro** [comment]
I could give it a try in a few weeks or months (at worst) and report back on it to you here, about what works, what doesn't and so on...

**Comment by SkewedZeppelin** [comment]
> Updater checks 

There are multiple updater checks from alioth running 12.

**Comment by AkechiShiro** [comment]
I just don't understand what is an updater check ? Is it a user that has his phone request for DivestOS 19.1 update and that has done so ? 
Or are updater checks, some kind of automated testing that are now passing and previously were failing?

**Comment by SkewedZeppelin** [comment]
There are monthly updates. The OTA Updater app checks for updates weekly by default.
It sends along the current running version.
https://divestos.org/updater.php?base=LineageOS&device=alioth

If there are requests to that, it is good indication that the system boots and is largely functional.

**Comment by AkechiShiro** [comment]
Okay thanks for making that clear, yeah I just found it weird no one comes out and says it works alright (so the status can become tested working fully/alright)
