### ISSUE TITLE
HTC One M8 render issues

### ISSUE THREAD

**Issue by Ftonans** [Divested-Mobile/DivestOS-Build#133]
#### There is a serious bug that I have been experiencing for a long time, every time I rotate the screen or the program rotates the screen, this [bug](https://upload.disroot.org/r/XCbRywky#mVo/cGJegQeSDkD1XdR0B6ruholV8IbtO9nwm664Rb8=) happens.
For example, I can't watch videos in NewPiped or LibreTube. I can't use OpenCamera when I rotate a screen, I can't watch videos using graphene OS camera built-in gallery (this is strange because it doesn't change screen rotation).
If I make a screenshot, it looks absolutely normal and if I click where (for example) icon of a program would be, It would open a program. It is only a visual issue.
To fix it, you need to relock your phone.

Everything works fine on the latest Lineage OS ROM
Latest Divest Os ROM (divested-18.1-20220711-dos-m8)

**Comment by SkewedZeppelin** [comment]
I am aware of this.

**Comment by SkewedZeppelin** [comment]
I've fixed this: https://github.com/Divested-Mobile/DivestOS-Build/commit/6d52d2f6ce4c5384d71dc4d0ff75363b56065b86
