### ISSUE TITLE
Add support for Galaxy S10+ exynos (beyond2lte)

### ISSUE THREAD

**Issue by Pacify1** [Divested-Mobile/DivestOS-Build#136]
So LineageOS added support for the Samsung Galaxy S10+ exynos for quite some time now. Would like to eventually switch to a more secure ROM since official support for the S10+ will end with Android 12, but LineageOS doesn't let you relock the bootloader and has lots of security flaws that break Android's security model.

**Comment by Filbuntu** [comment]
Hopefully we can soon use the great DivestOS with the still excellent S10+. Thank you for any work on this!
