### ISSUE TITLE
Heavy Battary drain on OnePlus 5T DivestOs 19.1

### ISSUE THREAD

**Issue by helpthemfix** [Divested-Mobile/DivestOS-Build#137]
Hey @SkewedZeppelin. My friend reported to me about an abnormal battery drain by Android System and while Idle. On my Oneplus 5 the issue is not present.

![g](https://user-images.githubusercontent.com/92321993/180587945-cda5bda2-8364-4960-97f2-d243ae7a15c0.jpg)

**Comment by SkewedZeppelin** [comment]
I have two cheeseburgers and they both easily go 1-2 days between charges in active use.

You can use the Battery Historian tool to identify exactly the cause:
- compile from source: https://github.com/google/battery-historian
- unofficial third party: https://bathist.ef.lc/

**Comment by helpthemfix** [comment]
> I have two cheeseburgers and they both easily go 1-2 days between charges in active use.
> 
> You can use the Battery Historian tool to identify exactly the cause:
> 
>     * compile from source: https://github.com/google/battery-historian
> 
>     * unofficial third party: https://bathist.ef.lc/

His device is OnePlus 5T Dumpling. is there anything besides what you suggested to help identify the problem?

**Comment by SkewedZeppelin** [comment]
No, that tool is the most accurate way to identify battery drain.
