### ISSUE TITLE
DivestOs not working on (Xiaomi Redmi 4x)

### ISSUE THREAD

**Issue by azR-103** [Divested-Mobile/DivestOS-Build#142]
Hello,
Dos recovery Installation was successfully, but adb sideloading dos build failed.

![20220814_211603](https://user-images.githubusercontent.com/27334453/184546285-08e83344-ab9e-4592-b6f2-317a0fc85ffd.jpg)
![20220814_211725](https://user-images.githubusercontent.com/27334453/184546289-c7b1c36e-1581-41ed-ace3-dda19bb6fd5e.jpg)

**Comment by SkewedZeppelin** [comment]
can you perform format, reboot recovery, and sideload again?

**Comment by azR-103** [comment]
> can you perform format, reboot recovery, and sideload again?
> 
> alternatively you can flash Orangefox recovery for your device and flash with that.

Same error.

Okay flashed via twrp no errors and it did boot after 10mins tho.

What about incremental/delta ota updates does it support via twrp or orangefox?

**Comment by SkewedZeppelin** [comment]
That device doesn't get incrementals https://divestos.org/index.php?page=faq#incrementalSupport

**Comment by azR-103** [comment]
So, i have to dirty flash when new build is up?

**Comment by SkewedZeppelin** [comment]
You just tap install from the Updater app.

You should never have to wipe for an update.

**Comment by azR-103** [comment]
Had flashed dos via twrp, later updated to version 20220814 via updater which was successfull but dos recovery got automatically installed.

Now downloaded lastest update 20220828 via updater app & tap install it booted to dos recovery and got stucked it didn't update and i can't boot back to system.

Turning power off & on doesn't work.

**Comment by SkewedZeppelin** [comment]
TWRP should persist itself. Just flash TWRP again and install the update and it should boot fine.
After flashing the system via TWRP it should print a message at the end of the installing saying "renaming recovery.patch to prevent override".

the 08/28 update compared to 08/14 update was just a handful of security updates.

**Comment by azR-103** [comment]
Flashed twrp and updated. But again dos recovery got installed.

**Comment by azR-103** [comment]
![20221111_135338](https://user-images.githubusercontent.com/27334453/210046920-d3a4525f-4801-42c7-b195-e89dc5c118e3.jpg)

Orangefox recovery error while updating.

**Comment by SkewedZeppelin** [comment]
can you try another recovery? there have been very few changes to 16.0

**Comment by azR-103** [comment]
Tested both TWRP & OrangeFox recovery.

TWRP can flash dos build but can't survive after ota update. Have to flash twrp img after every update and i don't always have access to pc.

OrangeFox can't flash dos build i have to unzip and delete compatibility.zip to flash it and it fails to update via ota cause compatibility.zip can't be deleted manually in ota update. Though orangefox recovery is yet to be tested if it can survive after ota update. Can you remove compatibility.zip from 16.0 santoni builds in further updates.?

![20230115_162520](https://user-images.githubusercontent.com/27334453/212537184-f1e367b0-3f46-4026-bd65-c9cd885797e8.jpg)

![210046920-d3a4525f-4801-42c7-b195-e89dc5c118e3](https://user-images.githubusercontent.com/27334453/212537581-95884f61-8dc3-4867-bd74-57177422191a.jpg)

**Comment by SkewedZeppelin** [comment]
DivestOS 20.0 for Mi8937 is now available: https://divestos.org/pages/news#2023-04

**Comment by jnbht** [comment]
> DivestOS 20.0 for Mi8937 is now available: https://divestos.org/pages/news#2023-04

Where can I download this build? I do not find it [here](https://divestos.org/pages/devices)
