### ISSUE TITLE
GPS looks broken on OnePlus 6 (enchilada)

### ISSUE THREAD

**Issue by guillaumerocq** [Divested-Mobile/DivestOS-Build#143]
Hello there, I am currently running Oneplus 6 (`enchilada`) w/ DivestOS 19.1 (`19-20220807-dos-enchilada`) (made OTA).
GPS worked really well using `divested-19.1-20220613-dos-enchilada` build through OpenStreetMap and Waze.

Tried to manually flash last ROM version, uninstall Waze and Osm using latest app. version and cleaning data/cache but it seems ineffective.
- OSM is effectively using location (as seen in recent access log and visible in state bar) but print "Position unknown" if request is made.
- Waze does not seems to be in capacity to access location at all (no access log is visible in location service).

Also tried to force GNSS measure but without positive result.

Any idea would be welcome; thanks !

**Comment by SkewedZeppelin** [comment]
I know of no changes related to the location stack in recent months.
The 6T/fajita is my daily driver and I have zero issues with GPS. I'm indoors right now and it locked on in 174 seconds.
What do you see with the GPSTest app?

Per the [website](https://divestos.org/index.php?page=broken#papercuts):
> Most devices will take up to the full 12.5 minutes to acquire a GPS lock. Please test using GPSTest app with *clear* and *direct* line of sky. https://f-droid.org/en/packages/com.android.gpstest.osmdroid

If you see absolutely no satellites at all after 12.5 minutes please post output of following from this [command](https://divestos.org/index.php?page=bug_reporting#logs): adb logcat -b all -d *:E | grep -i -e locsvc -e izat -e gps -e gnss -e location -e xtra

> Tried to manually flash last ROM

Do you mean you tried to flash the June build after having updated to August? The DivestOS recovery would reject this as downgrades are not supported.

**Comment by guillaumerocq** [comment]
Hello @SkewedZeppelin thanks for your quick answer.

> What do you see with the GPSTest app?
> Per the [website](https://divestos.org/index.php?page=broken#papercuts):
   >Most devices will take up to the full 12.5 minutes to acquire a GPS lock. Please test using GPSTest app with clear and direct line of sky. https://f-droid.org/en/packages/com.android.gpstest.osmdroid

I made different test with a clear line of sky, it took me:
- `374 sec.`
- `18 sec.`
- `20 sec.`
to acquire lock (`TTFF`).
OSM and Waze are properly working this time.

> Do you mean you tried to flash the June build after having updated to August? The DivestOS recovery would reject this as downgrades are not supported.

I just tried to flash latest for `enchilada` manually on top of current ROM (which is latest itself).

I am closing this issue now.
Sorry for inconvenience.

**Comment by guillaumerocq** [comment]
GPS is properly working on `enchilada` using latest build.

**Comment by SkewedZeppelin** [comment]
Those times look [right](https://en.wikipedia.org/wiki/Time_to_first_fix#Scenarios), happy to hear.
