### ISSUE TITLE
GitHub Sponsor

### ISSUE THREAD

**Issue by martin-braun** [Divested-Mobile/DivestOS-Build#144]
Could you please setup sponsoring through GitHub directly? It gives a cool badge and allows users to show public appreciating to DivestOS on their profile page.

Thank you.

**Comment by SkewedZeppelin** [comment]
I already accept donations [via](https://divested.dev/index.php?page=donate) Stripe directly and through Liberapay.

I have no intent on providing Microsoft with my tax information.

**Comment by martin-braun** [comment]
Fair enough and absolutely reasonable.
