### ISSUE TITLE
Hammerhead - unable to remove apps

### ISSUE THREAD

**Issue by fw190d13** [Divested-Mobile/DivestOS-Build#146]
Hi!

As per my comment here:
https://forum.xda-developers.com/t/rom-divestos-15-1-16-0-for-hammerhead.4285903/#post-87389505

It is impossible to uninstall apps the regular way.

**Comment by SkewedZeppelin** [comment]
Kindly, you do not need to ping me twice.

> This is an old bug in the launcher, it happens at random sometimes. Just force stop Trebuchet.

**Comment by fw190d13** [comment]
Ups. Sorry @SkewedZeppelin I'm not that good at this whole Github/XDA netiquette. Should I post only here meaning on Github?

**Comment by SkewedZeppelin** [comment]
Either is fine, and I do appreciate reports. Just kindly don't report the same issue multiple times.
