### ISSUE TITLE
Can you add Xiaomi Mi A2 to the DivestOS family?

### ISSUE THREAD

**Issue by fw190d13** [Divested-Mobile/DivestOS-Build#147]
Hi!

Xiaomi Mi A2 still has some steam in the boiler and as proved here:
https://forum.xda-developers.com/t/13-t-official-arrow-os-xiaomi-mi-a2-jasmine_sprout.4485215/
it can run the latest Android.

If you could smack the DivestOS goodies on top of that I could test the device for you.

I hope that I'm not asking too much.

**Comment by SkewedZeppelin** [comment]
https://github.com/Divested-Mobile/DivestOS-Build/issues/68#issuecomment-1100724624
