### ISSUE TITLE
Unable to Enter Fastboot Mode to Install DivestOS on Razer Phone 2.

### ISSUE THREAD

**Issue by g1t3m** [Divested-Mobile/DivestOS-Build#148]
Hello

Update: I was able to work around the issue below by downloading the Samsung ADB Driver from this website: https://developer.samsung.com/android-usb-driver and selecting that driver for the Razer Phone 2 driver via the Device Manager installer wizard. I was able to perform step 5 of the install process. However, the device has rebooted and been on the DivestOS boot screen (the black screen with the DivestOS word logo) for nearly 10 minutes. Furthermore, adb commands no longer work with the device, only fastboot.

According to the steps, at this point something may be wrong with the device. I attempted to restart the device in bootloader mode by hitting the power+volume keys, but to no avail. Have I bricked my device or is something else going on? If this is normal, how long does the boot process take?

========================

Original: I recently purchased an OEM unlocked Razer Phone 2. I followed the installation steps for Fastboot up to step 4. When I attempt to execute the commands from step 5 onward, there is no confirmation of the commands reaching the device on the device screen. The device does not enter Fastboot mode. 

To ensure I had up-to-date drivers on my Windows 10 OS, I navigated to my Device Manager, reviewed the Android drivers and found that the driver was listed as a generic Android driver with a yellow caution triangle next to the driver icon. I attempted to update the driver, but to no avail as no compatible drivers were found. I am currently using one of three USB-C 3.0 cables to connect to my computer, all of which work up to the step mentioned above.

Based on this thread here: https://forum.xda-developers.com/t/need-help-to-relock-the-razer-phone-2-bootloader.3986999/, and the tip under step 4 here: https://wiki.lineageos.org/devices/aura/install, this is either an issue with the type of cable I'm using, or this is an issue with the Bootloader of the Razer Phone 2 itself preventing fastboot commands from reaching the device. Do you have potential workarounds for this install?

**Comment by SkewedZeppelin** [comment]
You're likely the first person to test aura, or at least report it.

It is very likely it doesn't work.
