### ISSUE TITLE
Poco X3 ( SURYA )

### ISSUE THREAD

**Issue by TeaqariaWTF** [Divested-Mobile/DivestOS-Build#15]
can you add support for poco x3

**Comment by SkewedZeppelin** [comment]
The other Poco's aren't booting, so... ¯\_(ツ)_/¯

**Comment by TeaqariaWTF** [comment]
I didn't quite understand what you said

**Comment by SkewedZeppelin** [comment]
There is no point for me to add it when the 3 other POCO phones I support are
broken because it is very likely surya will be broken too.
As I do not have any of those devices myself I cannot test and debug to
determine why they are broken.

**Comment by TeaqariaWTF** [comment]
i can test builds

**Comment by TeaqariaWTF** [comment]
Poco X3 (Surya )has official Lineage support. Can DivestOS developers provide support for Poco X3?

**Comment by TeaqariaWTF** [comment]
Poco X3 (Surya )has official Lineage support. Can DivestOS developers provide support for Poco X3?

**Comment by SkewedZeppelin** [comment]
Closing, will be tracked in #68
