### ISSUE TITLE
Can't create multiple users

### ISSUE THREAD

**Issue by gibroule** [Divested-Mobile/DivestOS-Build#150]
I'm using divest os 17.1 osprey and I think can't create multiple user because I didn't find any option to do so and when I tried to install the apps Shelter or Insular, I've got an error saying "Missing functionnality : android.software.managed_users"

**Comment by SkewedZeppelin** [comment]
osprey is marked as a lowram device and some features like that are disabled as such

**Comment by gibroule** [comment]
Oh okay, thank you for the clarifications
