### ISSUE TITLE
Poor Microphone quality in DivestOS 12 Oneplus 5

### ISSUE THREAD

**Issue by helpthemfix** [Divested-Mobile/DivestOS-Build#151]
The issue started with DivestOS 12 as it wasn't present in 11. The audio recorded in videos by the default camera sounds muzzled. The issue is present as well in other apps such as voice notes in Signal app.

**Comment by SkewedZeppelin** [comment]
As a workaround: Open Camera lets you select an alternate microphone in its settings.
