### ISSUE TITLE
OnePlus 6 DOS 20 Build 20221112 Networking not working

### ISSUE THREAD

**Issue by syboxez** [Divested-Mobile/DivestOS-Build#168]
After updating from the October build to the November build, networking no longer works. Bootloader is unlocked, but downgrade attempts result in the device booting to recovery saying the data partition is corrupted.

**Comment by SkewedZeppelin** [comment]
read the website: https://divestos.org/index.php?page=news
> 20.0 rebuilds were published on October 20th. Users already on the existing 20.0 builds will have Network and Sensors permissions disabled for all user apps.

**Comment by syboxez** [comment]
> read the website: https://divestos.org/index.php?page=news
> 
> > 20.0 rebuilds were published on October 20th. Users already on the existing 20.0 builds will have Network and Sensors permissions disabled for all user apps.
> 
> Downgrades are never supported.

Yeah, was looking for some kind or report, but couldn't find one. Thanks.
