### ISSUE TITLE
Mi 9T (Davinci) Build issue

### ISSUE THREAD

**Issue by NaytSeyd** [Divested-Mobile/DivestOS-Build#170]
I'm successfully booted LineageOS 20.0 without bug(s) but whenever i try DivestOS i'm having trouble with the patchWorkspace command. Can you help with this issue?
OS: Ubuntu 18.04
![20221116_001337](https://user-images.githubusercontent.com/43905928/202026564-3009d7e0-967d-4639-81d2-452cb2ab396b.jpg)

**Comment by SkewedZeppelin** [comment]
Are you using bash?

**Comment by NaytSeyd** [comment]
> Are you using bash?

Yes.

**Comment by SkewedZeppelin** [comment]
Are you sure it isn't dash?

**Comment by NaytSeyd** [comment]
> Are you sure it isn't dash?

Yes, i'm sure.

**Comment by NaytSeyd** [comment]
I had one more question. I don't quite understand the signing build. In docs `nano Generate_Signing_Keys.sh; #Update description` but what exactly should I do here?

**Comment by SkewedZeppelin** [comment]
Change the names on this line to whatever: https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Scripts/Generate_Signing_Keys.sh#L31

**Comment by NaytSeyd** [comment]
> Change the names on this line to whatever: https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Scripts/Generate_Signing_Keys.sh#L31

Thanks again, I'm on the job, if I'm successful, I'll let you know here.

**Comment by NaytSeyd** [comment]
Divest 20 Succesfully booted on davinci. Debian fixed all issue(s).
