### ISSUE TITLE
Pixel XL (marlin) - Nov. 11th Update Broke Cellular Network Connectivity

### ISSUE THREAD

**Issue by 7MXek** [Divested-Mobile/DivestOS-Build#171]
The Nov. 11th update of DivestOS has seemingly broken cellular network connectivity for calls and texts (on Verizon) on my Pixel XL (marlin). The previously installed Oct. 8th release functioned as expected.

I previously had a similar cellular issue with the Sep. 9th release where I couldn't receive calls, but I could place them. This was fixed when I updated to the Oct. 8th build.

I can provide any additional information as requested.

**Comment by SkewedZeppelin** [comment]
Can you first reset the APN list?

And if that doesn't work can you invoke the "reset network settings" from the reset menu in Settings.

I have two sailfish and tested cellular data/calls/SMS before this update on one, albeit not Verizon as the carrier.

**Comment by 7MXek** [comment]
Sorry, I should have included in my post that I tried both of these options earlier in the day when I was fighting with my device. I have treid

However, I did notice that I am able to contact to my data services

**Comment by 7MXek** [comment]
Future Readers,

I was able to reach SkewedZeppelin on the DivestOS Matrix server. It was determined that my issue is most likely due to the 3G CDMA network shut off. My call problems are likely because VoLTE isn't working and VoLTE probably isn't working on Verizon because DivestOS removes all the Verizon apps. However, I can use my data services.
