### ISSUE TITLE
Oneplus 6 , usb cable connection problem 

### ISSUE THREAD

**Issue by gitgerardo** [Divested-Mobile/DivestOS-Build#172]
In latest build 20221112 for oneplus 6 the connection to the Computer via cable is not anymore possible (in order to transfer files from or to the Computer.)
The build before it worked perfectly.

![Screenshot_20221126-174831_Trebuchet](https://user-images.githubusercontent.com/33866993/204099753-f814077d-39b9-42fb-8b49-85dceadb49d4.png)

**Comment by SkewedZeppelin** [comment]
Are you on 19.1 or 20.0?

20.0 is EXPERIMENTAL and this is a known issue: https://divestos.org/index.php?page=news#thirteen
> USB may not work if deny USB is enabled (Settings > Privacy > Trust) on some devices.

It is largely fixed but the fix won't be available until next update.

**Comment by gitgerardo** [comment]
So  I 'll wait for the next update (I am on 20.0) Thanx a lot!

**Comment by SkewedZeppelin** [comment]
New builds are uploading right now, refresh your Updater later today.

**Comment by gitgerardo** [comment]
> New builds are uploading right now, refresh your Updater later today.

Great!
Just dowmloading...

**Comment by gitgerardo** [comment]
> > New builds are uploading right now, refresh your Updater later today.
> 
> Great! Just dowmloading...

The bug is fixed with the today's update, great work, thank you!
