### ISSUE TITLE
Fairphone 4 crashes and reboots

### ISSUE THREAD

**Issue by fuck-shithub** [Divested-Mobile/DivestOS-Build#173]
I installed DivestOS 20.0 TD1A.221105.001 on my fp4 thinking it was all working and 100% stable according to the website divestos.org, only to have my phone crash and reboot 5 to 10 times every day. Especially when I play music on my big sexy bluetooth speaker my phone will crash way more often, disconnecting bluetooth and causing the speaker to make the Windows XP logoff sound. It's really loud when that happens and it scares my neightbours.

Please fix and thanks for any help

**Comment by SkewedZeppelin** [comment]
>  it was all working and 100% stable according to the website 

20.0 is marked EXPERIMENTAL
With many known issues, including this one documented on the website: https://divestos.org/index.php?page=news#thirteen

However can you confirm you are on the 20221125 update? Because that one did have an explicit fix for this issue.

**Comment by fuck-shithub** [comment]
I installed the update and it works. Thanks bro. Now I can listen to my big sexy bluetooth speaker without my neightbours knocking on my door at 3 AM.
