### ISSUE TITLE
20.0 frameworks/base patch 0026 broken since qpr

### ISSUE THREAD

**Issue by danielk43** [Divested-Mobile/DivestOS-Build#174]
Didn't see this one in the most recent commit, is it working? Breaks for me then skips the remaining applypatch cmds. regenerated here:
https://github.com/danielk43/DivestOS-Build/blob/main/Patches/LineageOS-20.0/android_frameworks_base/0026-Crash_Details.patch

Also my DOS-patched builds on pixels are no longer booting but neither are plain ones since the qpr updates were merged :/

**Comment by SkewedZeppelin** [comment]
I have not yet rebased the patches on QPR1 yet that Lineage recently merged.

**Comment by danielk43** [comment]
Ah, will be patient then.. for 20.0 that was the only one I saw.
I agree, will try to find out more... it may be just me but not sure yet

Thx

**Comment by SkewedZeppelin** [comment]
https://github.com/Divested-Mobile/DivestOS-Build/commit/b78f573eb9d07476c5d12d4b10e57a629c30a462
https://github.com/Divested-Mobile/DivestOS-Build/commit/29c9826c11d723a15cc45466555c29d06b3fea87

still compiling/testing, but taimen boots for me

**Comment by danielk43** [comment]
Nice, good to know. An unsigned userdebug build booted for me as well.
Adding things back in stages, trying to isolate the issue on my end.

The "plain" mentioned earlier still had AVB, signature spoofing, custom packages.
So not quite an accurate description

**Comment by danielk43** [comment]
Found my problem, made a mistake recreating deblob commits and newly took out something vital, coincidental with QPR1 timing.
Not at all related to LOS updates.

DOS patches are great and crosshatch is booting again with the latest fixes.
Thanks again.

**Comment by danielk43** [comment]
One note re: most recent commit. Not necessary:
https://review.lineageos.org/q/topic:bluetooth-cert
