### ISSUE TITLE
Screenshot is bugged in Android 13 OnePlus 5

### ISSUE THREAD

**Issue by ghost** [Divested-Mobile/DivestOS-Build#176]
When I take a screenshot the image doesn't save and the System UI crashes.

I have the latest update as of now.

**Comment by SkewedZeppelin** [comment]
DivestOS 20.0 is EXPERIMENTAL, however I cannot reproduce this issue.

Please provide a logcat: https://divestos.org/index.php?page=bug_reporting#logs
