### ISSUE TITLE
Advance Privacy Function (Feature Request)

### ISSUE THREAD

**Issue by essoojay** [Divested-Mobile/DivestOS-Build#178]
thanks for the effort,

Can advance Privacy function, such as Advance Privacy Tracker and Ad blocking on /e/Foundation OS and IODEOS  iode app, be implemented.??

Thanks

**Comment by SkewedZeppelin** [comment]
DivestOS already has a built-in content blocker, the ability to revoke network permission (from GrapheneOS), and data restrictions (from LineageOS).
