### ISSUE TITLE
Raspberry Pi Support?

### ISSUE THREAD

**Issue by mattdrepo** [Divested-Mobile/DivestOS-Build#18]
Hi there!

Firstly thank you so much for creating this great build for the devices you support to date. Really good work here!

Wondering though, whether you might support a more generic device such as a raspberry pi or even do your magic on an x86 build?  It would be great to have a compliment to your work on something that could replace the standard desktop?

I am sure I am not alone in thinking this would be a great idea - and perhaps create more adoption?

Either way, thanks again for your great work and interesting inclusions to Android.  I have enjoyed using the apps you included and gaining more life out of my old hardware - whilst feeling more secure!

:)

**Comment by SkewedZeppelin** [comment]
> It would be great to have a compliment to your work on something that could
replace the standard desktop?

https://github.com/divestedcg/brace

> might support a more generic device such as a raspberry pi

Things like x86 machines and SBCs can typically run mainline Linux and standard
distros. You might as well install Fedora or Debian on them.

DivestOS aims to provide support to devices that mostly aren't supported
anymore.

> I have enjoyed

Your welcome!

**Comment by mattdrepo** [comment]
Thank you for your prompt reply and input :)

Some further discussion - I quite like the android x86 projects with regard to keeping old chromebooks alive.  I bought a very old x86 chromebook (celeron based) and would like a x86 divestos based chromebook, perhaps I ought to of been more clear (but at the same time i think there's some use to not having mainline linux and using android apps instead - i would go BSD unix otherwise)

Thank you for your link to brace - this looks very useful, I'll consider it if I use those Linux flavours.

DivestOS aims to provide support to devices that mostly aren't supported anymore.  - Perhaps then the Chromebooks and x86 variants might meet that criteria.  I would love divestos-x86 for my c300.  I would probably use it instead of normal day to day stuff on my Mac and keep that for music production and art (like it was intended) and I am sure there would be a following since galliumos is pretty much floating right now.

Just Ideas for you.  If you could provide x86 variants of your software apks perhaps a gradual effort to "divest" an android x86 port could be discussed.  Maybe you could point interested users like me as to how to do some of your work on x86?  Just thoughts if the work is too much?

Thanks again for your time!

**Comment by SkewedZeppelin** [comment]
Your c300 is quawks, I have a very similar glimmer I use daily with my Divested-
Coreboot builds and Fedora.

You can get started here if you haven't corebooted it already:
https://mrchromebox.tech

Android on regular x86 machines is a huge hack with many pitfalls that I do not
have resources to maintain.

**Comment by mattdrepo** [comment]
Yes I have just tried android x86 and sadly it was quickly obvious it wasn't much use other than for a VM.  I will try Fedora desktop as gallium needed replacing and it seems your work will be useful to drag this old machine into some more use.  Thanks for the insights!
