### ISSUE TITLE
(Critical) Galaxy S3 Recovery and Browser problem

### ISSUE THREAD

**Issue by Mikrizi** [Divested-Mobile/DivestOS-Build#180]
Galaxy S3 i9300, Last divestOS 6.01.2023 (clean install)

Divest recovery not install OS, sideload or from sdcard - failed to map file (error)
If install last TeamWin TWRP, 3.7.0, os install without problem, but all browser app crashed - mull, FOSS browser, privacy browser, and all other crashed on start.

! If after install OS, swap TWRP to Divest Recavery, browser issue not solved
! If after install wipe cash, dalvik, data, browser issue not solved

**Comment by SkewedZeppelin** [comment]
This is documented on the website: https://divestos.org/index.php?page=broken#s3-common

It is why it is labeled "mostly working" on the downloads page.

**Comment by Mikrizi** [comment]
> This is documented on the website: https://divestos.org/index.php?page=broken#s3-common
> 
> It is why it is labeled "mostly working" on the downloads page.
> 
> See the existing discussion: #50
> 
> From what I understand I did at least fix the issue for i9305, likely because it has more RAM.

Thank you very much for your reply, my fault for not looking at the error page.

I really like Divest, it's a pity that this problem, I will look for another device, thanks!
