### ISSUE TITLE
Fairphone 4: Fingerprint reader only intermittently available

### ISSUE THREAD

**Issue by bryanparadis** [Divested-Mobile/DivestOS-Build#185]
Fairphone 4
20-20230109-dos-FP4

The fingerprint reader seems to only be intermittently available. There is no sign of life and no reaction from the device. If there is a read there is a vibration regardless of match. Seems like once the phone has been off a while the fingerprint reader no longer works until you unlock the phone via pin/pattern.

I will try to reproduce the issue with adb logging run later today. Let me know if you have any particular logging requests.

**Comment by SkewedZeppelin** [comment]
While there may be a bug here, it should also be noted that DivestOS will disable the fingerprint reader and mandate strong auth (password/pin) at least once every 12 hours.

**Comment by bryanparadis** [comment]
> While there may be a bug here, it should also be noted that DivestOS will disable the fingerprint reader and mandate strong auth (password/pin) at least once every 12 hours.

Good to know. This is more like within the span of 15 minutes I may have several issues.  I think I was getting finger print reads during screen on as well before. Part of the problem maybe also be it quickly reading 5 times and then requiring a pin/pattern unlock before fingerprint is available again?

> 
> > 20230109
> 
> please update your device

Updated. Not sure yet.

**Comment by SkewedZeppelin** [comment]
When it does work can you unlock from screen off, just by tapping it?

I wonder if it may be falsely triggering? DivestOS will also disable the reader after _three_ failed attempts.

**Comment by bryanparadis** [comment]
> When it does work can you unlock from screen off, just by tapping it?

Yes.

> I wonder if it may be falsely triggering? DivestOS will also disable the reader after three failed attempts. Android default is 20?

Yeah interesting. I couldn't find a setting for changing this I am guessing it's not exposed anywhere? Props maybe? I wouldn't mind a bit more leeway if it meant it was useable more often than not.

I guess it may be going off in my pocket. I am paying real close attention to the behavior and with the additional information you gave me we will see if I can come to a conclusion.

**Comment by SkewedZeppelin** [comment]
There is no way to change that setting without recompiling as it stands.

**Comment by bryanparadis** [comment]
> There is no way to change that setting without recompiling as it stands.

Ok. Thanks. I will observe it for a while but I am thinking that the sensor is liking just firing a lot during handling and locking it out.
