### ISSUE TITLE
Surnia Recovery Non-functional

### ISSUE THREAD

**Issue by yeswap** [Divested-Mobile/DivestOS-Build#187]
Divested Recovery recovery (divested-17.1-20230121-dos-surnia-recovery.img) flashes successfully but booting into recovery from the fastboot menu or from adb boots to Android System, not to Recovery. 

LineageOS recovery works as expected. 

Using LineageOS recovery with adb sideload works to install  divested-17.1-20230121-dos-surnia.zip.  

Unfortunately, installing DivestOS overwrites the working LineageOS recovery with the not working DivestOS recovery.

fastboot flash recovery divested-17.1-20230121-dos-surnia-recovery.img 
(bootloader) has-slot:recovery: not found
(bootloader) is-logical:recovery: not found
Sending 'recovery' (13298 KB)                      OKAY [  0.439s]
Writing 'recovery'                                 OKAY [  0.797s]

**Comment by SkewedZeppelin** [comment]
Known issue: https://github.com/Divested-Mobile/DivestOS-Build/issues/135#issuecomment-1188080741

If you use TWRP it has a function that automatically prevents it from being replaced, as long as you install the system via it again (no need to wipe)
