### ISSUE TITLE
external/hardened_malloc revision in LOS 20 manifest

### ISSUE THREAD

**Issue by danielk43** [Divested-Mobile/DivestOS-Build#189]
Curious, why the preference to pin to an older commit [here](https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Manifests/Manifest_LAOS-20.0.xml#L49) instead of adapting the patches to include recent updates?

**Comment by SkewedZeppelin** [comment]
only because I haven't rebased the patches, and the recent change don't have any direct effect from what I skimmed

it is on my TODO list to be done someetime

**Comment by danielk43** [comment]
Got it... [mine](https://github.com/danielk43/DivestOS-Build/tree/main/Patches/LineageOS-20.0/android_external_hardened_malloc) have been booting all week, I just rebased today to restore original commit credit/metadata.
Thanks
