### ISSUE TITLE
OP 6 Reboot while Plugging in or off

### ISSUE THREAD

**Issue by gitgerardo** [Divested-Mobile/DivestOS-Build#194]
My Oneplus 6 reboots every time when pluged in or off to power source. I can't find the reason.
Using latest divestOS build for my device.

**Comment by SkewedZeppelin** [comment]
Are you sure it isn't shorting out?

Have you cleaned any dirt out of the connector? Tried a different cable and charger?

I don't have any issues like this on my OP6T

**Comment by gitgerardo** [comment]
Ok, now I changed to my second oneplus 6 and tried another cable . Same . It seems be a software issue.

**Comment by SkewedZeppelin** [comment]
did you ever figure this out?

**Comment by gitgerardo** [comment]
It's really funny that you ask this today because just today I did a fresh install (oxygen **and** latest divestedos) and now it works without that problem.
 Actually the problem I had before was an only reboot of the UI not a full reboot.
My other device with an normal update to the same build has still the same issue rebooting the UI while plugging or unplugging.

**Comment by SkewedZeppelin** [comment]
strange, there is actually one firmware partition that divestos doesn't ship on oneplus 6, I wonder if that somehow impacts charging: https://github.com/Divested-Mobile/firmware-empty/blob/master/enchilada/Android.mk#L24

**Comment by gitgerardo** [comment]
OK, interesting!

**Comment by gitgerardo** [comment]
Now I found out that an app was responsible for the problem!
It was "SystemUI Tuner" in f-droid.
Only installing the App and giving all permissions without changing any of the configurations (!) it caused the Problem.

So I am sorry for opening this issue!
