### ISSUE TITLE
VoWiFi (WiFi calling) whitelist

### ISSUE THREAD

**Issue by EmanuelLoos** [Divested-Mobile/DivestOS-Build#195]
WiFi calling is currently disabled in DivestOS. However, correct me if i'm wrong, but I don't think WiFi calling over my own private WiFi network comes with secority risks. Therefore, I think, it would be great to let the users add access points to a list of trusted WiFi networks after they were informed regarding the possible threats, instead of WiFi calling just being no option so that users can make their own informed choices.

**Comment by SkewedZeppelin** [comment]
nope

**Comment by EmanuelLoos** [comment]
Which freedom risks does it convey?

**Comment by SkewedZeppelin** [comment]
The dozens of proprietary blobs necessary for it to function: https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Scripts/Common/Deblob.sh#L110-L126

**Comment by SkewedZeppelin** [comment]
>  And why would there be more risks then the non-removed normal phone-call functionality has?

VoLTE is routed over cellular, but VoWiFi not which let's your carrier have fine grained tracking of which networks/IP addresses you use and can directly associate that with your identity via SIM.

**Comment by EmanuelLoos** [comment]
Why are there so many additional proprietary bllobs neccessary?
