### ISSUE TITLE
flashing nexus 5x rom zip gives error

### ISSUE THREAD

**Issue by baroni309** [Divested-Mobile/DivestOS-Build#2]
When flashing the rom 'clean flash' through twrp and even with adb sideload it shows ''updater process ended with ERROR: 6''

**Comment by SkewedZeppelin** [comment]
Can you try flashing the zip using the DivestOS recovery?

**Comment by SkewedZeppelin** [comment]
Don't bother.
I think I know what is wrong, I'll upload a new build shortly.

**Comment by SkewedZeppelin** [comment]
New build is up.
divested-15.1-20201226-dos-bullhead.zip
It removes some update-script calls to functions only available in the stock
update-binary.
It should hopefully work.

**Comment by baroni309** [comment]
I can comfirm that it's working now, thank you !
