### ISSUE TITLE
Cannot import vcard with VERSION:4.0

### ISSUE THREAD

**Issue by Thalley** [Divested-Mobile/DivestOS-Build#202]
When attempting to import my contacts to my DivestOS (build 20.0) I was met with an error message that it could not import the .vcf (vCard) file. 

I played around with the vCards in the file, and found that simply modifying the version from `VERSION:4.0` to `VERSION:3.0` made it work, so the (default) Contacts application may not (properly) support `VERSION:4.0`. 

See the following examples:

This works
```
BEGIN:VCARD
VERSION:2.1
N:;Test Name;;;
FN:Test Name
END:VCARD
```

And this works

```
BEGIN:VCARD
VERSION:3.0
N:;Test Name;;;
FN:Test Name
END:VCARD
```

but this doesn't work
```
BEGIN:VCARD
VERSION:4.0
N:;Test Name;;;
FN:Test Name
END:VCARD
```

**Comment by SkewedZeppelin** [comment]
The underlying AOSP Contacts app largely hasn't been updated since 2014 or so making issues like this expected.

**Comment by SkewedZeppelin** [comment]
Nah, they're deprecated in favor of their proprietary replacements, eg: https://play.google.com/store/apps/details?id=com.google.android.contacts

**Comment by Thalley** [comment]
> Nah, they're deprecated in favor of their proprietary replacements, eg: https://play.google.com/store/apps/details?id=com.google.android.contacts
> 
> and merely considered "reference implementations" these days.

I see. Would the best option be to update it for DivestOS, or to update the implement in the AOSP? 

On a related note, I don't know which labels exists for this repo, but I probably wouldn't call this a bug, but rather an enhancement (unless it is supposed to support version 4.0 already).

**Comment by SkewedZeppelin** [comment]
I'll look to pulling this in next update: https://github.com/GrapheneOS/platform_packages_apps_Contacts/commit/8fbeedd0023c8c007459b528b40204da31f7bfc9
