### ISSUE TITLE
Can't set up the work profile on DOS 18.1

### ISSUE THREAD

**Issue by ghost** [Divested-Mobile/DivestOS-Build#217]
I'm unable to set up the work profile on DOS 18.1 (not sure if device specific, but it's serranoltexx, the latest build). I've tried Shelter, and it results in "Setup failed". Also, one thing I've noticed, is that Shelter is listed in F-Droid as incompatible with the installed OS, due to "Requires: android.software.managed_users".

That's weird, because I remember that like a year ago, I was able to set up the work profile on DOS 18.1 (older builds, but the same device, and also through Shelter). It's also unfortunate, as I needed that particular feature quite recently, and had to downgrade to LineageOS 18.1, just because of it (user profiles are an overkill for my needs).

Any clues? Do the 18.1 builds really not include the "android.software.managed_users" feature anymore?

**Comment by SkewedZeppelin** [comment]
WHAT DEVICE?

**Comment by SkewedZeppelin** [comment]
An easy solution is to actually just boot twrp, mount system, adb pull /system/etc/build.prop, remove the lowram line, and push it back
