### ISSUE TITLE
More than 3 users?

### ISSUE THREAD

**Issue by martin-braun** [Divested-Mobile/DivestOS-Build#219]
Using multiple user profiles is a privacy feature that should not be underestimated.

I've read somewhere than changing `fw.max_users` to a higher number in the `build.prop` can solve this issue.

For some reason, I can only create two additional users, but I need 5 users in total to cover my needs.

OnePlus 5

**Comment by SkewedZeppelin** [comment]
It is already set to 16: https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Patches/Common/android_vendor_divested/overlay/common/frameworks/base/core/res/res/values/config.xml#L74

**Comment by martin-braun** [comment]
@SkewedZeppelin Yep that's weird: 

![2023-07-06 18 06 57](https://github.com/Divested-Mobile/DivestOS-Build/assets/24259245/9b312572-a5cb-48bb-95cf-5bf87464bbae)
