### ISSUE TITLE
Unable to patch Lineage 20.0 android_packages_apps_Updater

### ISSUE THREAD

**Issue by hafeoz** [Divested-Mobile/DivestOS-Build#222]
[LineageOS/android_packages_apps_Updater](https://github.com/LineageOS/android_packages_apps_Updater) has [recently redo its repo structure](https://github.com/LineageOS/android_packages_apps_Updater/commit/755560bbcddb9ef52f1368185d52e019d1cba37a), causing patches to fail:
```
[ENTERING] packages/apps/Updater
HEAD is now at 185b5de Updater: Don't show delete twice
ERROR: Cannot apply: /home/unprivileged/DivestOS//Patches/LineageOS-20.0//android_packages_apps_Updater/0001-Server.patch
ERROR: Cannot apply: /home/unprivileged/DivestOS//Patches/LineageOS-20.0//android_packages_apps_Updater/0002-Tor_Support.patch
sed: can't read src/org/lineageos/updater/misc/Utils.java: No such file or directory
```

**Comment by SkewedZeppelin** [comment]
yes, I'll fix them before next build

**Comment by steadfasterX** [comment]
another good example which would have been catched by: https://github.com/Divested-Mobile/DivestOS-Build/pull/206 

![image](https://github.com/Divested-Mobile/DivestOS-Build/assets/8750713/00700fc4-fea2-4dce-8c51-3ab77882f587)

just saying as I stumbled over the same issue here ;)
