### ISSUE TITLE
17.1 July Patches

### ISSUE THREAD

**Issue by robin0800** [Divested-Mobile/DivestOS-Build#227]
Neither of the two patch packages are available in the build but they do exist on your site. Is this an omission or do they run one month behind?

**Comment by SkewedZeppelin** [comment]
Can you be more specific? What "patch packages"?

**Comment by robin0800** [comment]
On the below the patch numbers are shown but can not find them in patches and building a ROM shows security patch of 05/06/2023 This is true for all july patches.
The difference  is up till June The patches and the security change was on Gitlab, but there is not one for july so I guess you have to generate the patches and alter the security code yourselves'

https://gitlab.com/divested-mobile/divestos-build/-/commit/b92655dac4c51e54970ed1c822db2a94b8e2401b

**Comment by SkewedZeppelin** [comment]
All patches are public and included in the released builds.
I don't know what you're saying isn't included.
Google stopped supporting Android 10 back in Feburary, I've been backporting the ASB patches myself with help from others.

**Comment by SkewedZeppelin** [comment]
Ah I think I see what you're saying.

The July patches are in this repo but you need the prerequisite patches: https://github.com/Divested-Mobile/DivestOS-Build/blob/master/Scripts/LineageOS-17.1/Functions.sh#L80-L85

They aren't included in this repo as they are upstreamed to Lineage.

**Comment by robin0800** [comment]
Thanks for fixing by the way the security string is in sed -i 's/2023-06-05/2023-07-05/' **build/**core/version_defaults.mk; #Bump Security String #Q_asb_2023-07
