### ISSUE TITLE
Building a wileyfox swift crackling rom

### ISSUE THREAD

**Issue by robin0800** [Divested-Mobile/DivestOS-Build#230]
Firstly had to remove patch 360973 as it would not build /out/soong/ host/linux-x86/frameworks/apksig.jar
patches 360952, 3609563, 360957 & 360961 had to be removed in order to build
/out/soong/.intermediates/frameworks/base/framework/android_common/javac/Framework.jar1 & framework.jar25 
Is it possible I am missing something? All patches go in without errors but build stops with the named patches included.

**Comment by SkewedZeppelin** [comment]
No patches need to be removed, please run resetWorkspace then patchWorkspace and post the output.
Also post the actual output of the errors you get.

**Comment by robin0800** [comment]
Its OK now thank you very much
