### ISSUE TITLE
KernelSU

### ISSUE THREAD

**Issue by alaskasquirrel** [Divested-Mobile/DivestOS-Build#231]
I see [KernelSU for oneplus 7 pro on Lineageos 20](https://forum.xda-developers.com/t/q-kernel-su-for-oneplus-7-pro.4542059/) XDA Forums
> KernelSU officially supports Android GKI 2.0 devices(with kernel 5.10+), old kernels(4.14+) is also compatible, but you need to build kernel yourself.

What do you think of this approach？

**Comment by SkewedZeppelin** [comment]
DivestOS does not support root: https://divestos.org/pages/faq#rootSupport
