### ISSUE TITLE
pixel 4a 5G call issue / bootloader relocking ok so far

### ISSUE THREAD

**Issue by llbstr** [Divested-Mobile/DivestOS-Build#235]
Had calls issues, randomly not hearing the person during a call, switched the preferred network type to 4g and that solved the problem for now. About "preferred network type", if I select 4g or 4g only, it displays "4g only" in both cases. Don't know if that's matter but I have a carrier plan with no 5g (never had issues with other roms though). 

Last thing relocking bootloader on this device goes fine for a month now.

**Comment by SkewedZeppelin** [comment]
> I select 4g or 4g only, it displays "4g only" in both cases. 

This is a graphical issue in the text, the chosen option still takes proper effect.

It is possible your device was falling back to 3g instead of using VoLTE for some reason which caused the call issues.

**Comment by llbstr** [comment]
> It is possible your device was falling back to 3g instead of using VoLTE for some reason which caused the call issues.

Could be but it was happening a lot since using divestos, I think I need a week or so so I made enough calls to be sure it's solved due to preferred network setting or maybe it's a non issue.

**Comment by SkewedZeppelin** [comment]
how have calls been?

**Comment by llbstr** [comment]
So far switching from different options gave the same positive results, no particular issue. Maybe some circumstances misled me. Thanks you anyway, closing issue.
