### ISSUE TITLE
Problem installing on Pixel 6a

### ISSUE THREAD

**Issue by beatstick** [Divested-Mobile/DivestOS-Build#240]
I followed this guide so far: https://divestos.org/builds/LineageOS/bluejay/install.html

I get the following error upon trying to install fastboot (this is on pop_os latest):

 fastboot update /media/twoflower/Leechme/phones/pixel_6a/divested-20.0-20230824-dos-bluejay-fastboot.zip
--------------------------------------------
Bootloader Version...: bluejay-1.2-9894665
Baseband Version.....: g5123b-116954-230511-B-10112789
Serial Number........: 
--------------------------------------------
extracting android-info.txt (0 MB) to RAM...
Checking 'product'                                 OKAY [  0.000s]
Setting current slot to 'a'                        OKAY [  0.102s]
extracting boot.img (64 MB) to disk... took 0.349s
archive does not contain 'boot.sig'
Sending 'boot_a' (65536 KB)                        OKAY [  1.940s]
Writing 'boot_a'                                   OKAY [  0.136s]
extracting dtbo.img (16 MB) to disk... took 0.054s
archive does not contain 'dtbo.sig'
Sending 'dtbo_a' (16384 KB)                        OKAY [  0.485s]
Writing 'dtbo_a'                                   OKAY [  0.032s]
archive does not contain 'dt.img'
archive does not contain 'recovery.img'
extracting vbmeta.img (0 MB) to disk... took 0.000s
archive does not contain 'vbmeta.sig'
Sending 'vbmeta_a' (8 KB)                          OKAY [  0.000s]
Writing 'vbmeta_a'                                 OKAY [  0.002s]
archive does not contain 'vbmeta_system.img'
extracting super_empty.img (0 MB) to disk... took 0.000s
Rebooting into fastboot                            OKAY [  0.000s]
< waiting for any device >
fastboot: error: Failed to boot into userspace fastboot; one or more components might be unbootable.

Any advice?

**Comment by SkewedZeppelin** [comment]
Bluejay is my daily driver, it works well.

What happens on the device side after the last step?
Maybe try another cable or a USB 2.0 port.
Can you try manually booting into the recovery afterwards? DivestOS recovery is _orange_.

**Comment by beatstick** [comment]
I am using fastboot from platform-tools_r33.0.3-linux.zip according to the divestos installation guide. 

The device reboots and hangs on a google screen,  it seems to try to boot the OS.
If I then hold volume down, the above mentioned fastboot error occurs. 

I tried different cables, both original pixel ones, and different usb slots, so that does not seem problematic. 

If I try rebooting to recovery, I am only getting the bootloop with the google screen again.

**Comment by SkewedZeppelin** [comment]
eh, can you try running fastboot as root?

**Comment by beatstick** [comment]
I tried that already. It does not change anything, unfortunately. 

I just installed calyxos, which worked, but I would prefer to try out divestos. I think it's better for degoogling and also comes with the adblocking hostfile.

**Comment by SkewedZeppelin** [comment]
After installing the latest CalyxOS can you try installing DivestOS again? It is possible the firmware you had is old.

I just confirmed someone in chat installed bluejay the other day without issue, and I just confirmed rebooting to recovery works on my unit as well.

**Comment by beatstick** [comment]
I will try to install it again on top of calyxos. Should I flash all images from the fastboot zip archive?

**Comment by SkewedZeppelin** [comment]
Try first the `fastboot update ...` if it doesn't work, then unzip and try flashing each then rebooting.
