### ISSUE TITLE
Can the charge control feature from CalyxOS be merged?

### ISSUE THREAD

**Issue by EmanuelLoos** [Divested-Mobile/DivestOS-Build#241]
Hi, CalyxOS now has a charging control feature.
[It seems to come from LineageOS.](https://review.lineageos.org/q/topic:%22charging-control-hal-20%22)

It would be great if this could be merged/activated here as well. (If this is not already the case, not all devices seem to be supported so I would not know.)

**Comment by SkewedZeppelin** [comment]
No, I purposely disable this because I consider it broken.

**Comment by EmanuelLoos** [comment]
Why would it be broken? It seems to work for me on the FP4 with CalyxOS.

**Comment by SkewedZeppelin** [comment]
These charge control features can get into a state where the charge controller no longer allows the device to charge, even when in a critically low state.

It is a known issue on many devices, eg.: https://github.com/VR-25/acc#warnings

I'm not going to ship a feature that can destroy a user's device.

**Comment by EmanuelLoos** [comment]
How about only enabling it for devices, where the charge controller is known to work without such issues, then?

An automatic shutdown when the battery reaches a certain percentage would also help prevent this issue where there are faulty PMICs.

**Comment by SkewedZeppelin** [comment]
> On some lineage builds it has the setting to actually limit the charge %

It isn't missing in Calyx, it depends on whether the controller supports it, and not all Pixels do.
