### ISSUE TITLE
Signature faking for microG doesn't work

### ISSUE THREAD

**Issue by 0xC4aE1e5** [Divested-Mobile/DivestOS-Build#242]
The microG self-check says that signature faking isn't working, and Discord sends a bunch of notifications, which doesn't happen on LineageOS microG.

**Comment by SkewedZeppelin** [comment]
Yes it does. You must install the **latest** version of microG:
- https://microg.org/fdroid/repo/com.google.android.gms-231657056.apk
- https://microg.org/fdroid/repo/com.google.android.gsf-8.apk
- https://microg.org/fdroid/repo/com.android.vending-30.apk
This is documented on the website.

**Comment by 0xC4aE1e5** [comment]
Well last time, (when I triggered the bug), I just used the F-Droid app and enabled the repo and installed the apps. Maybe they have to be done in order (similar to Fire tablets)?

**Comment by SkewedZeppelin** [comment]
Order does not matter.
F-Droid will NOT install the latest version, as they are marked beta.
You must manually scroll down to the versions in F-Droid to install the latest one.

**Comment by 0xC4aE1e5** [comment]
Yup, it works now. I just scrolled down, tapped Versions, and picked the highest version for all 3 packages.
