### ISSUE TITLE
packages/inputmethods/LatinIME patches failing

### ISSUE THREAD

**Issue by danielk43** [Divested-Mobile/DivestOS-Build#244]
Looks like there was a keyboard update recently and java/src/com/android/inputmethod/latin/settings/SettingsValues.java has changed. 

[Here](https://github.com/danielk43/DivestOS-Build/commit/ee69315d52f88fa1f1acf86253ed03bff50f91e8) are rebased versions of the previous patches which apply without errors.

**Comment by SkewedZeppelin** [comment]
thanks, will pull in later
