### ISSUE TITLE
"Phone" app crashes when getting called on a different user profile

### ISSUE THREAD

**Issue by martin-braun** [Divested-Mobile/DivestOS-Build#247]
For the first time I'm testing DivestOS using a SIM card and multiple user profiles. I noticed that my "Phone" app crashes when I receive a call on another user profile, but on the host (main) user profile this doesn't happen.

I also noticed that I would receive notifications about incoming SMS on my host profile, but I would not on any other user profile. I still can receive SMS on my other profiles though. The problem might be related.

**Comment by SkewedZeppelin** [comment]
> crashes when I receive a call on another user profile

- Is "Turn on phone calls & SMS" enabled?
- The phone app also received a big overhaul by Lineage team, it is possible multi-user support regressed.

>  but I would not on any other user profile. I still can receive SMS on my other profiles though

This is a long-standing issue: https://github.com/Divested-Mobile/DivestOS-Build/issues/141

> multiple user profiles

May I ask why you're using multiple profiles instead of main user + work profile via Shelter? it is more convenient and offers largely the same benefits.

**Comment by SkewedZeppelin** [comment]
This should fix it next update: https://review.lineageos.org/c/LineageOS/android_packages_apps_Dialer/+/366907

**Comment by martin-braun** [comment]
@SkewedZeppelin First of all thank you for the quick response. Outstanding indeed.

> Is "Turn on phone calls & SMS" enabled?

You mean for my other profiles? Yes, I enabled SMS and phone calls, after all I receive SMS, just not notifications. Thanks for linking that issue.

> May I ask why you're using multiple profiles instead of main user + work profile via Shelter? it is more convenient and offers largely the same benefits.

Actually I do use Shelter for apps from the Aurora Store that I frequently need like some apps for home automation or Spotify. However, for more critical apps I want them to reside in separate spaces, i.e. any big corp apps that I barely need. I also isolate my "fun" environment to have more focus on my main profile.

> Indeed it did regress, this should fix it next update

Thanks for finding the issue and that it will be fixed on the next update. I will close this issue then. One last question though: When will you fork from the newer version, as soon as it gets ready?

Thanks for everything and best regards!

**Comment by SkewedZeppelin** [comment]
> When will you fork from the newer version

DivestOS builds are not forked from LineageOS, but the changes are applied directly on top of the latest code as of that build cycle's compile date.

Next planed update is the October ASB update somewhere around October 9th.

**Comment by martin-braun** [comment]
I intentionally got the OnePlus 5, because it has full support with DivestOS incl. bootloader locking. But, no pressure here. If someone calls me from another profile, I will just move to the main profile and call back if I can't receive it properly. I'm on my main profile 95% of the time. :)

**Comment by SkewedZeppelin** [comment]
This should be fixed: https://divestos.org/pages/news#2023-10
