### ISSUE TITLE
20: packages/apps/LineageParts patch rebase

### ISSUE THREAD

**Issue by danielk43** [Divested-Mobile/DivestOS-Build#255]
Fixed on 20:
https://github.com/danielk43/DivestOS-Build/commit/acd203c6834401a53c8bc9abda7cbbe487e823d8

not sure about other LOS versions

**Comment by SkewedZeppelin** [comment]
Thanks, will pull in soon

**Comment by SkewedZeppelin** [comment]
Merged, thanks!
