### ISSUE TITLE
Moto X Style (Clark) / 17.1 / October 9th 2023 Update bricked my device?

### ISSUE THREAD

**Issue by AgentSteel** [Divested-Mobile/DivestOS-Build#258]
Just updated to October 9th 2023 Update, then when my device first rebooted after the update, it displayed the early (boot) schema security screen, I swiped my security schema, then nothing happens, screen stays black. No more Android loading!

Battery was 85% before flashing.

Now I'm unable to restart my device! It won't power on! (Not detected with fastboot or adb)

What can I do next? Thanks for any help!

**Comment by SkewedZeppelin** [comment]
it doesn't power on at all?

If you're using Windows, does it show up in device manger?
If you're on Linux, do you see it when running: sudo dmesg -w

**Comment by AgentSteel** [comment]
Ok all is no lost, after a while I just booted in recovery mode (volume down + poweron)!

**Comment by AgentSteel** [comment]
Ok it's back to full life, don't know what happened... Let's close this issue! :smile:
