### ISSUE TITLE
Security Feature Suggestion: Add "Network Permission" like on GrapheneOS.

### ISSUE THREAD

**Issue by MarkCyberSecDev93** [Divested-Mobile/DivestOS-Build#26]
**This was a security feature (recommended by GrapheneOS) because:**
**https://madaidans-insecurities.github.io/android.html#firewalls**

Wish you guys/gals devs could implement this feature! Best of luck!

Edit: The First custom ROM aside from GrapheneOS implemented this feature is Havoc OS.

**Comment by MarkCyberSecDev93** [comment]
I know this is a problem for some apps (app crashing) but it can be solved by reinstalling the app and never disable/deny the "Network PERMISSION".

**Comment by MarkCyberSecDev93** [comment]
Note: I also added this topic in the discussion tab.

**Comment by SkewedZeppelin** [comment]
https://github.com/Divested-Mobile/DivestOS-Build/commit/5e1521700f42a78e10192ece32a5cfc21e8bf58c
