### ISSUE TITLE
Remove applications that depend on Google Service

### ISSUE THREAD

**Issue by topminipie** [Divested-Mobile/DivestOS-Build#261]
"com.android.systemui.plugin.globalactions.wallet" - This is the Google Pay widget in the power menu(hold power button for 1sec to show this menu), below the Emergency, Power off and Reboot buttons. 
https://github.com/0x192/universal-android-debloater/blob/main/resources/assets/uad_lists.json#L7322C55

There is no Google Play Services in the system + even if you install it, it’s unlikely that Google Pay will work (SefetyNet/Google Play Integrity is broken)

**Comment by SkewedZeppelin** [comment]
Removing harmless remnants like this add unnecessarily complexity/maintenance.
