### ISSUE TITLE
Bring back HDR

### ISSUE THREAD

**Issue by topminipie** [Divested-Mobile/DivestOS-Build#262]
I think it’s worth bringing back HDR because:
- Directly affects the brightness of the display.
- Pay for a phone with HDR and then not receive it (Addition to the first one).
- And at the same time the blob itself is in the system. 

What do you think?

**Comment by SkewedZeppelin** [comment]
VoWiFi is already removed.

Adding HDR back may be tricky.

**Comment by SkewedZeppelin** [comment]
Some of the HDR blobs depend on the DRM or HDC blobs, so they can't be added back without also adding back those too.
