### ISSUE TITLE
Remove Metadata From Screenshots

### ISSUE THREAD

**Issue by UntrimmedParasail** [Divested-Mobile/DivestOS-Build#263]
I believe GrapheneOS patched so EXIF data like the local time is removed from screenshots, [as described here.](https://grapheneos.org/features#private-screenshots)

As they mention the name shows the time anyway so there is no need to store it as metadata. 

DivestOS currently does have metadata in screenshots (I assume inherited from lineageOS / stock AOSP), including date time and also the build number which is potentially bad to leak (although I doubt people would know what it means). If a patch could be included to fix this that would be great.

Although what would be even more ideal is GrapheneOS' exact approach where there is a toggle to turn it back on in the settings if someone wants to do so (but no idea why they would).

**Comment by SkewedZeppelin** [comment]
I'll seek to add this for the November update.
