### ISSUE TITLE
How to download the latest available version of Mulch for Andoroid 7?

### ISSUE THREAD

**Issue by topminipie** [Divested-Mobile/DivestOS-Build#283]
F-Droid only displays the latest (Incompatible) versions.

**Comment by SkewedZeppelin** [comment]
You can't.

Chromium 120 and higher no longer supports Android 7.
https://groups.google.com/a/chromium.org/g/chromium-dev/c/B9AYI3WAvRo

Android 7 has been officially end of life since October 2019, or 4.2 years ago.

**Comment by SkewedZeppelin** [comment]
If you need the webview, it is here: https://gitlab.com/divested-mobile/mulch/-/tree/m119
That webview is also bundled in DivestOS

If you need the standalone Mulch 119, I strongly suggest instead using an updated browser like Firefox or preferably my Mull.
