### ISSUE TITLE
Davinci Enhacement

### ISSUE THREAD

**Issue by TRKARTAL** [Divested-Mobile/DivestOS-Build#288]
Hello Dear developer.

It would be really glad to see the Davinci on the top of the DivestOS builds, as LineageOS does.

The Davinci still keeps to getting updates with Android 13, thanks to LineageOS.

DivestOS will be the best option in order to keep up the device's lifetime with more efficiently, instead of stucking in DivestOS 17.1 and/or LineageOS 20.0

For the quick access, here is the latest LineageOS Davinci build, which was made on 28 th. of January, 2024:

https://download.lineageos.org/devices/davinci/builds

For your willing to update,

Best regards.

**Comment by SkewedZeppelin** [comment]
There is already 20.0 for davinci, however it isn't shipped because Wi-Fi doesn't work and no one has stepped up to fix it: https://github.com/Divested-Mobile/DivestOS-Build/issues/238

**Comment by TRKARTAL** [comment]
@SkewedZeppelin sorry for disturb, but i could not find the 20.0 versioned Davinci build, dear.

If there is open access on it, could you spot it in here please? I would like to debug and work on it.

**Comment by TRKARTAL** [comment]
The last question, may i learn that whenever if LineageOS 21.0 has been released for the Davinci, will you update the Davinci build aswell in order to take a chance of get stable build?
