### ISSUE TITLE
Making VoLTE work on capable devices

### ISSUE THREAD

**Issue by dktzde** [Divested-Mobile/DivestOS-Build#289]
All requirements are met. I had the same phone before on LineageOS (incl. GApps) and VoLTE worked with Telekom.de without any problems.

I have DivestOS installed. I have locked the bootloader.

LTE works. When I make a call I get a fallback to the 2G network.

There is no VoLTE setting in the menu.

What else could I try to make it work? Is there a way to add the network operator settings on DivestOS?

**Comment by SkewedZeppelin** [comment]
DivestOS removes numerous proprietary carrier blobs, so VoLTE works if it works and doesn't if it doesn't.
https://divestos.org/pages/faq#volte

**Comment by dktzde** [comment]
I tested it on Telekom-de and o2-de with the same problem.

If you're considering changing something with the carrier blobs for DOS 21, I'll be very happy to help with betatesting.

**Comment by dktzde** [comment]
Same for raven: tested on Telekom-de and o2-de with VoLTE not working.

@SkewedZeppelin
Is there perhaps a place where this information could be collected? I'm sure I'm not the only one for whom VoLTE is important.

Should I assume that all mobile phones that are not listed there do not work with VoLTE?
https://divestos.org/pages/faq.html#volteTested

**Comment by ethical-haquer** [comment]
I experienced the same issue, Pixel 3 with ATT.
I hope that VoLTE support can be added for blueline eventually, for now I'm running CalyxOS.

**Comment by SkewedZeppelin** [comment]
This is unlikely to be fixed.

Having a way of collecting, inspecting, and adding updated MBN configs would likely dramatically help, however that is an extremely non-trivial task.

**Comment by ethical-haquer** [comment]
> > Should I assume that all mobile phones that are not listed there do not work with VoLTE?
> 
> Most devices after 2016/2017 do support VoLTE. The issue is having the actual configs for your carrier available.
> 
> This is unlikely to be fixed.
> 
> Having a way of collecting, inspecting, and adding updated MBN configs would likely dramatically help, however that is an extremely non-trivial task.

Thanks for the reply!
What would make flame (Pixel 4) and taimen (Pixel 2 XL) work with VoLTE, but not the Pixel 3? Would someone getting the MBN configs from a Pixel 3 help at all? TIA.

**Comment by SkewedZeppelin** [comment]
VoLTE works on all the Pixel's supported by DivestOS.

Again it just depends if the config for your carrier is included or not. And they aren't something easily sourced as they can be modem dependent.

**Comment by dktzde** [comment]
[@SkewedZeppelin](https://github.com/SkewedZeppelin)
Thank you for the detailed answer. I finally understand the issue.

Should I assume that none of the Pixel smartphones currently work with my carriers (Telekom-de, o2-de)?

Can you recommend a smartphone I can test that is more likely to work with VoLTE in Germany?

**Comment by dktzde** [comment]
@ethical-haquer

OT: What will you use when CalyxOS support ends? I tried CalyxOS some time ago and was unhappy with the ASB delay on Pixel 3 earlier this year. At the moment, I use DivestOS on one Pixel and still LinageOS with GApps on the other, but I consider to switch to IodéOS on the second one.

**Comment by SkewedZeppelin** [comment]
> Should I assume that none of the Pixel smartphones currently work with my carriers (Telekom-de, o2-de)?

The newer the device, the more likely there is a matching config included for your carrier.
ie. the greater the chance it will actually work.

**Comment by ethical-haquer** [comment]
Now I'm confused. VoLTE Is working fine on CalyxOS, so why would it not on DivestOS? They're both forks of Lineage OS, so is it that Divest OS removes something  related to that?

@dktzde 
I will then have to switch to a different OS that still supports the Pixel 3, or have to use a different device. I'm not as impressed with Calyx as I was with Divest though. First of all, they list the Pixel 3 under "Extended Support", which means that it will probably be dropped soon, as you said. Secondly, it's just not as modified as Divest is, you can see that here.

**Comment by SkewedZeppelin** [comment]
@ethical-haquer 
DivestOS makes thousands of changes.
The issue here, as already stated above, is the removal of the proprietary carrier apps.
https://github.com/Divested-Mobile/DivestOS-Build/blob/180ad2d17d2804dc315a9ef1102b042541883f3b/Scripts/Common/Deblob.sh#L280-L282
https://github.com/Divested-Mobile/DivestOS-Build/blob/180ad2d17d2804dc315a9ef1102b042541883f3b/Scripts/Common/Deblob.sh#L112-L128
https://github.com/Divested-Mobile/DivestOS-Build/blob/180ad2d17d2804dc315a9ef1102b042541883f3b/Scripts/Common/Deblob.sh#L168-L181
https://github.com/Divested-Mobile/DivestOS-Build/blob/180ad2d17d2804dc315a9ef1102b042541883f3b/Scripts/Common/Deblob.sh#L314-L319

**Comment by ethical-haquer** [comment]
Thanks again, I really appreciate you answering my noob questions. 😊

That explained it to me. I wasn't sure where the connection between the MSN configs and the blob removal was.

Looking at the commits, it looks like this issue should be fixed in LOS 21, if I read [this commit](https://github.com/LineageOS/android_device_google_crosshatch/commit/9bf6c1b647a47f3a9c93faa545d51980161076ad) correctly:

```
* From coral TP1A.221005.002.B2
* Update CNE IMS QMI RIL system/vendor blobs
* blueline/crosshatch's RIL blobs Still P's blobs, but not
  working already in 13 (e.g. missing LTE singal)
  so update RIL blobs

```

**Comment by SkewedZeppelin** [comment]
@ethical-haquer 
that commit is highly unlikely to change anything in regard to this issue.

**Comment by ethical-haquer** [comment]
@SkewedZeppelin 
I would like to help out (if I can) with supporting more carriers on the Pixel 3. I still have more questions though, and I'm not sure if I should clutter this issue any more than it already is. Do you have the same username on XDA?

**Comment by SkewedZeppelin** [comment]
This or the chat would be the better place.
But really someone needs to:
1) make a collection of sorted mbn files
2) make a program that can inspect them in order to sort by modem, version, carrier, and country
    - this likely requires significant effort
3) collate them into a repository
4) integrate that into the build system

**Comment by ethical-haquer** [comment]
Alright. So, just in case you haven't noticed, I didn't even know what MBN were, or that they were even a thing 😄. Also, there doesn't seem to be any "documentation" on MBN files. So, to begin with, getting the MBN files. The ones we need should be somewhere in the vendor.img, correct? For step two, it sounds like we need to be able to read the MBN files, but not write them, right?

**Comment by ethical-haquer** [comment]
I finally mounted vendor.img, and the mbn files are indeed there:
![vendor img](https://github.com/Divested-Mobile/DivestOS-Build/assets/141518185/9db7c3bd-3e1e-4a3c-82d9-d44554decbed)
![mbm](https://github.com/Divested-Mobile/DivestOS-Build/assets/141518185/f896a64b-c788-4598-98fb-de9806cc33c9)
I'm now looking into reading them.

**Comment by SkewedZeppelin** [comment]
@ethical-haquer 
> reading them

they are statically linked executables that contain some xml configs but also execute code

**Comment by SkewedZeppelin** [comment]
if anyone is really serious about this, I've spoken to NLnet in the past and this could potentially be such a grant supported by them

**Comment by ethical-haquer** [comment]
> @ethical-haquer
> 
> > reading them
> 
> they are statically linked executables that contain some xml configs but also execute code
> 
> there is extensive work here https://github.com/sbaresearch/mbn-mcfg-tools
> 
> if someone with the experience really wants to work on this, they should probably make a proposal for a grant before starting

Yes, I was looking at that tool, thanks for mentioning it.
What is a grant? 😊 (though I don't think I qualify as having "the experience", I'm just experimenting)

**Comment by SkewedZeppelin** [comment]
> What is a grant? 

you'd get paid to work on it as it progressed or reached completion

**Comment by ethical-haquer** [comment]
> > What is a grant?
> 
> you'd get paid to work on it as it progressed or reached completion
I just saw your second comment, I _do_ know what that is. 🤦
Obviously it won't be easy, but I think I can do most of the stuff in your simplified list.
I'm doing this in my spare time though, and I don't think I need to get paid, unless hardware is required. Maybe I'm missing something though.

**Comment by ethical-haquer** [comment]
@SkewedZeppelin 
I mounted the Pixel 3 DivestOS vendor.img, and the ATT .mbn(s) are there. Is the issue that they are not the latest ones? You showed me the [list of .mbn files it falls back to](https://github.com/LineageOS/android_device_google_crosshatch/blob/lineage-20/blueline/proprietary-files-vendor.txt#L1039-L1217); where are those files stored? TIA.

**Comment by ethical-haquer** [comment]
Thanks for the info!
Yes, I do know that site, it's also a good resource.
The Pixel 5 looks like it has good support as well.

**Comment by ethical-haquer** [comment]
@SkewedZeppelin
Apparently the Pixel 4 and Pixel 4a are affected by this issue as well: [link](https://www.reddit.com/r/DivestOS/comments/1bo9ubq/pixel_4_flame_pixel_4a_sunfish_no_call_connection/)
After thinking about it more, I think the .MBN files are not necessarily the issue, rather it is the removal of carrier apps.
Pretty much whenever somebody has an issue with VoLTE on DOS, people mention the removal of carrier apps.
For example, in this issue you mention them, and in the link above.
What I'm thinking, obviously I don't _know_, is that what's in the .MBN files determines what carrier apps are required to be installed for VoLTE to work.
If someone was able to say "the removal of the the ... app makes VoLTE not work on the ... phone with the ... carrier", what action would be taken?
Would that app be removed from the de-blob list?
TIA.

**Comment by ethical-haquer** [comment]
@SkewedZeppelin
I know you said "I myself am not interested in tackling the scope of this at this time.", but do you at least know anyone who might be able to answer these silly questions? TIA.

**Comment by SkewedZeppelin** [comment]
I've added some changes that should enable VoLTE on more carriers.
- https://github.com/Divested-Mobile/DivestOS-Build/commit/4328ec6c6594f3949113ccd923eecaa36d8f7b1f
- https://github.com/Divested-Mobile/DivestOS-Build/commit/2850ff678af543e9787774c14a27db98156189eb

**Comment by ethical-haquer** [comment]
> I've added some changes that should enable VoLTE on more carriers.
> 
>     * [4328ec6](https://github.com/Divested-Mobile/DivestOS-Build/commit/4328ec6c6594f3949113ccd923eecaa36d8f7b1f)
> 
>     * [2850ff6](https://github.com/Divested-Mobile/DivestOS-Build/commit/2850ff678af543e9787774c14a27db98156189eb)
> 
> 
> already tested on a few so far to work 🚀

Nice! Thanks for working on that.

**Comment by dktzde** [comment]
It works for me. Thank you so much!
How about you @ethical-haquer?

**Comment by ethical-haquer** [comment]
> It works for me. Thank you so much! How about you @ethical-haquer?

I haven't tried it yet. Looks like I'll have to now! 🥳

**Comment by ethical-haquer** [comment]
@SkewedZeppelin, @dktzde 
I finally got around to re-flashing DivestOS, and VoLTE worked for me on ATT after toggling the CarrierConfig2 toggle on. Thanks for working on this!
