### ISSUE TITLE
Samsung Galaxy S4 Mini Duos (GT-I9192) - serranodsdd not recognizing inserted SIM-cards

### ISSUE THREAD

**Issue by AliRezayiNejad** [Divested-Mobile/DivestOS-Build#293]
DivestOS 18.1 (Android 11 - Feb 8th, 2024) does not recognize SIM-card as inserted in either slot. Everything else works flawlessly.

**Comment by SkewedZeppelin** [comment]
Did it work previously?

Do you have the latest recommended firmware?

**Comment by SkewedZeppelin** [comment]
Follow this guide https://xdaforums.com/t/modem-odin-stopped-samsung-galaxy-s4-mini-duos-i9192.2768593/

**Comment by AliRezayiNejad** [comment]
Thank you very much, the problem was with the firmware.
