### ISSUE TITLE
blueline: Error while flashing boot (installation)

### ISSUE THREAD

**Issue by dktzde** [Divested-Mobile/DivestOS-Build#295]
During installation, I received the following error message: "Error Flashing boot".

I used the following procedure to successfully install DivestOS:
- I unpacked divested-20.0-20240214-dos-blueline-fastboot.zip
- I checked if I am in slot a or b
- if slot a:
fastboot flash boot_a boot.img
- if slot b:
fastboot flash boot_b boot.img

Then I followed the installation instructions and the installation went fine.

**Comment by SkewedZeppelin** [comment]
Why were you manually flashing it?

Use `fastboot update divested-20.0-20240214-dos-blueline-fastboot.zip`

**Comment by dktzde** [comment]
Thanks for the quick reply.

Do I neet to use fastboot version 33.0.3 or the newest version?

I was using fastboot 34.0.1. I have now updated to 35.0.0. Thanks for the tip!

(I had used fastboot update divested-20.0-20240214-dos-blueline-fastboot.zip for the installation - while doing so the above error message occurred)

**Comment by SkewedZeppelin** [comment]
I haven't tested 35.
Some versions of 34 are however known not to work.
Try 33.0.3 first, it is known working.

**Comment by dktzde** [comment]
> You need to be on fastboot 33.0.3

FYI: The CalyxOS Installer also uses this version.
