### ISSUE TITLE
Remaining bloated app?

### ISSUE THREAD

**Issue by tcrxt** [Divested-Mobile/DivestOS-Build#296]
The [Universal Android Debloater GUI](https://github.com/0x192/universal-android-debloater) hasn't been updated in a while, but it recommends to uninstall the following applications on a fresh installation of DivestOS:

```
com.android.bluetoothmidiservice
com.android.calllogbackup
com.android.dreams.phototable
com.android.egg
com.android.providers.partnerbookmarks
com.android.systemui.plugin.globalactions.wallet
```

I get that the first one may be useful in some cases, but the others seem safe to remove from vanilla installations.

**Comment by SkewedZeppelin** [comment]
Define "bloat".

DivestOS ships fewer pre-installed apps than any other OS.

**Comment by tcrxt** [comment]
Ok, thanks. "Bloat" seemed to apply to typically `com.android.egg`, which doesn't provide any feature and cannot be easily installed otherwise.
