### ISSUE TITLE
OnePlus 9 Pro: stuck at Qualcomm crashdump

### ISSUE THREAD

**Issue by josefv2** [Divested-Mobile/DivestOS-Build#297]
I've rigorously followed all steps.

```
Backup your device.
Follow the prerequisite steps [here](https://divestos.org/pages/bootloader#prereq)
Reboot to the bootloader: With the device powered off, hold Volume Up + Volume Down + Power.
$ fastboot oem unlock or $ fastboot flashing unlock
Reboot the device, then reboot back to bootloader
$ fastboot erase avb_custom_key
$ fastboot flash avb_custom_key avb_pkmd-lemonadep.bin
Reboot to the bootloader
$ fastboot update divested-20.0-20240214-dos-lemonadep-fastboot.zip
```

The problem comes after the last command. Now I should boot into recovery, but instead, I'm met with Qualcomm crashdump screen. I read you should install a recovery and I also tried but now I'm stuck in an endless boot screen. The lst quoted command ends like this:
```

Rebooting into fastboot                            OKAY [  0.002s]
< waiting for any device >
```
If I manually reboot into fastboot I get this:
`fastboot: error: Failed to boot into userspace fastboot; one or more components might be unbootable.`

**Comment by SkewedZeppelin** [comment]
You're likely on a very old firmware
Try to update it first: https://wiki.lineageos.org/devices/lemonadep/fw_update/

**Comment by josefv2** [comment]
> You're likely on a very old firmware Try to update it first: https://wiki.lineageos.org/devices/lemonadep/fw_update/

There are two problems: I can'n install apps as my OS is wiped, and LineageOS recovery boots on an endless boot screen. Should I factory reset it? And will updating to Android 14 update the firmware too?

**Comment by SkewedZeppelin** [comment]
Factory reset won't do anything

You don't need apps to extract the firmware, you can download them here https://gitlab.com/the-muppets/proprietary_vendor_firmware/-/tree/lineage-20/lemonadep/radio?ref_type=heads

**Comment by josefv2** [comment]
> Factory reset won't do anything
> 
> You don't need apps to extract the firmware, you can download them here https://gitlab.com/the-muppets/proprietary_vendor_firmware/-/tree/lineage-20/lemonadep/radio?ref_type=heads

Thanks. I assume this is from the LineageOS guide you posted. If so, I followed that guide and I'm facing the following problem at the first command:

```
fastboot flash --slot=all abl abl.img
fastboot: error: Could not check if partition abl has slot all

fastboot flash abl abl.img
Sending 'abl' (212 KB)                             OKAY [  0.007s]
Writing 'abl'                                      FAILED (remote: 'Flashing is not allowed for Critical Partitions
')
fastboot: error: Command failed
```

**Comment by SkewedZeppelin** [comment]
try `fastboot flashing unlock_critical`

**Comment by josefv2** [comment]
> try `fastboot flashing unlock_critical`

```
fastboot flashing unlock_critical
FAILED (remote: '       Device already : unlocked!')
fastboot: error: Command failed
```

**Comment by josefv2** [comment]
Any update pls? Is there hope for my device?

**Comment by SkewedZeppelin** [comment]
You can always use msmdownloadtool to go back to 1000% stock and try the process again.
https://xdaforums.com/t/op9pro-repository-of-msm-unbrick-tools-tmo-eu-glo-in.4272549/
