### ISSUE TITLE
Nexus 4 and nexus 7 debx dont have the oem flag under developer settings anymore

### ISSUE THREAD

**Issue by sbe-arg** [Divested-Mobile/DivestOS-Build#298]
Not sure why.
Both devicea don't show the oem falg in developer settings anymore.

Nexus4 was locked a year ago or so
Nexus7 is intended to be locked (currently unlocked post fresh setup)

**Comment by SkewedZeppelin** [comment]
These devices don't use that function, that was first introduced with the Nexus 9, 5x, and 6p

ie. you can always unlock them

**Comment by sbe-arg** [comment]
Nice. Facepalm on my end
