### ISSUE TITLE
Create a place to collect VoLTE test results for different phones on different carriers

### ISSUE THREAD

**Issue by dktzde** [Divested-Mobile/DivestOS-Build#301]
As VoLTE may become increasingly important, I would like to have a central place where we can collect possible tests.

I can imagine a table of devices and operators.

For example:

| | Germany |  |
|--------------|-----------|------------|
| carrier-name | 262-01 | 262-03 |
| | Telekom-de | o2-de |
| blueline | no | no |
| raven | no | no |

I think an "official" DivestOS place would be very good, so that it can be found by potential interested people.

My first idea was a table in the github wiki. This is not used yet. Maybe a txt or something similar on the website or only in the repository is an option.

This topic is linked to https://github.com/Divested-Mobile/DivestOS-Build/issues/289

**Comment by dktzde** [comment]
It works with you latest update - thank you so much!

**Comment by SkewedZeppelin** [comment]
@dktzde with the toggle enabled?

**Comment by dktzde** [comment]
Yes - took me a litte time to find ist.
