### ISSUE TITLE
Preferred network type: 4G only instead of 4G

### ISSUE THREAD

**Issue by ketchup-mayor** [Divested-Mobile/DivestOS-Build#305]
When selecting the network type there are following choices:
- 4G only
- 5G (recommended)
- 4G
- 3G

If you choose 4G, you assume the device is using 4G, 3G and 2G. But it changes the status to 4G only.

Device is Fairphone 4 with the newest DivestedOS may update installed.

**Comment by SkewedZeppelin** [comment]
Nah, it is just an issue with the label.

The option selected is the option enforced.

But when you're not in the menu it bugs out and shows `4G only`.

**Comment by ketchup-mayor** [comment]
Thank you for your fast reply. Very helpful!
