### ISSUE TITLE
Date And Time Not Appear (With No Animations On)

### ISSUE THREAD

**Issue by slendermon** [Divested-Mobile/DivestOS-Build#312]
I am using Pixel 4 Android 13 DivestOS, Happened to me last time I used Pixel 3a XL

I use the developer mode to turn off all animations ( or from accessibility no animations ), and it will cause the glitch in above the quick settings, when pulling down and letting go to extended quick settings very fast:
![Screenshot_20240621-214943_Lawnchair_1](https://github.com/Divested-Mobile/DivestOS-Build/assets/97182340/3c051588-3b5c-4002-a23c-aaac33cc8f7e)

It's supposed to look like this:
![Screenshot_20240621-214947_Lawnchair_1_1](https://github.com/Divested-Mobile/DivestOS-Build/assets/97182340/2381f90a-ec08-4269-827e-c0c55e77ab1f)

With animations (animator duration scale on, and not manually making it pull down fast) it works properly

**Comment by slendermon** [comment]
I can't tell if this is a LineageOS issue or not, but disabling animations makes split screen apps impossible

**Comment by SkewedZeppelin** [comment]
Please do not disable animations.
This issue has existed in AOSP & partly LineageOS changes for years, it is unlikely to be fixed.

Disabling animations can break various apps outside of the system's control too.

**Comment by slendermon** [comment]
Probably add a note if wanted.
