### ISSUE TITLE
Latest update appears in the list even device is up-to-date

### ISSUE THREAD

**Issue by attisimon** [Divested-Mobile/DivestOS-Build#316]
Hello!

Device: Google Pixel 3 (blueline)
OS: 20-20240615-dos-blueline

First of all, I want to report back that this device can be locked successfully.

Second, the issue is that, although I initially installed the latest version (20240615), when checking for updates, the same version appears as update. I downloaded it, installed it, rebooted the device, but the update is still in the list as waiting for being installed.

There is no error message, device is working, installation takes some time and I kept an eye on it to see if there is anything displayed, but nothing out of the ordinary is seen.

These are the stages: Downloading update, Confirming to apply update, Preparing for first boot, Finalizing package installation, Reboot, Update still there as if it was not installed.

<img alt="Screenshot" src="https://github.com/Divested-Mobile/DivestOS-Build/assets/7713006/c189af23-d3fc-475c-bc64-946018180b14" width="230" />
<img alt="Screenshot" src="https://github.com/Divested-Mobile/DivestOS-Build/assets/7713006/525108cc-0779-432f-b06c-b6f07788ad48" width="230" />
<img alt="Screenshot" src="https://github.com/Divested-Mobile/DivestOS-Build/assets/7713006/f4b391be-a782-4ab2-88b4-35182b76fb45" width="230" />
<img alt="Screenshot" src="https://github.com/Divested-Mobile/DivestOS-Build/assets/7713006/8fe4926f-87c9-433b-bd61-6384f7d6e4c4" width="230" />
<img alt="Screenshot" src="https://github.com/Divested-Mobile/DivestOS-Build/assets/7713006/d10ecc4b-e135-47e5-bd1d-03852dcbb00b" width="230" />
<img alt="Screenshot" src="https://github.com/Divested-Mobile/DivestOS-Build/assets/7713006/b8691e16-ab0d-470b-adbf-d4cab705d224" width="230" />
<img alt="Screenshot" src="https://github.com/Divested-Mobile/DivestOS-Build/assets/7713006/acf03262-b96a-4102-a524-a1e2c3fa083c" width="230" />

**Comment by SkewedZeppelin** [comment]
This is intentional and expected.
https://divestos.org/pages/broken#notes
> The Updater will show the currently installed update, this is expected.

**Comment by steadfasterX** [comment]
> This is intentional and expected. https://divestos.org/pages/broken#notes
> 
> > The Updater will show the currently installed update, this is expected.
> 
> You can delete the update once installed.

Interested on a fix for that ;) ? 
I stumbled over that issue one long ago when offering my first OTA's.. its quite easy to fix but I dont know if u really want it that way or not

**Comment by SkewedZeppelin** [comment]
It is not a bug. It makes it easy to install the update again to the other slot if necessary or to verify that update capability still works.

**Comment by steadfasterX** [comment]
> It is not a bug. It makes it easy to install the update again to the other slot if necessary or to verify that update capability still works.

True, its not a bug but its not intentional or how it is meant to be. 

You found some valid points to keep it like that though and it is like you want to have it and thats fine. Thats why I've asked. All good

**Comment by attisimon** [comment]
> This is intentional and expected. https://divestos.org/pages/broken#notes
> 
> > The Updater will show the currently installed update, this is expected.
> 
> You can delete the update once installed.

I already had the latest version, but I downloaded the update and installed it, thinking that I missed somthing. Then if I delete it, it will still appear in the list, available for download. 
I understand that this is something good to have for testing, but it is still confusing. 
So, this is out of the ordinary, but I'll have to accept that this is how it is done in DivestOS.

**Comment by attisimon** [comment]
I would also like to add, regarding future updates and allowing the bootloader to be unlocked, I would suggest to add an extra message about this before starting the update process, similar to the one in the second screenshot.

Not everyone is willing to keep OEM unlock "on", but it could be briefly done before each update, just to make sure. 

I know this is user specific, but because this is again out of the ordinary, an extra message would be of help.

Thanks!

**Comment by SkewedZeppelin** [comment]
> Not everyone is willing to keep OEM unlock "on", 

There is no downside to this.
Anyone attempting to unlock the device will still cause a wipe to be invoked before the actual unlock happens.
DivestOS only recommends you keep it enabled.

**Comment by SkewedZeppelin** [comment]
>  but the device will still be usable

A wipe can be invoked regardless.

> Are there any serious implications of using this toggle before and after every OTA update?

Do not do this.

**Comment by attisimon** [comment]
>A wipe can be invoked regardless.

Is this the case with any Pixel with stock, or only for DivestOS?

Thanks for all this info, I made a note.

**Comment by SkewedZeppelin** [comment]
Why do you think a wipe can't be invoked?

Just boot into the recovery and see there is a `factory reset` option.

The stock OS however has Google Play services which offers Factory Reset Protection.
ie. if phones home to Google to see if it was logged out first or not and demands signin again if it wasn't logged out before reset.

**Comment by attisimon** [comment]
I wasn't sure about the precise details, but I knew that there was something there against theft/reselling-stolen, but your reply cleared my thoughts. Thanks!
