### ISSUE TITLE
DivestOS 21/Android 14 on pixel 6 or newer

### ISSUE THREAD

**Issue by andrewnoonan2004** [Divested-Mobile/DivestOS-Build#328]
Hello, first I wanted to say I am very grateful for the work DivestOS does, not only for its OS but the greater FOSS ecosystem. I hope this question doesn't seem entitled or impatient, but I was wondering when DivestOS builds based on Android 14 may become available? Perhaps around the release of Android 15? Thanks in advance for your time and consideration.

**Comment by SkewedZeppelin** [comment]
Work on it was started back in May but there are issues porting the network and sensors permissions as well as inline kernel building.
