### ISSUE TITLE
DivestOS_16 build is kinda broken

### ISSUE THREAD

**Issue by Chococatpp** [Divested-Mobile/DivestOS-Build#330]
The build end successfully but webview signatures in framework-res don't work, and almost all the patches aren't applied.
I basically just got a lineageos build of 2022 with webview broken.  Also all my vendor blobs aren't in the build and my kernel is broken probably for the hardening patches. even after disable all deblob options. I just had to put them manually in my vendor partition and also i needed to flash a custom kernel to make this boot. (My vendor, device tree and kernel work normally on lineageOS)

I followed: https://divestos.org/pages/build 
but with lineageos 16 insted of 20

**Comment by SkewedZeppelin** [comment]
Please follow the steps again. They are tested to fully work.

**Comment by Chococatpp** [comment]
yeah it seems like doing resetWorkspace; broke something. i had too rm * and resync. But yeah i had to copy my vendor files again cuz it bootlooped
