### ISSUE TITLE
Wi-Fi randomly stops working on almost every app (platina)

### ISSUE THREAD

**Issue by ObjectiveFresh65** [Divested-Mobile/DivestOS-Build#334]
Starting from the last update Wi-Fi randomly stops working, that is when I enable it, sometimes it works without issues but sometimes doesn't work anymore, in every app, it gets connected but I don't have connection. 

When I try to open a browser I get the error "ERR_NAME_NOT_RESOLVED" but for some reason there is only one app where it works and it works too when I open the Divest Support app and try to visit Recommended Apps or News in a browser but if I do a simple search, it doesn't work. A strange issue is also the fact the sometimes I have connection in my Work Profile but not in my User Profile.  I don't know if this is related to Divest OS, but I noticed it since the last update, I guess it's worth reporting it.

**Comment by SkewedZeppelin** [comment]
What is your connectivity check server set to? And Private DNS? Is the content blocker enabled? Are you using a VPN?

**Comment by ObjectiveFresh65** [comment]
My connectivity check server is set to DivestOS, I use Quad9 as a Private DNS, content blocker is enabled and yes, I use a VPN but it's not always on, only when I need it.

**Comment by SkewedZeppelin** [comment]
Can you try using both a different connectivity check and Private DNS servers and see if it still happens?

**Comment by ObjectiveFresh65** [comment]
I tried using a different connectivity check and Private DNS and I still have the issue, apps have no connection but this time too, as I said in the first comment, only one app works and the links in the DivestOS support app work too, I can reach them on a browser but if I try to search something it's like if there is no connection.

**Comment by SkewedZeppelin** [comment]
Can you verify those apps have both network permission granted and no network restrictions set?

https://divestos.org/pages/faq#networkControl
- For simply blocking an app from say using mobile data, use the built-in data restrictions: App info > Mobile data & Wi-fi
- For completely denying an app access to networking functions entirely, revoke the Network permission: App info > Permissions > Network

**Comment by SkewedZeppelin** [comment]
- have you made any other changes to the system via eg. adb or root?
- is it more likely to work with a VPN enabled?
- does it work with other wifi networks or cellular?

it sounds like a DNS issue and only domains that are cached are working

**Comment by ObjectiveFresh65** [comment]
I want to inform you that Wi-Fi started working again, I don't know why, and then I tried one thing, I disabled Wi-Fi and enabled and disabled Mobile Data rapidly and then tried to enable Wi-Fi again and it did not work anymore, I don't know if this is reproducible.

* yes
* no
* I tried and no
* it works with other cellulars, no issues, it is only for me that doesn't work
* no
* no
* don't know

Anyway I don't know if this issue is related to DivestOS so if this doesn't get far I guess I'll try formatting or reinstalling

**Comment by SkewedZeppelin** [comment]
strange

> I'll try formatting or reinstalling

this is never the solution

**Comment by ObjectiveFresh65** [comment]
I understand, but if we don't know what is the issue related to, I don't know what solutions to try, so if you need logs or other things that I have to check let me know.

**Comment by ObjectiveFresh65** [comment]
I have an update, the issue is still present, I have it from time to time but I was able to produce it. 

What I did was activating Wi-Fi and it was still working, then I enabled work profile, disabled Wi-Fi and disabled work profile, then I activated Wi-Fi again and it was not working anymore. I don't know if this is going to give you any clue but I try anyway, I tried to describe it as best I could.

**Comment by ObjectiveFresh65** [comment]
I want to update the situation regarding this issue, I want to inform you that I did not encounter the bug in the last month, so all good so far. I don't know what solved the problem, if it was my ISP, my VPN provider or a Divest OS update, anyway I appreciate the help you provided. I don't know if it's going to reappear someday but, as of now, I guess we can close the issue as there's no reason to keep it open since I'm not getting it anymore.

**Comment by SkewedZeppelin** [comment]
no worries, feel free to re-open if it happens again
