### ISSUE TITLE
Problems with apps that use Bluetooth data transfer

### ISSUE THREAD

**Issue by dktzde** [Divested-Mobile/DivestOS-Build#335]
I have problems with 2 apps that use the Bluetooth connection to transfer data.
Since according to the website nothing has been changed in Bluetooth, could it be that I have overlooked a setting that is necessary for it to work?

Unfortunately, both apps can only be tested with the corresponding remote station.

What other information could help to narrow down the problem?

Cell phone: blueline, with current DivestOS

App 1:
[Post & DHL](https://play.google.com/store/apps/details?id=de.dhl.paket)
App for the German market. This is (also) used to establish contact with so-called [“Packstations”](https://www.dhl.de/en/privatkunden/pakete-empfangen/an-einem-abholort-empfangen/packstation/packstation-kompakt.html). When the Bluetooth connection is established, an LED on the station flashes. This does not flash at all when I try to establish a connection, so I assume that for some reason unknown to me no connection attempt arrives at the other end.

App 2:
[mucar](https://play.google.com/store/apps/details?id=com.us.bt200)

This app is used to establish contact with an OBD Bluetooth dongle. To read out errors or similar in a car. No connection is possible here either.

I tested both apps on a oneplus X with Android 13 without microG or Playservices. There were no problems there. On a 2nd Pixel 3 with LineageOS and GApps it also runs without problems.

What could I do to better localize the problem?

**Comment by dktzde** [comment]
I was able to fix the problem myself. I had both apps in a shelter-work profile. When I moved the apps to my main profile, there were no more problems with Bluetooth connections.

**Comment by SkewedZeppelin** [comment]
oooh interesting! I'll add a note to the website for this, thanks!
