### ISSUE TITLE
SecureCamera patches fail since Android.mk is gone

### ISSUE THREAD

**Issue by danielk43** [Divested-Mobile/DivestOS-Build#338]
Heads up that the makefile has changed to .bp for this project.
My Patch.sh is set like this now:
```
if enterAndClear "external/SecureCamera"; then
sed -i '/name/s/Camera/SecureCamera/' Android.bp; #Change module name
sed -i 's/preprocessed/presigned/' Android.bp;
fi;
```
Not ideal to sub preprocessed to presigned, may need a separate row for A14+
but works fine for 20, maybe 19 also

**Comment by SkewedZeppelin** [comment]
Thanks!
