### ISSUE TITLE
Google Pixel 4a: usb adb connection / file sharing ... no longer possible after latest upgrade (September)

### ISSUE THREAD

**Issue by t3e** [Divested-Mobile/DivestOS-Build#341]
I've recently installed the Update from September, unfortunately before I installed it I decided to delete the current Image. Then after I installed the update I discovered that I was no longer able to connect via adb neither over usb nor wifi. When I open the USB settings I can no longer switch between different modes when I connect the device. I've tried with two different USB cables und also rebooted the device multiple times but the issue is still there.

**Comment by SkewedZeppelin** [comment]
sunfish uses the same exact kernel as coral/flame and my flame is fully functional.
please sideload the update twice and see if that helps

**Comment by SkewedZeppelin** [comment]
a user in the chat has also confirmed that usb is fully functional on their sunfish with the September update

**Comment by t3e** [comment]
Thanks for your reply.
Your right, it looks like both USB-C cables I tested are charging cables without data connection (I wasn't even aware that such a thing exists...).
