### ISSUE TITLE
could not find contact info anywhere, asking here.

### ISSUE THREAD

**Issue by daedaevibin** [Divested-Mobile/DivestOS-Build#344]
since you have allowed flashing a custom avb key, this means the device will pass vbmeta verity and verification correct? Does that mean it is possible to lock the bootloader afterwards since it has all been verified properly?

I did test, and no. It said invalid android images.

I realize this may have been due to me not rebooting before continuing to the fastboot update command.  I am re-flashing and doing so this time.

Also, may I ask what android version it is? There is no mention of this anywhere that I can find.

**Comment by SkewedZeppelin** [comment]
this is all documented on the website.

each top section of the downloads page says what android version it is and each device listed says whether or not it can be locked.

**Comment by daedaevibin** [comment]
> this is all documented on the website.
> 
> each top section of the downloads page says what android version it is and each device listed says whether or not it can be locked.
> 
> each section also has the installation steps via the "install method" link
> 
> devices that can be locked usually need both fastboot update, adb sideload, reboot, and another adb sideload before they can be locked
> 
> but you must test the system before locking

Ended up not using it when I realized it is in fact not updated.

All copyrights seem to be dated 2021 last updated, meaning there's a high chance this project is no longer maintained officially from the looks of it.

13 is pretty far behind, I would rather 14 or 15 (official release October 5th 2024)

**Comment by SkewedZeppelin** [comment]
There are monthly updates, this is documented here:
- https://divestos.org/pages/news
- https://divestos.org/pages/patch_history
- https://divestos.org/misc/ch-dates.txt
- https://divestos.org/misc/ffa-dates.txt

**Comment by steadfasterX** [comment]
> All copyrights seem to be dated 2021 last updated, meaning there's a high chance this project is no longer maintained officially from the looks of it.

yes! you made my day!
copyright dates is the most important part of a dev! but better do not look at commit histories or news entries or support channels to see if a project is alive and maintained.. its always better taking an eye on copyright dates..!
`/sarcasm off`

**Comment by daedaevibin** [comment]
> I don't know what you're looking at.
> 
> There are monthly updates, this is documented here:
> - https://divestos.org/pages/news
> - https://divestos.org/pages/patch_history
> - https://divestos.org/misc/ch-dates.txt
> - https://divestos.org/misc/ffa-dates.txt
> 
> You're welcome to pick another OS: https://eylenburg.github.io/android_comparison.htm

A13 is significantly behind the official stable release which is now A15 as of October 15 2024.

**Comment by daedaevibin** [comment]
> > I don't know what you're looking at.
> > 
> > There are monthly updates, this is documented here:
> > - https://divestos.org/pages/news
> > - https://divestos.org/pages/patch_history
> > - https://divestos.org/misc/ch-dates.txt
> > - https://divestos.org/misc/ffa-dates.txt
> > 
> > You're welcome to pick another OS: https://eylenburg.github.io/android_comparison.htm
> 
> A13 is significantly behind the official stable release which is now A15 as of October 15 2024.

At least that's the case for Bluejay (Pixel 6a) in specific

**Comment by SkewedZeppelin** [comment]
@daedaevibin 
DivestOS is primarily focused on supporting end of life devices.
If you have a Pixel 6 or newer you are strongly encouraged to go GrapheneOS then.

**Comment by daedaevibin** [comment]
> @daedaevibin 
> DivestOS is primarily focused on supporting end of life devices.
> If you have a Pixel 6 or newer you are strongly encouraged to go use GrapheneOS then.

Ah, okay that makes much more sense.

Even though, in my case, GrapheneOS is also a no go (for multiple reasons) until the legal disputes they've threatened against Google are either brought up or resolved.
