### ISSUE TITLE
One Plus 7 Pro no touchscreen response

### ISSUE THREAD

**Issue by MatthewBriggs** [Divested-Mobile/DivestOS-Build#345]
I installed the latest DivestOS build after formatting and updating to the latest OEM Android 11 build.

I did a factory reset when prompted.

After restarting I have no touchscreen support in DivestOS and have to use an external keyboard to restart the phone :-)

Camera, WiFi etc. all appears to be working.

In an attempt to help myself, I'm formatting the phone again. I'll update it to the latest version of 11, unlock the bootloader, then upgrade it to 12 (a step I skipped this time) and then install DivestOS. If it fixes it I'll close this issue.

**Comment by SkewedZeppelin** [comment]
Did you do both the `fastboot update` and the `adb sideload` per the install guide?

**Comment by MatthewBriggs** [comment]
ah ok - I followed these instructions: https://divestos.org/pages/bootloader#fastbootUnlocking

The recovery my phone rebooted into (I assume one that came with the build because there is no recovery download available) only had the option to factory reset, I didn't see an option for `adb sideload`.

I'll have another go.

**Comment by MatthewBriggs** [comment]
While attempting to use the sideload command, I have the same problem as reported here:

https://github.com/Divested-Mobile/DivestOS-Build/issues/113

**Comment by SkewedZeppelin** [comment]
You don't need copy-partitions, please follow the steps and use the correct files:
- https://divestos.org/builds/LineageOS/guacamole/install.html
- https://divestos.org/mirror.php?base=LineageOS&f=guacamole/divested-20.0-20241011-dos-guacamole.zip
- https://divestos.org/mirror.php?base=LineageOS&f=guacamole/divested-20.0-20241011-dos-guacamole-fastboot.zip

**Comment by MatthewBriggs** [comment]
It turns out I can't read :man_facepalming: 

Apologies. Donation incoming!

**Comment by SkewedZeppelin** [comment]
Just to confirm, installed and all working now?

**Comment by MatthewBriggs** [comment]
All working perfectly - thank you.

A couple of things that threw my sleep deprived brain, but are now obvious in hindsight:

- Because I didn't have a separate recovery I assumed that some parts of what followed didn't apply to me, because I got bounced straight to the factory reset.

- As I was flashing with fastboot, it wasn't clear to me that I also needed the sideload file (the one marked 'download' in the device list) and I assumed it was the same file in the instructions.

thank you for putting me on the right track

**Comment by SkewedZeppelin** [comment]
The factory reset prompt shows up when it doesn't recognize the system, like when coming from stock.
The fastboot image doesn't contain the firmware files, only the sideload image does.

**Comment by MatthewBriggs** [comment]
got it :-) thank you again. I'm very happy with my new install.
