### ISSUE TITLE
SimpleX as standard?

### ISSUE THREAD

**Issue by Jeffrey2307** [Divested-Mobile/DivestOS-Build#346]
I thought it would be a great Idea to make SimpleX Chat as pre installed App in the OS, when anyone newly installs DivestOS.

And which Apps does come preinstalled?

**Comment by SkewedZeppelin** [comment]
> SimpleX Chat as pre installed App i

no.

> Apps does come preinstalled?

- https://divestos.org/pages/technical_details#includedApps
- https://divestos.org/pages/screenshots#includedApps

**Comment by Jeffrey2307** [comment]
Okay I understand. May I ask if you update the Fossify Gallery in the System Update or do I need to update it manually? Because I don't like Fossify because many of their Apps lack in Updates...

**Comment by SkewedZeppelin** [comment]
It gets updates via the included F-Droid app. What is wrong with the gallery? What are supposed updates supposed to fix/improve?
You're welcome to disable any included app and use whatever you prefer.
