### ISSUE TITLE
How is Divestos working?

### ISSUE THREAD

**Issue by Jeffrey2307** [Divested-Mobile/DivestOS-Build#347]
How does updating System-Apps in DivestOS work? Do we update them always in F-Droid or once Month all get updated with System Update?

**Comment by SkewedZeppelin** [comment]
most updates are provided only in the monthly update

update for extra apps like F-Droid and Gallery are provided via F-Droid through F-Droid.org and updates for Mull and Mulch are provided via F-Droid through DivestOS.org

**Comment by Jeffrey2307** [comment]
So I don't need to update Fossify Gallery, because it is a System App or am I wrong?

**Comment by SkewedZeppelin** [comment]
Both the system updater and F-Droid will prompt you whenever updates are available.

**Comment by Jeffrey2307** [comment]
Okay thank you. I hope I can get a Build in the Future too that I can join this amazing Project!
