### ISSUE TITLE
Accrescent?

### ISSUE THREAD

**Issue by Jeffrey2307** [Divested-Mobile/DivestOS-Build#348]
hey i would love to see the Mulch App on Accrescent Store (which is the most secure and private Store and better solution than F-Droid or the Website) maybe you can apply there, because it would be the best and better solution and I would love to see you Guys there

And maybe if it is possible too, the Mulch System Webview.

**Comment by SkewedZeppelin** [comment]
no.

**Comment by Jeffrey2307** [comment]
Oh okay thank you! Your right, I can't understand these People too...
