### ISSUE TITLE
[Installation Error] Xperia XZ2 Compact, 'avb_custom_key' Partition Doesn't Exist

### ISSUE THREAD

**Issue by JosiahDanger** [Divested-Mobile/DivestOS-Build#351]
Hello all,

Thank you for your hard work in developing this operating system.

I would like to report an issue I have encountered during installation of DivestOS version 20.0 on my _new old stock_ Xperia XZ2 Compact (H8314), which arrived in the mail today. I updated to Android 10 by flashing stock firmware downloaded through XperiFirm. Having unlocked the phone's bootloader using fastboot, I proceeded in following the [device-specific DivestOS installation instructions](https://divestos.org/builds/LineageOS/xz2c/install.html).

Upon carrying out step (5.), an error occurred:

![Screenshot 2024-11-01 182327](https://github.com/user-attachments/assets/168e8f17-f0a9-4fc5-96f7-8d26149e43d8)
_FAILED (remote: 'No such partition.')_

Curious, I continued to step (6.) and attempted to flash the AVB key anyway. This resulted in the following message:

![Screenshot 2024-11-01 182613](https://github.com/user-attachments/assets/6a2263b5-9e24-4b12-839f-f4a965c4d33b)
_FAILED (remote: 'No such partition.')_

It would appear that the 'avb_custom_key' partition does not exist on my phone.

I continued to follow the installation instructions. I can confirm that I have now installed DivestOS without the presence of a valid AVB key. However, I would like to relock the bootloader. My understanding if that I will be unable to relock the bootloader until I can flash the correct AVB key.

Please advise.

**Comment by SkewedZeppelin** [comment]
Seems this is an edgecase in the installation steps generator.

This device doesn't need that actually since it can't actually be relocked, you can skip this step safely.

**Comment by JosiahDanger** [comment]
> Seems this is an edgecase in the installation steps generator.
> 
> This device doesn't need that actually since it can't actually be relocked, you can skip this step safely.

Thank you for your extremely fast response! So, to confirm, you are informing me that the 'xz2c' device bootloader cannot be relocked after installing DivestOS? Could you perhaps update the website Devices page and FAQ accordingly?

**Comment by SkewedZeppelin** [comment]
Yes I will adjust it, it was previously marked unknown because I thought there was a slim chance it was possible, but you're the first to actually confirm it isn't.

**Comment by SkewedZeppelin** [comment]
This should be fixed now, thank you for the report.
