### ISSUE TITLE
On Fairphone 3, since 2024.10.13 system update, System UI app seems to be draining battery

### ISSUE THREAD

**Issue by mkalinski** [Divested-Mobile/DivestOS-Build#353]
Since the October 13 update of DivestOS 20, on my Fairphone 3 phone, I noticed in Settings > Battery > Battery usage that "System UI" app is reported to consume inordinate amount of battery, dwarfing all apps I'm actually using.

This consumption doesn't seem to depend on me actually doing anything with the phone. Even if I leave it locked with a blanked screen, the battery usage graph is showing a constant decline.

I did not previously see System UI anywhere in the Battery usage apps list before the last update. It took me awhile to notice that this is happening, as the drain isn't so bad to make the phone unusable, the battery just last shorter than usual.

Another thing that seems to be connected to this issue is that when the phone reaches low battery, the system seems to try to show a new low battery notification on almost every percentile decrease, and these notifications get glitchy and delayed for minutes sometimes, and the battery level shown seems to desync between lockscreen and launcher screen.

I'm not sure how to best go about debugging this problem. I'd appreciate any hints, if more information is needed from me.

**Comment by mkalinski** [comment]
- I've rebooted the phone many times.
- The phone is not rooted.
- No changes via adb (other than instructions during DivestOS installation)
- No device admin apps.
- No secondary profiles.
- I'm using battery icon (as in, shaped like a battery) + text always shown outside icon.
- I have network traffic indicator enabled (but it's been like this long before the issue).
- Default launcher (Trebuchet).
- No visual artifacts other than battery indicator desync.
- At times the whole UI seems to momentarily slow down. It happens randomly and never for a long time. Usually happens after the battery hits low level (< 20%).
- There was also one time when System UI started crashing every few minutes. But it went away after reboot and didn't happen again.
- I did, actually. But it was to the default DivestOS wallpaper, from a different built-in wallpaper.

I'll try to check out the battery historian when I have time. Is the docker image still somehow available? I can't seem to pull it from gcr.io/android-battery-historian/stable:3.0

**Comment by SkewedZeppelin** [comment]
do you have any long running apps in the background like chat apps? sometimes the battery screen mistattributes the drain

I know a few months back someone was having rapid drain and it was showing as "System"  not "System UI" and it turned out to be an issue with their Matrix chat app reconnecting repeatedly.

**Comment by mkalinski** [comment]
I do have several long running background apps. I'll try disabling them for a day and get back to you.

**Comment by mkalinski** [comment]
Yes, it was a background app after all. I had it installed earlier, but I was fiddling with it around the time of the update and I must have configured something to make it drain battery.

I would have never thought that it would be counted as System UI, since it doesn't even have much UI to speak of (it's a server that only has localhost web interface).

Thanks for your assistance.
