### ISSUE TITLE
Moto X Style (Clark) - NFC does not work (anymore)

### ISSUE THREAD

**Issue by AgentSteel** [Divested-Mobile/DivestOS-Build#355]
Hello

Using latest build to date (october 17, 2024)

I noticed NFC does not work anymore (I'm sure it dit work in earlier builds, I used it with NFC tags from time to time)

Here is logcat output, when enabling/disabling NFC from settings, hope it is useful :

`
11-11 12:40:41.284  6041  6211 I NfcService: Enabling NFC
11-11 12:40:41.293  6041  6211 I com.android.nf: ConfigFile - Parsing file '/vendor/etc/libnfc-nci.conf'
11-11 12:40:41.295  6041  6211 I com.android.nf: ConfigFile - [APPL_TRACE_LEVEL] = 0x01
11-11 12:40:41.295  6041  6211 I com.android.nf: ConfigFile - [PROTOCOL_TRACE_LEVEL] = 0x00000000
11-11 12:40:41.295  6041  6211 I com.android.nf: ConfigFile - [NFA_STORAGE] = "/data/nfc"
11-11 12:40:41.295  6041  6211 I com.android.nf: ConfigFile - [NFC_WAKE_DELAY] = 20
11-11 12:40:41.295  6041  6211 I com.android.nf: ConfigFile - [NFCC_ENABLE_TIMEOUT] = 1000
11-11 12:40:41.295  6041  6211 I com.android.nf: ConfigFile - [POWER_ON_DELAY] = 300
11-11 12:40:41.295  6041  6211 I com.android.nf: ConfigFile - [PRE_POWER_OFF_DELAY] = 10
11-11 12:40:41.295  6041  6211 I com.android.nf: ConfigFile - [CE3_PRE_POWER_OFF_DELAY] = 1500
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [NFA_DM_DISC_DURATION_POLL] = 333
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [DEFAULT_OFFHOST_ROUTE] = 0xF3
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [OBERTHUR_WARM_RESET_COMMAND] = 0x03
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [UICC_LISTEN_TECH_EXCLUDE_MASK] = 0x10
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [AID_FOR_EMPTY_SELECT] = {08:A0:00:00:01:51:00:00:00}
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [POLLING_TECH_MASK] = 0xEF
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [SCREEN_OFF_POWER_STATE] = 1
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [TRANSPORT_DRIVER] = "/dev/bcm2079x-i2c"
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [POWER_CONTROL_DRIVER] = "/dev/bcm2079x-i2c"
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [NFC_WRITE_DELAY] = 20
11-11 12:40:41.296  6041  6211 I com.android.nf: ConfigFile - [ENABLE_VZW_AID_FILTERING] = 0
11-11 12:40:41.297  6041  6211 I com.android.nf: ConfigFile - [PRESERVE_STORAGE] = 1
11-11 12:40:41.297  6041  6211 I com.android.nf: ConfigFile - [AID_MATCHING_MODE] = 2
11-11 12:40:41.297  6041  6211 I com.android.nf: ConfigFile - [NOTIFY_EE_APP_INIT_EVENT] = 0
11-11 12:40:41.297  6041  6211 I com.android.nf: ConfigFile - [TRANSPORT_PREFIX] = 1
11-11 12:40:41.297  6041  6211 I libnfc_nci: [INFO:NfcAdaptation.cc(490)] NfcAdaptation::InitializeHalDeviceContext: INfc::getService()
11-11 12:40:41.299   358   358 I hwservicemanager: getTransport: Cannot find entry android.hardware.nfc@1.2::INfc/default in either framework or device manifest.
11-11 12:40:41.306   358   358 I hwservicemanager: getTransport: Cannot find entry android.hardware.nfc@1.1::INfc/default in either framework or device manifest.
11-11 12:40:41.314  6041  6211 I libnfc_nci: [INFO:NfcAdaptation.cc(499)] NfcAdaptation::InitializeHalDeviceContext: INfc::getService() returned 0x2fb92dc5e0 (remote)
11-11 12:40:41.320  6041  8001 E libnfc_nci: [ERROR:gki_ulinux.cc(98)] gki_task task_id=0 terminating
11-11 12:40:41.321   453   462 I USERIAL_LINUX: USERIAL_Open(): enter
11-11 12:40:41.321   453   462 I USERIAL_LINUX: USERIAL_Open() device: /dev/bcm2079x-i2c port=5, uart_port=0 WAKE_DELAY(20) WRITE_DELAY(20) POWER_ON_DELAY(300) PRE_POWER_OFF_DELAY(10) POST_POWER_OFF_DELAY(0)
11-11 12:40:41.633   453   462 I USERIAL_LINUX: USERIAL_Open(): exit
11-11 12:40:42.067   453   462 D BrcmNciR: 600003000111
11-11 12:40:42.068   453   462 D BrcmNciX: 2f0400
11-11 12:40:42.070   453   462 D BrcmNciR: 4f0428004a756c203138203230313430393a34383a313800021923a2950702073230373935413205009065
11-11 12:40:42.071   453   462 D BrcmNciX: 2f1d03059065
11-11 12:40:42.078   453   462 D BrcmNciR: 4f1d0100
11-11 12:40:43.120   453   462 D BrcmNciX: 2f2d00
11-11 12:40:43.124   453   462 D BrcmNciR: 4f2d230001040732303739354132000000000000000000050030000080487500002851000001
11-11 12:40:43.145   453   462 D BrcmNciX: 20000101
11-11 12:40:43.151   453   462 D BrcmNciR: 400003001101
11-11 12:40:43.153   453   462 D BrcmNciX: 200100
11-11 12:40:43.156   453   462 D BrcmNciR: 40011900030e0301080001020381848382058403ff3d002e02021923
11-11 12:40:43.158   453   462 D BrcmNciX: 20021101b90e0100ffff00008b130010000a0000
11-11 12:40:43.161   453   462 D BrcmNciR: 4002020000
11-11 12:40:43.161   453   462 D BrcmNciX: 2002830be0070c785b3a4e440ae1026901e204671d0012e30402042311e409592200000000000000e50d885a0160601104061260100014ca120000000008e8030000000000000000000003dd2d00002000000001850000000000005555555555555555555555555500a8000260607782e34c7f60609742e38c0f800101d60101de0401000000
11-11 12:40:43.171   453   462 D BrcmNciR: 4002020000
11-11 12:40:43.171   453   462 D BrcmNciX: 20020601b703020001
11-11 12:40:43.173   453   462 D BrcmNciR: 61070100
11-11 12:40:43.173   453   462 D BrcmNciR: 4002020000
11-11 12:40:43.173   453   462 D BrcmNciX: 2f060101
11-11 12:40:43.179   453   462 D BrcmNciR: 4f060100
11-11 12:40:43.180   453   462 D BrcmNciX: 2f05faf3ffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
11-11 12:40:43.191   453   462 D BrcmNciR: 4f050100
11-11 12:40:43.191   453   462 D BrcmNciX: 2f05faf4ffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
11-11 12:40:43.202   453   462 D BrcmNciR: 4f050100
11-11 12:40:43.203   453   462 D BrcmNciX: 2f05faf5ffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
11-11 12:40:43.214   453   462 D BrcmNciR: 4f050100
11-11 12:40:43.221   453   462 D BrcmNciX: 2f050bf2ffffffffffffffff0000
11-11 12:40:43.223   453   462 D BrcmNciR: 4f050100
11-11 12:40:43.225   453   462 D BrcmNciX: 21000702040302050303
11-11 12:40:43.228   453   462 D BrcmNciR: 41000100
11-11 12:40:43.230   453   462 D BrcmNciX: 20020e02510801feffffffffffff580107
11-11 12:40:43.234   453   462 D BrcmNciR: 4002020000
11-11 12:40:43.235   453   462 D BrcmNciX: 22000101
11-11 12:40:43.239   453   462 D BrcmNciR: 4200020001
11-11 12:40:43.239   453   462 D BrcmNciR: 620005f200010100
11-11 12:40:43.240   453   462 D BrcmNciX: 20040603010102f201
11-11 12:40:43.244   453   462 D BrcmNciR: 40040400ff0101
11-11 12:40:43.245   453   462 D BrcmNciX: 010003810201
11-11 12:40:43.249   453   462 D BrcmNciR: 01000a81803ceb545538eb5455
11-11 12:40:43.250   453   462 D BrcmNciR: 600603010101
11-11 12:40:43.251   453   462 D BrcmNciX: 01000481140201
11-11 12:40:43.255   453   462 D BrcmNciR: 0100028180
11-11 12:40:43.256   453   462 D BrcmNciR: 6f050bf2ffffffffffffffff0000
11-11 12:40:43.258   453   462 D BrcmNciR: 600603010101
11-11 12:40:43.259   453   462 D BrcmNciX: 0100028103
11-11 12:40:43.260   453   462 D BrcmNciR: 0100028180
11-11 12:40:43.262   453   462 D BrcmNciR: 600603010101
11-11 12:40:43.262   453   462 D BrcmNciX: 01000b81010102345555f40b5555
11-11 12:40:43.267   453   462 D BrcmNciR: 0100028180
11-11 12:40:43.268   453   462 D BrcmNciR: 600603010101
11-11 12:40:43.269   453   462 D BrcmNciX: 010006810103020304
11-11 12:40:43.275   453   462 D BrcmNciR: 0100028180
11-11 12:40:43.276   453   462 D BrcmNciR: 600603010101
11-11 12:40:43.375   453   462 D BrcmNciR: 620004f3020000
11-11 12:40:43.377   453   462 D BrcmNciR: 620004f4020000
11-11 12:40:43.381   453   462 D BrcmNciR: 620004f5020000
11-11 12:40:43.382   453   462 D BrcmNciX: 22000100
11-11 12:40:43.383   453   462 D BrcmNciX: 010003810204
11-11 12:40:43.388   453   462 D BrcmNciR: 4200020000
11-11 12:40:43.389   453   462 D BrcmNciR: 01000481800001
11-11 12:40:43.391   453   462 D BrcmNciR: 600603010101
11-11 12:40:43.393  6041  8002 E libnfc_nci: [ERROR:HciEventManager.cpp(151)] Incorrect Pipe Id
11-11 12:40:43.393   453   462 D BrcmNciX: 2003020152
11-11 12:40:43.395   453   462 D BrcmNciR: 4003050001520102
11-11 12:40:43.400  6041  6211 D NfcService: NCI_Version: 16
11-11 12:40:43.402  6041  6211 D NdefPushServer: start, thread = null
11-11 12:40:43.402  6041  6211 D NdefPushServer: starting new server thread
11-11 12:40:43.405  6041  8007 D NdefPushServer: about create LLCP service socket
11-11 12:40:43.408  6041  8007 D NdefPushServer: created LLCP service socket
11-11 12:40:43.408  6041  8007 D NdefPushServer: about to accept
11-11 12:40:43.425   453   462 D BrcmNciX: 21011b000501030001030103000104010300010500030001000003000102
11-11 12:40:43.430   453   462 D BrcmNciR: 41010100
11-11 12:40:43.431   453   462 D BrcmNciX: 20021701291446666d010112020207ff03020013040164070103
11-11 12:40:43.434   453   462 D BrcmNciR: 4002020000
11-11 12:40:43.435   453   462 D BrcmNciX: 20021a02611446666d010112020207ff03020013040164070103600108
11-11 12:40:43.442   453   462 D BrcmNciR: 4002020000
11-11 12:40:43.442   453   462 D BrcmNciX: 20021005300104310100320160380100500102
11-11 12:40:43.444  6041  8012 I OMXClient: IOmx service obtained
11-11 12:40:43.445  2876  2925 I OMXMaster: makeComponentInstance(OMX.google.vorbis.decoder) in android.hardwar process
11-11 12:40:43.446   453   462 D BrcmNciR: 4002020000
11-11 12:40:43.448   453   462 D BrcmNciX: 2002050100024d01
11-11 12:40:43.450   453   462 D BrcmNciR: 4002020000
11-11 12:40:43.452   453   462 D BrcmNciX: 2103170b00010101020103010501800182018301850106017701
11-11 12:40:43.457   453   462 D BrcmNciR: 41030100

`

**Comment by SkewedZeppelin** [comment]
NFC is fully functional on my clark. Was able to read my Yubikey without issue.

**Comment by AgentSteel** [comment]
Ah, thanks for your input. 

Can't read/detect any tags with mine.

Maybe the NFC is dead. Too lazy right now to disassemble my phone right now, will do when the battery has to be replaced!

**Comment by SkewedZeppelin** [comment]
Do let me know how it goes.

You may also consider trying to flash firmware partitions (not
system/vendor/boot) again.

**Comment by AgentSteel** [comment]
Just flashed the December 17th 2024 Update and... NFC is back! :+1:  

Thanks again for your great work
