### ISSUE TITLE
[dumpling] fstab encryption + broken usb port issue: stranded?

### ISSUE THREAD

**Issue by olsonperrensen** [Divested-Mobile/DivestOS-Build#356]
Hi, I'm trying to flash GAPPS to my Oneplus 5T, with the issue being my port is broken. It only charges in recovery mode, if you plug it while booted it does not even detect it is charging let alone USB Debugging. Wireless ADB works, but I cannot sideload. USB OTG doesn't work either. 

Since fastboot would be useless here, and I am stuck with TWRP 3.7.1, it is not possible to neither flash DivestOS's own recovery image nor to have access to the file system. Every time I wipe /data and disable encryption I cannot disable it again after a factory reset hence there is no way I have found access the downloaded zip file I need. 

Doing some research it seems you need to tamper fstab inside /vendor/etc in order for it to be decrypted, but I have yet to see proper documentation on the subject. 

Edit: I did try microG (and I know both gapps and microG don't necessarily align with DivestOS's philosophy) but services like Maps and the like are broken. I did try FOSS alternatives and the maps seem to be broken too. I doubt this is a sensor issue. 

Could someone help me better troubleshoot my problem? I don't want to end up with a hard bricked device, more so without proper usb c port bindings. 

Thanks! Kr.

**Comment by SkewedZeppelin** [comment]
- sideload only works in the recovery
- encryption can't easily be disabbled
- you'll likely need to fix your usb port regardless
- flashing gapps is unlikely to work
- it sounds like you did not follow the correct steps to enable microG, you MUST chose the latest version manually not the one it suggests https://divestos.org/pages/faq#microgEnable
  - google maps does work with microG, I tested it very recently

**Comment by olsonperrensen** [comment]
Thank you. I will take a closer look.
