### ISSUE TITLE
Can not select adb root but service is running, please remove adb root prop

### ISSUE THREAD

**Issue by NgoHuy** [Divested-Mobile/DivestOS-Build#357]
As I see that we can search adb root from developer mode, but it redirects to developer options, we cannot select it. But the prop [init.svc.adb_root]: [running] is still exist. Please remove this prop to prevent some misfunction about ADB root

**Comment by SkewedZeppelin** [comment]
adb root is not supported on DivestOS and cannot be used

**Comment by NgoHuy** [comment]
I understand that adb root cannot be used. But our rom still show prop about adb_root. It leads to some misfunction about root status. Please remove it from your build.

**Comment by SkewedZeppelin** [comment]
The service runs regardless and advertises its state as not rooted.
Just because the name has root in it doesn't mean the device is rooted.
If an app is checking that property it is bad.

**Comment by NgoHuy** [comment]
firstly, [init.svc.adb_root]: [running] it means adb init as root, and this prop is useless when we dont have root. It leaked many false detections. Why do you set it when we dont need it? It means our rom is debuggable build? right

**Comment by SkewedZeppelin** [comment]
no, DivestOS primarily ships non-debuggable -user builds.
again this is just how it is, not going to change.
