### ISSUE TITLE
Mulch Problem

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [Divested-Mobile/DivestOS-Build#359]
Hey,

since a few Days I have this Problem that when I watch a bit YouTube Videos, I can't watch anymore, because it says, that I should login. I need to always close the Browser and then it works again, until a bit and then it happens again. And these are even not fsk 18 Videos. I don't know how this happens and I checked my VPN and tried to turn off most, but it don't change anything. And I have this Problem that sometimes I can't access YouTube because it says something about IP-Adress and I nedd to click several times in DuckDuckGo that it works finally again. I really don't know why these boths happen.

**Comment by SkewedZeppelin** [comment]
This is not a Mulch problem, this is a widespread issue with using VPNs.

**Comment by SkewedZeppelin** [comment]
YouTube is aggressively blocking VPNs and proxies and other shared connections.

You can try changing your exit via the refresh button in the Mullvad app.

**Comment by PrivacyAndSecurity** [comment]
Okay, I will. Thank you.

**Comment by PrivacyAndSecurity** [comment]
Would you say that Updates from Mullvad could have caused this Issue or that maybe YouTube goes more aggressive now against VPN Clients? Because I have a Feeling that YouTube could make it harder now, specially because after the uBlock Origin topic, where they go against it.

**Comment by SkewedZeppelin** [comment]
this is entirely on the YouTube side and affects all VPNs and even Tor
