### ISSUE TITLE
Twrp cannot open System partition

### ISSUE THREAD

**Issue by reyis4402** [Divested-Mobile/DivestOS-Build#36]
![IMG_20220113_145704_931](https://user-images.githubusercontent.com/60405617/149326083-9814a93a-249f-4fd0-b509-494b2029bb19.jpg)

**Comment by reyis4402** [comment]
Mi 9t Davinci - OrangeFox

**Comment by SkewedZeppelin** [comment]
What was the fix?

Did you mount the system first?
