### ISSUE TITLE
Store for DivestOS

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [Divested-Mobile/DivestOS-Build#360]
Hey,

i was thinking of an Store for DivestOS. (Like the GrapheneOS Store) And the Benefit in that would be that all Apps would be bundled in the offical Store, which would maybe reduce the load on the F-Droid Server + some People don't like F-Droid and this Problem would be away too. It would be really nice to use and practical too. (easier)

**Comment by SkewedZeppelin** [comment]
No. Use F-Droid with the DivestOS.org F-Droid repo. It has 7 mirrors too.
https://divestos.org/pages/our_apps#repos

**Comment by PrivacyAndSecurity** [comment]
I do that already.
