### ISSUE TITLE
[Pixel 3A XL bonito] Document workaround for unresponsive screen

### ISSUE THREAD

**Issue by ZhanYF** [Divested-Mobile/DivestOS-Build#368]
I recently replaced the screen of a Google Pixel 3A XL, on every boot up the screen will work until the phone went to sleep, and then the screen will stop responding to touch, until another reboot. 

After the screen became unresponsive, the rest of the phone would remain responsive during the locked state and it’s possible to unlock the screen with fingerprint, but there is no way to make the touchscreen responsive again without reboot.

To fix this, go to Settings -> System -> Gestures and disable Double-tap to check phone. After which the screen should no longer stuck into unresponsive state. This seems to be [a common problem](https://support.google.com/mail/thread/26404710/pixel-3a-xl-touch-not-working-after-locking-phone) affecting many phones with replaced screen.

I think we should document this workaround in the known problems page.

**Comment by SkewedZeppelin** [comment]
very interesting! I'll add this to the website soon

**Comment by SkewedZeppelin** [comment]
added to the papercuts section, thank you
