### ISSUE TITLE
oneplus2 fails to install from abd sideload (ERR6)

### ISSUE THREAD

**Issue by Kreyren** [Divested-Mobile/DivestOS-Build#4]
Using https://divestos.org/builds/LineageOS/oneplus2/divested-17.1-20210508-dos-oneplus2.zip fails to deploy using `adb sideload` to TWRP.

Same configuration works to deploy lineageOS.

**Comment by SkewedZeppelin** [comment]
Please try to install it using the DivestOS recovery.

**Comment by Kreyren** [comment]
Works now! thanks

Can i use TWRP with divestOS? (the divest recovery lacks features in comparison)

**Comment by SkewedZeppelin** [comment]
DivestOS recommends against the use of TWRP for the majority of devices to ensure image verification and flashing.
Use of TWRP also breaks the incremental OTA updates and provides attackers an easy way to dump your /data.

**Comment by Kreyren** [comment]
Can you elaborate on that? I though that it's sane as long as the device is encrypted since TWRP doesn't allow access (and doesn't have access to the device on technical level) without a password/pattern?
Also about the OTA i never had issues with any ROM using TWRP as when the OTA is performed it's handled by TWRP?

Or would you recommend any other recovery solution? I need:
- terminal access with Read+Write
- Ideally an internet connection (not available in TWRP)
- Perform backup/restore of the system
- Perform installation of images e.g. MagiskSU (that now needs patching of boot image)

**Comment by SkewedZeppelin** [comment]
>  about the OTA i never had issues with any ROM using TWRP 

No other ROM provides incremental updates like DivestOS does.

> I need

SeedVault is provided for backup/restore.
All the other reqs are not really compatible with DivestOS.

**Comment by Kreyren** [comment]
Makes sense, thanks for info
