### ISSUE TITLE
Failed trying to do a git submodule update

### ISSUE THREAD

**Issue by R1413** [Divested-Mobile/DivestOS-Build#48]
Please make sure you have the correct access permissions
and that the repository exists.
fatal: cloning 'git@gitlab.com:divested-mobile/kernel_patches.git' on '/home/r1413/DivestOS/Patches/Linux' failed

And that with all the submodules

**Comment by SkewedZeppelin** [comment]
You can manually edit the path to use the https endpoint instead in the git
config.

**Comment by R1413** [comment]
> You can manually edit the path to use the https endpoint instead in the git config.

sankiu

**Comment by mmvanheusden** [comment]
enable "show hidden folders" and open the /.git/config file.

make it look like this:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://gitlab.com/divested-mobile/divestos-build
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[submodule "Patches/Linux"]
	active = true
	url = https://gitlab.com/divested-mobile/kernel_patches
[submodule "Patches/DivestOS_Wallpapers"]
	active = true
	url = https://gitlab.com/divested-mobile/wallpapers
[submodule "PrebuiltApps"]
	active = true
	url = https://gitlab.com/divested-mobile/prebuilt_apps
```
