### ISSUE TITLE
OnePlus2 - Stuck at "Phone is starting..."

### ISSUE THREAD

**Issue by Kreyren** [Divested-Mobile/DivestOS-Build#5]
Seems that the launcher fails to start or could be the setup wizard?

**Comment by SkewedZeppelin** [comment]
Did you wipe /data before first boot?

**Comment by Kreyren** [comment]
Unless divestOS recovery does that by default i did not

**Comment by SkewedZeppelin** [comment]
Please try to perform a factory reset from the DivestOS recovery.
I hope you also backed up beforehand.

**Comment by Kreyren** [comment]
Getting black screen after the boot now

**Comment by SkewedZeppelin** [comment]
Black screen after OnePlus logo or DivestOS boot animation?

Earlier when you had the "Phone is starting..." did you see the background (orange/blue paint)?

Can you for good measure one more time:
- boot recovery
- adb sideload
- factory reset
- reboot

DivestOS doesn't make all too many modifications to the oneplus2 tree and it booting like it is rules out the kernel modifications.
A bit strange.

**Comment by Kreyren** [comment]
FWIW i am getting a `ring` when i disconnect the cable and it seems to respond to input so i assume it being an issue with display rendering?

**Comment by Kreyren** [comment]
> Black screen after OnePlus logo or DivestOS boot animation? 

After DivestOS boot animation

> Earlier when you had the "Phone is starting..." did you see the background (orange/blue paint)? 

Yes and i was able to access settings

> Can you for good measure one more time:

Did that same result

**Comment by Kreyren** [comment]
> DivestOS doesn't make all too many modifications to the oneplus2 tree and it booting like it is rules out the kernel modifications.

FWIW i had same issue on LineageOS before, but i am not sure what did they do to fix it.

**Comment by Kreyren** [comment]
Also i've just noticed that if i hold a power button it opens the power menu.

**Comment by Kreyren** [comment]
Pressing `Emergency` in power menu opens the UI with dialer (the one in lockscreen not the app) and i have access to the status bar, but not to settings or anything else.

**Comment by SkewedZeppelin** [comment]
I think I might have an idea on the cause.
I will have another build up in an hour or so.

**Comment by Kreyren** [comment]
FWIW i could flash TWRP and get read/write to the device through the built-in terminal if needed to e.g. rewrite you snippets of the logs, change things, etc..

**Comment by SkewedZeppelin** [comment]
A 20210529 build is up for testing.

**Comment by Kreyren** [comment]
Seems to work now, i got setup wizard and i have access to the UI without any noticable issues atm

**Comment by SkewedZeppelin** [comment]
Awesome!
Thank you for testing.

**Comment by Kreyren** [comment]
thanks for fixing! 

Btw. Cool OS! You pretty much fixed everything that i hate on LineageOS. ^-^

**Comment by Kreyren** [comment]
Also care to elaborate what was the issue?

**Comment by SkewedZeppelin** [comment]
Some devices don't like full dexpreopt.
I had hope that newer versions would've fixed this, but it doesn't appear so.
The fix is setting partial dexpreopt:
WITH_DEXPREOPT_BOOT_IMG_AND_SYSTEM_SERVER_ONLY := true
