### ISSUE TITLE
Device request: OnePlus 9 Pro

### ISSUE THREAD

**Issue by josefv2** [Divested-Mobile/DivestOS-Build#51]
I see most OnePlus devices are supported, but for some reason it stopped after OnePlus 9. I would like to contribute but unfortunately I don't know anything about code. However, I have this phone and I am willing to provide all the necessary to development of DOS for OP9 Pro. Also, I offer myself to test on my device all the builds to ensure they are working.

Is it likely a build will come for this device?

**Comment by SkewedZeppelin** [comment]
I only add new devices in batches.
I've added it to my list, but I give no time when it will arrive.

**Comment by SkewedZeppelin** [comment]
Closing, will be tracked in #68
