### ISSUE TITLE
Question: Possibility to build with custom packages?

### ISSUE THREAD

**Issue by michaelschefczyk** [Divested-Mobile/DivestOS-Build#61]
I my be outdated, but I like to use android devices with z-push/activesync clients to connect to SOGo and Kopano. Open source implementations are rare. Hence, I currently build LineageOS 18.1 with the old com.android.email packages based on a manifest to include that from LOS 17.1 (https://github.com/lineageos4microg/docker-lineage-cicd/issues/204).

Is a similar way to build (without docker, of course) possible with DivestOS as well? If so, I would try for hotdogb. However it would be good to know that such way is possible including relocking the bootloader without bricking the device.

**Comment by SkewedZeppelin** [comment]
There are some lines in Patch.sh commented as `Remove Email`, simply remove
those and compile.
The resulting build will have AOSP Email + basic Exchange support.

There is a build guide here:
https://divestos.org/index.php?page=build

You'll also likely bump into this:
https://github.com/Divested-Mobile/DivestOS-Build/issues/48

**Comment by michaelschefczyk** [comment]
Thank you very much! I am sorry to say that I was not successful in mitigating issue #48, regardless of the content of the hidden file mentioned. Therefore, I will probably try again next month or so. Maybe then, the setup will work without extra adjustments.

**Comment by michaelschefczyk** [comment]
Getting beyond issue #48, did work and the cause was on my side: The snort IDS did block the relevant repo IP after the failures before changing the access as described.

I did take some steps to build for hotdogb. I was not certain about the recommended approach to get the vendor files. In the end, I did copy sm8150-common-vendor.mk and hotdogb-vendor.mk from a same-day build of LineageOS with microG based on lineageos4microg/docker-lineage-cicd.

The problem I could not overcome building on an i9-9900 CPU with 16 GB RAM was the following output of make -j5 generate_verity_key (## same with -j10 or -j20 of course):

08:47:27 ************************************************************
08:47:27 You are building on a machine with 15.5GB of RAM
08:47:27 
08:47:27 The minimum required amount of free memory is around 16GB,
08:47:27 and even with that, some configurations may not work.
08:47:27 
08:47:27 If you run into segfaults or other errors, try reducing your
08:47:27 -j value.
08:47:27 ************************************************************
[W][2022-03-21T09:47:27+0100][6059] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2022-03-21T09:47:27+0100][6059] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
LINEAGE_VERSION=18.1-20220321-UNOFFICIAL-hotdogb
TARGET_PRODUCT=lineage_hotdogb
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-2a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.0-19-amd64-x86_64-Debian-GNU/Linux-10-(buster)
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ3A.211001.001
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=vendor/oneplus/sm8150-common device/oneplus/sm8150-common hardware/oneplus vendor/oneplus/hotdogb device/oneplus/hotdogb hardware/qcom-caf/sm8150 vendor/qcom/opensource/commonsys-intf/display vendor/qcom/opensource/data-ipa-cfg-mgr vendor/qcom/opensource/dataservices vendor/qcom/opensource/commonsys/packages/apps/Bluetooth vendor/qcom/opensource/commonsys/system/bt/conf
============================================
[W][2022-03-21T09:47:28+0100][6096] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2022-03-21T09:47:28+0100][6096] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2022-03-21T09:47:28+0100][6107] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2022-03-21T09:47:28+0100][6107] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[W][2022-03-21T09:47:28+0100][6174] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2022-03-21T09:47:28+0100][6174] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[100% 1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
internal error: failed to find a dex jar path for module 'WfdCommon', note that some jars may be filtered out by module constraints
08:48:08 soong bootstrap failed with: exit status 1

Can someone please be so kind as to point me to what to try next?

**Comment by SkewedZeppelin** [comment]
That is not the proper way to get the vendor repository, you need the full vendor repo.

**Comment by michaelschefczyk** [comment]
Thank you very much! I am sorry, that my knowledge is quite limited. I am not building for fun or because I am able to contribute to development, but because I prefer active sync groupware (Kopano, SOGo) and I found building with lineageos4microg/docker-lineage-cicd with a modified manifest quite feasible. So I am hoping that I could also wrestle building DivestOS and relock the bootloader as a security measure after the end of full disk encryption.

The LineageOS build guide lists "Prepare the device-specivic code" (https://wiki.lineageos.org/devices/hotdogb/build) and mentions "breakfast hotdogb" and it literally says "This will download your device’s device specific configuration and kernel." So this is not enough and I need to do follow this step in addition to extract (current) blobs from installable ZIPs (?!?):

https://wiki.lineageos.org/extracting_blobs_from_zips#extracting-proprietary-blobs-from-payload-based-otas

As hotdogb is an A/B-system, I will probably need to follow the payload-based variant, correct? I assume, that in the end, I will intuitively see which files resulting from those steps will need to be moved where in order to build DivestOS?

**Comment by SkewedZeppelin** [comment]
You can try that method, but the result may not be correct.
Sorry I cannot help here with the proprietary blobs.

**Comment by michaelschefczyk** [comment]
OK, the LineageOS instructions overcome the this hurdle. This was correct:

https://wiki.lineageos.org/extracting_blobs_from_zips#extracting-proprietary-blobs-from-payload-based-otas

Then the next trap is resetWorkspace returning:

warning: Python 3 support is currently experimental. YMMV.
Please use Python 2.7 instead.

... A new version of repo (2.21) is available.
... You should upgrade soon:
    cp /build/DivestOS/Build/LineageOS-18.1/.repo/repo/repo /usr/bin/repo

fatal: duplicate path device/oneplus/hotdogb in /build/DivestOS/Build/LineageOS-18.1/.repo/manifest.xml

Doing cat /build/DivestOS/Build/LineageOS-18.1/.repo/manifest.xml does not reveal duplicate paths but just instructions to include "default.xml" as a manifest (from whereever).

How should one handle this "fatal"? Running resetWorkspace in python2.7 leads to a SyntaxError. Running patchWorkspace does not work in any python version leads to bash: $1: unbound variable.

**Comment by SkewedZeppelin** [comment]
You need to remove `.repo/local_manifests/roomservice.xml`

As for the python error, only Fedora 34/35 is tested working with the script.

**Comment by michaelschefczyk** [comment]
Thanks again!! That brought me to the next step.

resetWorkspace does run through. patchWorkspace leads to:

WARNING: clamscan is unavailable, a malware scan will not be performed!
/build/DivestOS/Scripts/LineageOS-18.1//Patch.sh: 18: set: Illegal option -o pipefail
/build/DivestOS/Scripts/Common//Enable_Verity.sh: 18: set: Illegal option -o pipefail
/build/DivestOS/Scripts/Common//Copy_Keys.sh: 18: set: Illegal option -o pipefail
/build/DivestOS/Scripts/LineageOS-18.1//Defaults.sh: 18: set: Illegal option -o pipefail
/build/DivestOS/Scripts/LineageOS-18.1//Rebrand.sh: 18: set: Illegal option -o pipefail
/build/DivestOS/Scripts/Common//Optimize.sh: 18: set: Illegal option -o pipefail
/build/DivestOS/Scripts/Common//Deblob.sh: 18: set: Illegal option -o pipefail
/build/DivestOS/Scripts/Common//Patch_CVE.sh: 18: set: Illegal option -o pipefail
/build/DivestOS/Scripts/Common//Post.sh: 18: set: Illegal option -o pipefail

I suspect that this might be a distro issue (Debian vs. Fedora). Is it critical? Do I need to switch to Fedora?

When entering "buildDevice hotdogb" the process quickly ends with:

FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: vendor/google/marlin/Android.bp:426:1: module "embmslibrary" variant "android_common": module source path "vendor/google/marlin/proprietary/vendor/framework/embmslibrary.jar" does not exist
error: vendor/google/sailfish/Android.bp:259:1: module "qcrilhook" variant "android_common": module source path "vendor/google/sailfish/proprietary/framework/qcrilhook.jar" does not exist
error: vendor/google/marlin/Android.bp:253:1: module "com.google.android.camera.experimental2016" variant "android_common": module source path "vendor/google/marlin/proprietary/framework/com.google.android.camera.experimental2016.jar" does not exist
error: vendor/google/sailfish/Android.bp:419:1: module "QtiTelephonyServicelibrary" variant "android_common": module source path "vendor/google/sailfish/proprietary/vendor/framework/QtiTelephonyServicelibrary.jar" does not exist
error: vendor/google/marlin/Android.bp:259:1: module "qcrilhook" variant "android_common": module source path "vendor/google/marlin/proprietary/framework/qcrilhook.jar" does not exist
error: vendor/google/sailfish/Android.bp:440:1: module "rcsservice" variant "android_common": module source path "vendor/google/sailfish/proprietary/vendor/framework/rcsservice.jar" does not exist
error: vendor/google/sailfish/Android.bp:253:1: module "com.google.android.camera.experimental2016" variant "android_common": module source path "vendor/google/sailfish/proprietary/framework/com.google.android.camera.experimental2016.jar" does not exist
error: vendor/google/marlin/Android.bp:440:1: module "rcsservice" variant "android_common": module source path "vendor/google/marlin/proprietary/vendor/framework/rcsservice.jar" does not exist
error: vendor/google/marlin/Android.bp:419:1: module "QtiTelephonyServicelibrary" variant "android_common": module source path "vendor/google/marlin/proprietary/vendor/framework/QtiTelephonyServicelibrary.jar" does not exist
error: vendor/google/marlin/Android.bp:433:1: module "qti-vzw-ims-internal" variant "android_common": module source path "vendor/google/marlin/proprietary/vendor/framework/qti-vzw-ims-internal.jar" does not exist
error: vendor/google/sailfish/Android.bp:433:1: module "qti-vzw-ims-internal" variant "android_common": module source path "vendor/google/sailfish/proprietary/vendor/framework/qti-vzw-ims-internal.jar" does not exist
error: vendor/google/sailfish/Android.bp:426:1: module "embmslibrary" variant "android_common": module source path "vendor/google/sailfish/proprietary/vendor/framework/embmslibrary.jar" does not exist

This is a surprise, because I did intend to limit building to hotdogb. For the other devices, I neither h ave proprietary blobs nor anything to do with them.

Regards,

Michael

**Comment by SkewedZeppelin** [comment]
You need to switch from dash to bash.
You can remove those other unneeded devices from the local manifest.

**Comment by SkewedZeppelin** [comment]
Successful output should look something like this https://divestos.org/misc/patchWorkspace-18.1.txt

**Comment by michaelschefczyk** [comment]
Sorry - next step -> next error. Now the build complains that TARGET_ARCH would not be defined by board config. This seems to be true when I look into the file at device/oneplus/hotdogb/BoardConfig.mk. Output:

[W][2022-03-21T17:05:59+0100][23030] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2022-03-21T17:05:59+0100][23030] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:277:
build/make/core/board_config.mk:144: error: TARGET_ARCH not defined by board config: device/oneplus/hotdogb/BoardConfig.mk.
16:05:59 dumpvars failed with: exit status 1
Device hotdogb not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_oneplus_hotdogb
Default revision: lineage-18.1
Checking branch info
Checking if device/oneplus/hotdogb is fetched from android_device_oneplus_hotdogb
LineageOS/android_device_oneplus_hotdogb already fetched to device/oneplus/hotdogb
Syncing repository to retrieve project.
warning: Python 3 support is currently experimental. YMMV.
Please use Python 2.7 instead.

... A new version of repo (2.21) is available.
... You should upgrade soon:
    cp /build/DivestOS/Build/LineageOS-18.1/.repo/repo/repo /usr/bin/repo

fatal: duplicate path device/oneplus/hotdogb in /build/DivestOS/Build/LineageOS-18.1/.repo/manifest.xml
Repository synced!
Looking for dependencies in device/oneplus/hotdogb
Looking for dependencies in device/oneplus/sm8150-common
device/oneplus/sm8150-common has no additional dependencies.
Done
[W][2022-03-21T17:06:01+0100][23122] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2022-03-21T17:06:01+0100][23122] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:277:
build/make/core/board_config.mk:144: error: TARGET_ARCH not defined by board config: device/oneplus/hotdogb/BoardConfig.mk.
16:06:01 dumpvars failed with: exit status 1
[W][2022-03-21T17:06:01+0100][23208] void cmdline::logParams(nsjconf_t *)():250 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[W][2022-03-21T17:06:01+0100][23208] void cmdline::logParams(nsjconf_t *)():260 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
In file included from build/make/core/config.mk:291:
In file included from build/make/core/envsetup.mk:277:
build/make/core/board_config.mk:144: error: TARGET_ARCH not defined by board config: device/oneplus/hotdogb/BoardConfig.mk.
16:06:02 dumpvars failed with: exit status 1

** Don't have a product spec for: 'lineage_hotdogb'
** Do you have the right repo manifest?


Did I delete something that should  not have been deleted, such as a default entry for TARGET_ARCH?

**Comment by michaelschefczyk** [comment]
Dear Tad,

Thanks a log for the immense help!

Presently, I am lost as I did seem to have the proprietary blobs already and now I seem to be unable to return to that point again (now, after repo sync, not even breakfast does work without errors about TARGET_ACRH missing in BoardConfig.mk).

I will need a fresh start on a fresh day and before that, I will have to make up my mind if I need to accept that my skills are insufficient to go beyond self-built LineageOS 18.1 with an activesync mail app, but also with an unlocked bootloader or if it may be realistic for me to acquire the skills to proceed beyond this point with DivestOS.

Regards,

Michael

**Comment by jensbakker01** [comment]
Thanks Tad for providing some steps here.
I tried to build for vayu and after 2 days of trying it finally worked. resetWorkspace gave me an error, and deleting a file worked.

Thanks for this great OS!

**Comment by michaelschefczyk** [comment]
Unfortunately, I did not get as far as ghost did.

When trying patchWorkspace, I get

bash: $1: unbound variable

What does this error want to tell me?

**Comment by michaelschefczyk** [comment]
Did try to build again, this time LOS 19.1 and enchilada after using ./extract-files.sh with an LOS 19.1 enchilada connected.

Upon "make -j20 generate_verity_key", the output ends with:

FAILED: out/soong/build.ninja
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/soong/.bootstrap/bin/soong_build")" && cd / && env -i "$BUILDER"     --top "$TOP"     --out "out/soong"     -n "out"     -d "out/soong/build.ninja.d"     -t -l out/.module_paths/Android.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used Android.bp
error: vendor/oneplus/sm8150-common/Android.bp:254:1: module "manifest_android.hardware.drm@1.3-service.widevine" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/manifest_android.hardware.drm@1.3-service.widevine.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:254:1: module "manifest_android.hardware.drm@1.3-service.widevine" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/manifest_android.hardware.drm@1.3-service.widevine.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:254:1: module "manifest_android.hardware.drm@1.3-service.widevine" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/manifest_android.hardware.drm@1.3-service.widevine.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:254:1: module "manifest_android.hardware.drm@1.3-service.widevine" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/manifest_android.hardware.drm@1.3-service.widevine.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:263:1: module "vendor.qti.gnss@4.0-service" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/vendor.qti.gnss@4.0-service.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:263:1: module "vendor.qti.gnss@4.0-service" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/vendor.qti.gnss@4.0-service.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:263:1: module "vendor.qti.gnss@4.0-service" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/vendor.qti.gnss@4.0-service.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:263:1: module "vendor.qti.gnss@4.0-service" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/vendor.qti.gnss@4.0-service.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:227:1: module "android.hardware.gnss@2.1-service-qti" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.gnss@2.1-service-qti.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:227:1: module "android.hardware.gnss@2.1-service-qti" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.gnss@2.1-service-qti.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:227:1: module "android.hardware.gnss@2.1-service-qti" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.gnss@2.1-service-qti.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:227:1: module "android.hardware.gnss@2.1-service-qti" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.gnss@2.1-service-qti.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:236:1: module "android.hardware.neuralnetworks@1.3-service-qti-hta" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti-hta.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:236:1: module "android.hardware.neuralnetworks@1.3-service-qti-hta" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti-hta.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:236:1: module "android.hardware.neuralnetworks@1.3-service-qti-hta" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti-hta.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:236:1: module "android.hardware.neuralnetworks@1.3-service-qti-hta" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti-hta.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:245:1: module "android.hardware.neuralnetworks@1.3-service-qti" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:245:1: module "android.hardware.neuralnetworks@1.3-service-qti" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:245:1: module "android.hardware.neuralnetworks@1.3-service-qti" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti.xml" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:245:1: module "android.hardware.neuralnetworks@1.3-service-qti" variant "android_arm64_armv8-a": module source path "vendor/oneplus/sm8150-common/proprietary/vendor/etc/vintf/manifest/android.hardware.neuralnetworks@1.3-service-qti.xml" does not exist
10:49:23 soong bootstrap failed with: exit status 1

What could be wrong, here?

If I try the same with hotdogb after extracting proprietary blobs from a DivestOS.zip, I similarly get:

FAILED: out/soong/build.ninja
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/soong/.bootstrap/bin/soong_build")" && cd / && env -i "$BUILDER"     --top "$TOP"     --out "out/soong"     -n "out"     -d "out/soong/build.ninja.d"     -t -l out/.module_paths/Android.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used Android.bp
error: vendor/oneplus/sm8150-common/Android.bp:186:1: module "tcmclient" variant "android_common": module source path "vendor/oneplus/sm8150-common/proprietary/system/framework/tcmclient.jar" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:174:1: module "WfdCommon" variant "android_common": module source path "vendor/oneplus/sm8150-common/proprietary/system/framework/WfdCommon.jar" does not exist
error: vendor/oneplus/sm8150-common/Android.bp:180:1: module "qcnvitems" variant "android_common": module source path "vendor/oneplus/sm8150-common/proprietary/system/framework/qcnvitems.jar" does not exist
09:57:30 soong bootstrap failed with: exit status 1

**Comment by SkewedZeppelin** [comment]
It means something is missing, verify everything in init.sh is correct.

**Comment by michaelschefczyk** [comment]
Thank you and sorry, I have given up. I will not build myself and I will rather accept that one must use the gmail app if one does want to use z-push/activesync.

For outsiders like myself it would be nice, if the project could clearly state if microg is included or not included. The about page https://divestos.org/index.php?page=about does still list it, while it does not seem to be included.
