### ISSUE TITLE
Mulch Blank homepage

### ISSUE THREAD

**Issue by reyis4402** [Divested-Mobile/DivestOS-Build#64]
I'm using version 99 of the Mulch browser and the homepage is strangely completely blank.
![Screenshot_20220302-213413_Mulch](https://user-images.githubusercontent.com/60405617/156426506-f5a98e2e-e533-49f3-97ff-ca1296e91f4a.png)

**Comment by SkewedZeppelin** [comment]
Indeed.

**Comment by reyis4402** [comment]
Yep

**Comment by reyis4402** [comment]
https://user-images.githubusercontent.com/60405617/156457959-373993d7-cee1-4024-9229-d4d9961a9bd2.mp4

**Comment by reyis4402** [comment]
Is there any fix for this error?

**Comment by reyis4402** [comment]
I deleted and reinstalled but it didn't fix it.

**Comment by SkewedZeppelin** [comment]
It will be fixed in the next update.
Please be patient.

**Comment by SkewedZeppelin** [comment]
Mulch 99.0.4844.58-1 is up, fixes blank new tab page and broken WebView
scrolling.

**Comment by reyis4402** [comment]
Fixed. Thanks.
