### ISSUE TITLE
Device request: Motorola Moto G7 Power (ocean)

### ISSUE THREAD

**Issue by rottenstonks** [Divested-Mobile/DivestOS-Build#65]
DivestOS supports osprey, harpia, victara, clark, griffin, merlin, surnia... Is there any chance we can get support for ocean (Motorola Moto G7 Power) as well? If so, how? We are willing to chip in a few bucks if a maintainer steps up, should that be needed at all. 

For what it is worth, it looks like upstream LineageOS offers official support for the device. LineageOS 18.1 builds are available on their [website](https://download.lineageos.org/ocean).

I own one of these and will happily flash alpha/beta DivestOS builds on it, to see how it fares and deliver a stable experience to potential users.

As @SkewedZeppelin indicated in another [issue](https://github.com/Divested-Mobile/DivestOS-Build/issues/51#issuecomment-1039372143), new devices get added to the list in batches and there are no ETAs; that is acknowledged and I am okay with that. Just thought opening this issue would help keep track of this request. If I need to amend anything, or can improve the format of the issue, let me know and I will make the necessary changes around.

Thanks!

**Comment by SkewedZeppelin** [comment]
Closing, will be tracked in #68
