### ISSUE TITLE
System Update

### ISSUE THREAD

**Issue by reyis4402** [Divested-Mobile/DivestOS-Build#66]
My Davinci device is not detecting the update.

![Screenshot_20220309-002910_Updater](https://user-images.githubusercontent.com/60405617/157328425-377fc37d-7609-4375-be75-679e0a77476f.png)

**Comment by SkewedZeppelin** [comment]
That is expected, there is a 12 hour cache window.
It'll show up later.

**Comment by SkewedZeppelin** [comment]
That is expected, there is a 12 hour cache window.
It'll show up later.
