### ISSUE TITLE
Audio Issues

### ISSUE THREAD

**Issue by rsssxd** [Divested-Mobile/DivestOS-Build#67]
I turn up the volume on the headphones to the highest level. However, the device constantly lowers the volume.

Suddenly the system shut down. It loads but the system shuts down as soon as it boots up.

I reset everything in recovery.

However, the volume level drops again, or even completely.

Mi 9T Davinci

**Comment by SkewedZeppelin** [comment]
That is very strange.
What version are you on?
Did you flash any modifications?

**Comment by reyis4402** [comment]
Latest version for Davinci. However, the previous version had this problem. It is not always repeated. I'll post a video if the problem recurs.

After restarting the device strongly, the system is gone.

**Comment by reyis4402** [comment]
I just disabled the FM radio app and that's it.

**Comment by SkewedZeppelin** [comment]
That is very strange.
What version are you on?
Did you flash any modifications?

**Comment by rsssxd** [comment]
I can't use Divest because it's lagging behind on the Android version.

I have the unofficial A13 Calyx on my Davinci device.

**Comment by rsssxd** [comment]
https://github.com/Divested-Mobile/DivestOS-Build/discussions/121
