### ISSUE TITLE
Sensor permission corrupt

### ISSUE THREAD

**Issue by rsssxd** [Divested-Mobile/DivestOS-Build#79]
If I turn off sensor permission for apps on 17.1, apps can still access sensors.

**Comment by SkewedZeppelin** [comment]
What device? What app are you testing with?

**Comment by SkewedZeppelin** [comment]
I have just again tested the sensors permission working correctly on clark/17.1
and klte/18.1

I am using the app "CPU Info" from F-Droid.

**Comment by rsssxd** [comment]
https://user-images.githubusercontent.com/60405617/163271514-8e657e75-5ac6-488a-a5e4-56014f568617.mp4

**Comment by rsssxd** [comment]
Mi 9T Davinci

**Comment by rsssxd** [comment]
GrapheneOS camera app

**Comment by SkewedZeppelin** [comment]
Sensors permission only blocks sensors like gyro/accelerometer/temperate, not
camera.

Camera and microphone are each controlled by their own permission.

**Comment by rsssxd** [comment]
I didn't know that 😂 Good then.

**Comment by rsssxd** [comment]
Sensor permission is on but it doesn't show anything.

![Screenshot_20220414-005715_CPU_Info](https://user-images.githubusercontent.com/60405617/163277304-bb41004d-61f3-490a-bc79-1a63ed7fb286.png)

**Comment by rsssxd** [comment]
Sensor permission on

![Screenshot_20220414-020912_Compass](https://user-images.githubusercontent.com/60405617/163284309-c8f2e22c-b8d8-4cd4-b2a5-facb90c7d46c.png)

**Comment by rsssxd** [comment]
It looks like the sensor permission is completely turned off system-wide.

**Comment by rsssxd** [comment]
https://www.f-droid.org/packages/com.bobek.compass/

**Comment by rsssxd** [comment]
Also the system pauses while setting sensor permissions.

**Comment by jensbakker01** [comment]
> It looks like the sensor permission is completely turned off system-wide.

Did you upgrade to a newer version while still having the old sensor toggle on (blocked)? That could be the issue here

**Comment by rsssxd** [comment]
I usually keep the normal sensor permission turned off and did not turn it on during the update.

**Comment by rsssxd** [comment]
I reset the system and tried again, but no change.

**Comment by SkewedZeppelin** [comment]
Reseting/wiping the system is *never* the fix.

Does auto rotate work?
Did sensors work previously?
Have you updated the firmware for your device?

**Comment by rsssxd** [comment]
I want to disable verified boot. Would the following two commands suffice? Is there anything else I need to flash?

fastboot --disable-verity --disable-verification

**Comment by SkewedZeppelin** [comment]
Verified boot is only enabled when bootloader is locked.
Given that bootloader locking would brick your davinci, you do not have verified
boot enabled.

**Comment by rsssxd** [comment]
Is it possible for you to take a look at the link below and confirm if it's causing the problem?

https://forum.xda-developers.com/t/successfully-unbricked-mi-9t.4095107/

**Comment by SkewedZeppelin** [comment]
Are you saying your phone is bricked now?

**Comment by rsssxd** [comment]
No, the device is not currently bricked. But it got bricked while trying to update Firmware.

I recovered the device but the Firmware version is out of date and installing new Firmware prevents installing all roms.

**Comment by rsssxd** [comment]
@SkewedZeppelin Can DivestOS update firmware for davinci?

**Comment by rsssxd** [comment]
A developer told me today that the Official LineageOS release for Davinci is using an older version of Vendor.

Can the DivestOS developer fix this?

![1038](https://user-images.githubusercontent.com/60405617/170686868-b624aa74-26d8-4883-b9d8-e81741258fc5.jpg)

**Comment by SkewedZeppelin** [comment]
That number is set by the system and DivestOS includes a compiled /vendor image.


You need to figure out what firmware you need for your device and flash that.

**Comment by rsssxd** [comment]
Unfortunately the developer working for Davinci does not update this.

This issue only exists in Davinci version of LineageOS.

This is causing many users to experience similar issues just like me.

It is breaking the firmware version update.

**Comment by rsssxd** [comment]
The persist partition of the device is corrupted

I was able to partially fix it. But the pop-up camera does not work. Only the rear camera works.

Before installing DivestOS, there was no firmware or persistence problem.

Also I have to remove encryption to install new ROM.

**Comment by rsssxd** [comment]
I completely solved the problem. But I will use other software until I upgrade to 19.1 for DivestOS Davinci.
