### ISSUE TITLE
oneplus2: Mull is not installed by default

### ISSUE THREAD

**Issue by Kreyren** [Divested-Mobile/DivestOS-Build#8]
There is a space in a launcher's foobar where i assume is mull supposed to be and it's not available until it's `updated` from the f-droid. So i assume it failed to build?

**Comment by SkewedZeppelin** [comment]
This is expected. Some of the supported devices do not have enough space in system to hold Mull.
So instead an empty 'shim' app is in its place.
F-Droid on first launch will prompt to update to the full Mull.
