### ISSUE TITLE
Editing hosts file

### ISSUE THREAD

**Issue by jensbakker01** [Divested-Mobile/DivestOS-Build#80]
Hi.

Is there any way to edit the hosts file? I found that the included doesnt block a few obvious tracking domains (namely from whatsapp etc). Is there any way to change this without rebuilding the entire rom?
Thanks.

Edit: the domains I am talking about are the following
`dit.whatsapp.net
p3a.brave.com
variations.brave.com
tiles.search.brave.com
`

**Comment by SkewedZeppelin** [comment]
You cannot edit the list.
You can however tell report the domains and I'll exclude them:

https://github.com/divestedcg/dnsrm

**Comment by SkewedZeppelin** [comment]
Next update includes a toggle on to control the hosts file
