### ISSUE TITLE
GPS doesn't fix on davinci

### ISSUE THREAD

**Issue by Eirikr70** [Divested-Mobile/DivestOS-Build#82]
Hello, happy owner of a davinci with DivestOS, I have noticed that the OS "sees" the satellites but doesn't seem to be capable to calculate a position. Tried with GPSTest.

**Comment by SkewedZeppelin** [comment]
GPS does work. DivestOS however removes many of the proprietary Qualcomm location blobs that speedup location processing.

> Devices will take longer to acquire a GPS lock. Please test using GPSTest app with *clear* and *direct* line of sky https://f-droid.org/en/packages/com.android.gpstest.osmdroid

GPS can take up to 12.5 minutes to acquire a lock: https://en.wikipedia.org/wiki/Time_to_first_fix

**Comment by rsssxd** [comment]
@Eirikr70 
Hello

I also use Davinci and I have a problem.

Does the sensor error I mentioned in the link below repeat for you?

I would be very happy if you could test it.

https://github.com/Divested-Mobile/DivestOS-Build/issues/79#issuecomment-1098563343

**Comment by Eirikr70** [comment]
Thanks @SkewedZeppelin for that answer. I then suppose I have to wait for a fix, and following fix should be faster if not too distant in time.
@rsssxd I absolutely don't have that problem : compass works fine for me, except if I de-activate sensors of course.

**Comment by 0nxku** [comment]
I have another phone than that, but I think these steps will generally help for any phone:
1. Enable microG in system settings: Settings → Security — Toggle on "microG enablement".
2. Install from F-Droid (enable microG repository): microG Services, microG Companion, microG Services Framework Proxy.
3. Install MozillaNlpBackend from F-Droid or some another NLP to do "geo" job.
4. Go to microG settings app that you will have after installing microG. Go to Health Check (or how it called in English), toggle on Approximate location access, Precise location access, Geodata background access, Battery optimization off.
5. Go to Location section in the exact microG app, toggle on all the toggles.

Geolocation might start working on your phone.  If not, try to reboot the system, if still not, try to reinstall an app that uses geolocation.

**Comment by SkewedZeppelin** [comment]
@0nxku 
microG does not support location backends anymore

microG on DivestOS has NO permission to inject location

NLP providers like microG cannot speedup GPS lock
