### ISSUE TITLE
Error installing my own build

### ISSUE THREAD

**Issue by ghost** [Divested-Mobile/DivestOS-Build#84]
Hi.
I just finished building divestOS but I have no idea how to flash the zip. TWRP gives me an error and divestos recovery aswell.
see screenshot
![image](https://user-images.githubusercontent.com/104061102/164498962-c99a3afc-cd59-4790-8861-f6f985d77493.png)

**Comment by SkewedZeppelin** [comment]
TWRP is not supported, please read the installation steps:
https://divestos.org/index.php?page=bootloader#fastboot

**Comment by SkewedZeppelin** [comment]
Also please post the error you get from recovery.

DivestOS recovery will reject if not properly signed.

Also there are a handful of undocumented steps like sourcing vendor blobs.
And you won't receive webview updates in custom builds.

**Comment by jensbakker69** [comment]
I signed the OTA, and used the dosrecovery . Works now.

If I run repo sync will the webview be updated again?

**Comment by SkewedZeppelin** [comment]
cool

and yes webview will be updated on sync, just not via the f-droid repo due to
key mismatch

**Comment by SkewedZeppelin** [comment]
TWRP is not supported, please read the installation steps:
https://divestos.org/index.php?page=bootloader#fastboot
