### ISSUE TITLE
DivestOS 19.1 shows no boot logo while booting on fajita

### ISSUE THREAD

**Issue by EmanuelLoos** [Divested-Mobile/DivestOS-Build#86]
The screen just stays dark and it is not clear that it boots (it does). Is this intended?

**Comment by SkewedZeppelin** [comment]
> stays dark

Please read the known issues:
https://divestos.org/index.php?page=news-future#twelve

That issue has already been fixed but won't be available until the next builds.

> preinstalled Gallery

Simple Gallery *is* the preinstalled gallery.
Please read the list of preinstall apps:
https://divestos.org/index.php?page=technical_details#includedApps

**Comment by EmanuelLoos** [comment]
Oh, sorry for not looking there first.
