### ISSUE TITLE
oneplus2: Camera use crashes

### ISSUE THREAD

**Issue by Kreyren** [Divested-Mobile/DivestOS-Build#9]
### Steps to reproduce
0. Install [com.nextcloud.client](https://f-droid.org/en/packages/com.nextcloud.client/) and get a nextcloud account
1. Create an application password on your nextcloud account e.g. from thegood.cloud or tab.digital
2. Give the app permission to use the camera
3. Try to scan the QR code using the app and expect OS to crash

```console
kreyren@leonid:~$ adb logcat com.nextcloud.client
[snip]
05-30 03:46:49.728  7075  7075 F DEBUG   : pid: 796, tid: 7071, name: CAM_eztuneSrvr  >>> /vendor/bin/mm-qcamera-daemon <<<
05-30 03:46:49.728  7075  7075 F DEBUG   : uid: 1006
05-30 03:46:49.728  7075  7075 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
05-30 03:46:49.728  7075  7075 F DEBUG   :     r0  00000000  r1  00001b9f  r2  00000006  r3  daf93098
05-30 03:46:49.728  7075  7075 F DEBUG   :     r4  daf930ac  r5  daf93090  r6  0000031c  r7  0000016b
05-30 03:46:49.728  7075  7075 F DEBUG   :     r8  daf930a8  r9  daf93098  r10 daf930c8  r11 daf930b8
05-30 03:46:49.728  7075  7075 F DEBUG   :     ip  00001b9f  sp  daf93068  lr  e8dfd263  pc  e8dfd276
[snip]
05-30 03:46:54.085  7040  7040 W CAM_MctWorker: type=1400 audit(0.0:730): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=1827 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
05-30 03:46:54.390   796  7040 E libc    : Access denied finding property "persist.camera.isp.regdump"
05-30 03:46:54.089  7040  7040 W CAM_MctWorker: type=1400 audit(0.0:731): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=1827 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
05-30 03:46:54.406   796  7040 E libc    : Access denied finding property "persist.camera.isp.offregdump"
05-30 03:46:54.435   796  7040 E libc    : Access denied finding property "persist.camera.dumpmetadata"
05-30 03:46:54.465   796  7040 E libc    : Access denied finding property "persist.camera.isp.regdump"
05-30 03:46:54.469   796  7040 E libc    : Access denied finding property 
[snip]
05-30 03:46:54.917  7040  7040 W CAM_MctWorker: type=1400 audit(0.0:749): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=1827 scontext=u:r:mm-qcamerad:s0 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
```

Full logcat: https://gist.github.com/Kreyren/843ef6d8b2d4ee6e1b70dac6182bf84a

**Comment by SkewedZeppelin** [comment]
Does the normal camera app, OpenCamera cause the system to crash too?

**Comment by Kreyren** [comment]
@SkewedZeppelin OpenCamera causes the crash too

**Comment by SkewedZeppelin** [comment]
Seems to just be a SELinux denial, I can upload a boot.img to test in 20 mins.

**Comment by Kreyren** [comment]
Also i've just notice there being an update for 29th May that i do not have updated

**Comment by Kreyren** [comment]
> Seems to just be a SELinux denial, I can upload a boot.img to test in 20 mins. @SkewedZeppelin 

I've installed MagiskSU could that affect it?

**Comment by SkewedZeppelin** [comment]
> being an update for 29th May that i do not have updated

That is the same build you are on.
Happens because the Updater app hasn't recorded any updates yet.

> MagiskSU could that affect it

While root isn't supported, it shouldn't cause this.

You can try `setenforce 0` from a terminal and opening the camera however.

**Comment by Kreyren** [comment]
Does not crash with `setenforce 0` in OpenCamera and NextCloud

**Comment by SkewedZeppelin** [comment]
Cool, can you provide: `adb logcat -b all -d | grep -i audit` ?

**Comment by Kreyren** [comment]
Also crashes on non-magiskSU boot.img (i've made a backup in TWRP)

**Comment by Kreyren** [comment]
> adb logcat -b all -d | grep -i audit

http://ix.io/3ohG

**Comment by SkewedZeppelin** [comment]
Give this a test https://divestos.org/testing/boot-oneplus2-camerafix.img

**Comment by Kreyren** [comment]
Flashed using TWRP, still crashes

**Comment by SkewedZeppelin** [comment]
Strange. Logcat again?

**Comment by Kreyren** [comment]
It camera now it says that camera might be in use by other application so it seems that the crash is less frequent now? (halted, gave me a black screen and then recovered)

```console
kreyren@leonid:~$ { adb logcat -b all -d | grep -i audit ;} | ix
http://ix.io/3ohQ
kreyren@leonid:~$ { adb logcat net.sourceforge.opencamera ;} | ix
http://ix.io/3ohR
```

**Comment by SkewedZeppelin** [comment]
https://divestos.org/testing/boot-oneplus2-camerafix2.img

**Comment by Kreyren** [comment]
```console
kreyren@leonid:~$ { adb logcat -b all -d | grep -i audit && adb logcat net.sourceforge.opencamera ;} | ix
http://ix.io/3ohZ
```

**Comment by SkewedZeppelin** [comment]
> 3ohZ
Was that with camerafix2.img?

**Comment by Kreyren** [comment]
@SkewedZeppelin yes, installed using TWRP. Want me repeat the attempt?

**Comment by Kreyren** [comment]
Optionally i can add command in that returns some identification of the kernel used?

**Comment by Kreyren** [comment]
```console
kreyren@leonid:~$ adb shell uname -a
Linux localhost 3.10.108-dos.p209+ #1 SMP PREEMPT Sat May 29 22:17:28 EDT 2021 aarch64
```

**Comment by SkewedZeppelin** [comment]
That timestamp is off by 40 mins.
I am doing a clean build.
Will be up within the hour.


Thank you for being helping me work through this.

**Comment by Kreyren** [comment]
Noted, happy to help and thanks for working on it!

**Comment by Kreyren** [comment]
```console
kreyren@leonid:~$ date && adb shell uname -a && { adb logcat -b all -d | grep -i audit | ix ;} && adb shell monkey -p net.sourceforge.opencamera -v 1 2>&1 >/dev/null & adb logcat net.sourceforge.opencamera | { ix 2>/dev/null || ix ;}
[1] 8664
Sun 30 May 2021 05:20:05 AM CEST
Linux localhost 3.10.108-dos.p209+ #1 SMP PREEMPT Sat May 29 22:17:28 EDT 2021 aarch64
http://ix.io/3oij
[snip]
http://ix.io/3oik
[1]+  Done                    date && adb shell uname -a && { adb logcat -b all -d | grep -i audit | ix; } && adb shell monkey -p net.sourceforge.opencamera -v 1 2>&1 > /dev/null
```

Did second run for consistency

**Comment by SkewedZeppelin** [comment]
A 20210530 build is up.

**Comment by Kreyren** [comment]
Says that the recovery img is corrupted

**Comment by SkewedZeppelin** [comment]
Likely have to flash via DivestOS recovery

**Comment by Kreyren** [comment]
I was trying to flash the DivestOS recovery as the build gives me Err6 (sorry should have been more specific)

**Comment by Kreyren** [comment]
to clarify: DivestOS recovery fails with "ZIP file corrupted" in TWRP sideloading

**Comment by Kreyren** [comment]
and the device is still locked.. trying to get LOS to unlock the bootloader now

**Comment by SkewedZeppelin** [comment]
Assuming you had locked after you installed DivestOS:
- you need to boot twrp
- flash twrp to boot (as a backup)
- flash the recovery from the last available stock image
- reboot to fastboot
- fastboot oem unlock
- it should at this point reboot to the stock recovery and do the unlock
- it should then reboot and since twrp is on boot, enter twrp
- from there you can flash whatever

if you want to continue to use DivestOS:
- flash DivestOS recovery from fastboot
- adb sideload DivestOS from DivestOS recovery
- do not relock (as it is clearly broken on this device)

**Comment by Kreyren** [comment]
I wasn't able to unlock the bootloader on LOS, but i got Divested-recovery on the device and was able to flash it in TWRP to then install 20210530, but i am getting behavior similar to https://github.com/Divested-Mobile/DivestOS-Build/issues/5 after DivestOS logo i get blackscreen with no UI

> fastboot oem unlock

forgot to do that x.x

**Comment by Kreyren** [comment]
FWIW i prefer to have the bootloader locked on daily use

**Comment by Kreyren** [comment]
also i am getting response to buttons and when i replug the charging cable i am getting a "ring" noise so i assume it booted, but failed to render the display?

**Comment by Kreyren** [comment]
> if you want to continue to use DivestOS:

i do! :)

**Comment by Kreyren** [comment]
EDIT: I can now get the power menu to access limited UI through pressing "emergengy" so it seems as same issue in https://github.com/Divested-Mobile/DivestOS-Build/issues/5 ?

**Comment by SkewedZeppelin** [comment]
Yep, seems I accidentally reverted the fix in https://github.com/Divested-Mobile/DivestOS-Build/commit/1c9a66f896f33d5816b7a99005003984bd19a419#diff-211c96ea3d4848ac3b0ff6d58c553e9c802200698ed2698a2029fcd4d8524c6b

**Comment by Kreyren** [comment]
FWIW if you are limited on processing resources you could use https://gitpod.io it provides vscode-clone in web browser with 16 threads CPU (shared across X amount of users in kubernetes) and is free for open-source.

e.g. https://gitpod.io/#https://github.com/Divested-Mobile/DivestOS-Build/issues/9

**Comment by SkewedZeppelin** [comment]
I have enough processing power to compile 80+ builds in <48 hours.
The slowest part is signing, and uploading.

oneplus2 in this case takes 28 minutes to compile, 3 minutes to sign, and 8 minutes to upload.

**Comment by Kreyren** [comment]
Same issue on:

a8719d5dc654455e9ed05dd5f77165fdea0cd4961bc6af5c0014fc252e3689c0  divested-17.1-20210530-dos-oneplus2.zip

**Comment by SkewedZeppelin** [comment]
Same issue as in black screen or broken camera?

:eyes:

**Comment by Kreyren** [comment]
Oh same blackscreen as in #5

**Comment by Kreyren** [comment]
FWIW 20210529 works for the black screen issue

```
kreyren@leonid:~/Downloads$ sha256sum divested-17.1-20210529-dos-oneplus2.zip 
0aa342dcbd63843bb533c49f049164de180a2b3731ad3afd5e3b88aa7b196264  divested-17.1-20210529-dos-oneplus2.zip
```

**Comment by SkewedZeppelin** [comment]
I made 3 changes in 0529:
- disabled dexpreopt
- reverted a camera commit (broke shamu recently)
- disabled mm-pp-daemon removal

I thought at first the fix was the dexpreopt removal.
But I received a report that ether was having the same black screen issue. I made an ether build with the dexpreopt change and that reportedly failed to boot.
Then I saw that oneplus2 and ether both had the mm-pp-daemon service not disabled in init.
So I removed the mm-pp-daemon service.
In the first 20210530 build you reported that it didn't boot.
That rules out the service.
In the second 20210530 build I added back the dexpreopt change and you reported it didn't boot.

I am now making another build with no dexpreopt change and without removing the mm-pp-daemon at all.

If this boots that means one of two things:
- one of the libraries I remove are used by dynamically loaded by another library that I do not see
- the mm-pp-daemon is actually required for some reason on this device + potentially ether too

**Comment by SkewedZeppelin** [comment]
Another 20210530 is up.
:crossed_fingers:

**Comment by Kreyren** [comment]
```console
kreyren@leonid:~/Downloads$ sha256sum divested-17.1-20210530-dos-oneplus2.zip.1
abc35077cf864583fd731c4a300b0b483a616e6166f274956ec2f303968fb313  divested-17.1-20210530-dos-oneplus2.zip.1
```

Installed, after boot i get to the UI, but camera still crashes the system.


```console
kreyren@leonid:~$ date \
&& adb shell uname -a \
&& { { adb logcat -b all -d | grep -i audit ;} | ix ;} \
&& adb shell monkey -p net.sourceforge.opencamera -v 1 2>&1 >/dev/null \
&& { adb logcat net.sourceforge.opencamera | { ix 2>/dev/null | ix ;} ;}
Sun 30 May 2021 09:41:02 AM CEST
Linux localhost 3.10.108-dos.p209+ #1 SMP PREEMPT Sun May 30 02:12:05 EDT 2021 aarch64
http://ix.io/3oj8
args: [-p, net.sourceforge.opencamera, -v, 1]
 arg: "-p"
 arg: "net.sourceforge.opencamera"
 arg: "-v"
 arg: "1"
data="net.sourceforge.opencamera"
http://ix.io/2Us8
```

**Comment by SkewedZeppelin** [comment]
I will need to look into the camera issue more, dissapointing.

Can you as root, remount /system rw, and `mv system/vendor/bin/mm-pp-daemon system/vendor/bin/mm-pp-daemon.bak`.
And see if the system still boots after? To determine if it is the daemon that is truly required, or just one of its libraries.

**Comment by Kreyren** [comment]
Rooted the phone using magisk and `/system` is not mounted or mountable

https://gist.githubusercontent.com/Kreyren/f780817ce8935aabcce4b708163420eb/raw/a9a32a2a315189a6c7e5694dd207dfb244740408/gistfile1.txt

**Comment by SkewedZeppelin** [comment]
A 20210531 build is up for testing.
Grants more permissions to qcamerad.

**Comment by Kreyren** [comment]
Seems to work!

no blackscreen and crashing in the net.sourceforge.opencamera

**Comment by Kreyren** [comment]
Nextcloud also works

**Comment by SkewedZeppelin** [comment]
> crashing in the net.sourceforge.opencamera

To confirm, camera does work? or it still crashes?

**Comment by Kreyren** [comment]
Sorry i missed the reply. Yes camera works
