### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by zqpvr** [Divested-Mobile/DivestOS-Build#90]
Would I be able to build Divest OS for the nintendo switch LineageOS fork? https://forum.xda-developers.com/t/rom-unofficial-switchroot-android-10.4229761/ it would be cool to see divest os on and nintendo switch but I don't know if it is possible am on CFW

**Comment by SkewedZeppelin** [comment]
Is it possible, probably.

Will it ever be suppoorted? Unlikely.

**Comment by zqpvr** [comment]
it is tegra it uses and arm64
