### ISSUE TITLE
I am getting an error please help

### ISSUE THREAD

**Issue by zqpvr** [Divested-Mobile/DivestOS-Build#91]
root@mx:/home/user/Build/LineageOS-18.1/DivestOS# git submodule update --init --recursive
Cloning into '/home/user/Build/LineageOS-18.1/DivestOS/Patches/Linux'...
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@gitlab.com:divested-mobile/kernel_patches.git' into submodule path '/home/user/Build/LineageOS-18.1/DivestOS/Patches/Linux' failed
Failed to clone 'Patches/Linux'. Retry scheduled
Cloning into '/home/user/Build/LineageOS-18.1/DivestOS/Patches/Wallpapers'...
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@gitlab.com:divested-mobile/wallpapers.git' into submodule path '/home/user/Build/LineageOS-18.1/DivestOS/Patches/Wallpapers' failed
Failed to clone 'Patches/Wallpapers'. Retry scheduled
Cloning into '/home/user/Build/LineageOS-18.1/DivestOS/PrebuiltApps'...
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@gitlab.com:divested-mobile/prebuilt_apps.git' into submodule path '/home/user/Build/LineageOS-18.1/DivestOS/PrebuiltApps' failed
Failed to clone 'PrebuiltApps'. Retry scheduled
Cloning into '/home/user/Build/LineageOS-18.1/DivestOS/Patches/Linux'...
git@gitlab.com: Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@gitlab.com:divested-mobile/kernel_patches.git' into submodule path '/home/user/Build/LineageOS-18.1/DivestOS/Patches/Linux' failed
Failed to clone 'Patches/Linux' a second time, aborting

**Comment by SkewedZeppelin** [comment]
https://github.com/Divested-Mobile/DivestOS-Build/issues/48

**Comment by SkewedZeppelin** [comment]
It is also strongly recommended you compile with Fedora Linux.

**Comment by zqpvr** [comment]
now i am getting Invalid cipherdir: directory /home/user/Build/LineageOS-18.1/DivestOS/.Signing_Keys not empty

**Comment by SkewedZeppelin** [comment]
Please read the manual for whatever file encryption program you are using

**Comment by SkewedZeppelin** [comment]
You should probably also try getting the hang of compiling vanilla LineageOS
first.

**Comment by zqpvr** [comment]
any idea how i can get that

**Comment by zqpvr** [comment]
i think it is gocryptfs

**Comment by zqpvr** [comment]
if it helps im using debian based system

**Comment by zqpvr** [comment]
fixed that
