### ISSUE TITLE
Building 19.1 / new 19.1 builds

### ISSUE THREAD

**Issue by ghost** [Divested-Mobile/DivestOS-Build#92]
Hi there.

Sorry that I created a github issue just for this, but I was wondering if all currently 18.1 devices will get DOS 19.1. If I look at my own device (vayu) the kernel/device tree hasn't been updated since december last year and it doesnt even have the 19.1 branch yet. Is there any hope for these devices to get DivestOS 19.1 support? Maybe by using the device tree from another rom like crdroid?

Will it be possible to build divestos 19.1 for vayu but instead of using the 18.1 kernel/tree manually downloading the 19.1 variant from crdroid?

thanks for your work on divestOS and keep this project going!

**Comment by SkewedZeppelin** [comment]
Be patient.
Vayu is likely to receive 19.1

> Relock

Xiaomi devices have a non-standard bootloader, bootloader locking on them will
likely never be possible.

> Can you unbrick those devices

I know of one person who hard bricked theirs and was unable to recover it at all
despite being technical.

**Comment by jensbakker69** [comment]
OK thanks.

Just saw that Lineage 19 was released, I cant wait for dos to come out aswell. Thanks
