### ISSUE TITLE
I tested DivestOS 19.1 cheeseburger OnePlus 5

### ISSUE THREAD

**Issue by helpthemfix** [Divested-Mobile/DivestOS-Build#94]
Here are the issues I encountered:

1. Settings app crashes repeatedly.
2. SIM card is not detected.
3. Mobile Network settings is greyed out.
4. There's no cellular signal despite being there on 18.1.
5. Phone app has no buttons at all and when I try to place a call the whole OS restarts.
6. The font in the settings app is abnormally large, although I'm not sure about it.
7. General laggness while using the phone.

**Comment by SkewedZeppelin** [comment]
Noted and will mark broken for now.
There aren't even official Lineage builds for it yet, so not surprising.


Thanks for testing.

**Comment by SkewedZeppelin** [comment]
If you are still on it, logs would be helpful.

**Comment by SkewedZeppelin** [comment]
ala
adb logcat -b all *:E

**Comment by SkewedZeppelin** [comment]
Most of these pending commits fix numerous crashes:
project:LineageOS/android_device_oneplus_msm8998-common status:open
branch:lineage-19.1

**Comment by helpthemfix** [comment]
> Those changes have merged and I've made new builds. I've personally tested working in-place while locked upgrade from 18.1 to 19.1 on my cheeseburger. Everything appears working well!
> 
> Please give it a spin. Backup first as always!

I switched to a daily driver Rom. I cant test it at the time. Thanks for your efforts!
