### ISSUE TITLE
oneplus 2: graphical bugs 

### ISSUE THREAD

**Issue by xlebun** [Divested-Mobile/DivestOS-Build#95]
bug 1: If i pick black as the accent color and then switch to dark mode/turn on the battery saver half of the icons and text become unreadable. [image1](https://i.postimg.cc/cxS9J205/Screenshot-20220505-144408-Settings.png) [image2](https://i.postimg.cc/tqk54grY/Screenshot-20220505-144346-Trebuchet.png) 

bug 2: there's no option to disable "Turn off sensors" icon in the status bar menu.

**Comment by SkewedZeppelin** [comment]
1 is an upstream Lineage bug, pick the dark theme when dark mode is enabled.

2, it is pretty important to know if it is on isn't it?

**Comment by xlebun** [comment]
> 1 is an upstream Lineage bug, pick the dark theme when dark mode is enabled. 
thanks for the info
>2, it is pretty important to know if it is on isn't it?
i think people should decide on their own, the menu exists for this reason.

**Comment by xlebun** [comment]
1. thanks for the info!
2. i think people must decide on their own, the menu exists for this reason. at least it would be great to have it

**Comment by xlebun** [comment]
btw, if you're interested maybe you could look at these two kernels ([1](https://github.com/mukul2259/kernel_oneplus_msm8994) [2](https://github.com/Pierre2324/AGK_android_kernel_oneplus_msm8994)) for op2 and maybe port something from them, coz despite the rom being awesome this phone struggles hard in the "performance department". 

tho maybe im asking for too much

**Comment by SkewedZeppelin** [comment]
Some minor erformance loss is expected and I won't add "riced out" kernel
patches.
