### ISSUE TITLE
ADB root option not available under developer options

### ISSUE THREAD

**Issue by tneo** [Divested-Mobile/DivestOS-Build#96]
I want to upgrade my XA2 to the next version. The option to enable ADB root is not showing under developer options and ADB needs that to flash the device. Is there a file I can edit to enable ADB root or another way to upgrade my device?

**Comment by SkewedZeppelin** [comment]
That is not how that works.

Just reboot to recovery, choose apply update, via sideload, then adb will
activiate.
Then you: adb sideload divested-19.1-20220426-dos-device.zip

Note: xa2 is untested on 19.1, it should work, but may not.
Always backup first!

You do NOT need root and you do NOT need to wipe to update.

**Comment by SkewedZeppelin** [comment]
Yes, that page does not really apply to DivestOS, and is just a left-over
remanent that needs to be adjusted.

**Comment by SkewedZeppelin** [comment]
That is not how that works.

Just reboot to recovery, choose apply update, via sideload, then adb will
activiate.
Then you: adb sideload divested-19.1-20220426-dos-device.zip

Note: xa2 is untested on 19.1, it should work, but may not.
Always backup first!

You do NOT need root and you do NOT need to wipe to update.
